// The character editor's labels (client/ui/customize.ts) in pt-BR, en, es and de, the order of LANGS: the editor has
// many, so they live here instead of strings.ts; apart from the editor's DOM code so the tests read them (PF-30).
import { LANGS } from '@shared/langs';
import { getLang } from './strings';

export const CUSTOMIZE_LABELS: Record<string, [string, string, string, string]> = {
  title: ['Personalizar personagem', 'Customize character', 'Personalizar personaje', 'Charakter anpassen'],
  tabBody: ['Corpo', 'Body', 'Cuerpo', 'Körper'],
  tabHair: ['Rosto e cabelo', 'Face & hair', 'Rostro y cabello', 'Gesicht & Haare'],
  tabTop: ['Parte de cima', 'Tops', 'Parte de arriba', 'Oberteile'],
  tabBottom: ['Parte de baixo', 'Bottoms', 'Parte de abajo', 'Unterteile'],
  tabShoes: ['Calçados', 'Shoes', 'Calzado', 'Schuhe'],
  tabHead: ['Cabeça', 'Headwear', 'Cabeza', 'Kopf'],
  tabAcc: ['Acessórios', 'Accessories', 'Accesorios', 'Accessoires'],
  tabTactical: ['Tático', 'Tactical', 'Táctico', 'Taktisch'],
  tabPcd: ['Modo PCD', 'PCD mode', 'Modo PcD', 'Inklusionsmodus'],
  search: ['Buscar peça…', 'Search items…', 'Buscar pieza…', 'Teil suchen…'],
  results: ['Resultados', 'Results', 'Resultados', 'Ergebnisse'],
  noResults: ['Nada encontrado.', 'Nothing found.', 'No se encontró nada.', 'Nichts gefunden.'],
  soon: [
    'As peças desta categoria chegam nas próximas atualizações.',
    'Items in this category arrive in the next updates.',
    'Las piezas de esta categoría llegan en las próximas actualizaciones.',
    'Teile dieser Kategorie kommen mit den nächsten Updates.',
  ],
  height: ['Altura', 'Height', 'Altura', 'Größe'],
  build: ['Biotipo', 'Build', 'Complexión', 'Statur'],
  skin: ['Cor da pele', 'Skin color', 'Color de piel', 'Hautfarbe'],
  hairStyle: ['Cabelo', 'Hair', 'Cabello', 'Frisur'],
  hairColor: ['Cor do cabelo e da barba', 'Hair & beard color', 'Color del cabello y la barba', 'Haar- und Bartfarbe'],
  beard: ['Barba', 'Facial hair', 'Barba', 'Bart'],
  eyeColor: ['Cor dos olhos', 'Eye color', 'Color de ojos', 'Augenfarbe'],
  eyeStyle: ['Olhos', 'Eyes', 'Ojos', 'Augen'],
  redondo: ['Redondos', 'Round', 'Redondos', 'Rund'],
  amendoado: ['Amendoados', 'Almond', 'Almendrados', 'Mandelförmig'],
  marcante: ['Marcantes', 'Sharp', 'Marcados', 'Markant'],
  caido: ['Caídos', 'Downturned', 'Caídos', 'Hängend'],
  puxado: ['Puxados', 'Upturned', 'Rasgados', 'Schräg'],
  grande: ['Grandes', 'Big', 'Grandes', 'Groß'],
  // The face (keys prefixed: some values repeat across features).
  faceShape: ['Formato do rosto', 'Face shape', 'Forma del rostro', 'Gesichtsform'],
  'formato.oval': ['Oval', 'Oval', 'Ovalado', 'Oval'],
  'formato.quadrado': ['Quadrado', 'Square', 'Cuadrado', 'Eckig'],
  'formato.redondo': ['Redondo', 'Round', 'Redondo', 'Rund'],
  'formato.longo': ['Fino e longo', 'Long', 'Delgado y largo', 'Lang und schmal'],
  'formato.coracao': ['Coração', 'Heart', 'Corazón', 'Herzförmig'],
  brows: ['Sobrancelhas', 'Brows', 'Cejas', 'Augenbrauen'],
  'sobrancelhas.reta': ['Retas', 'Straight', 'Rectas', 'Gerade'],
  'sobrancelhas.arqueada': ['Arqueadas', 'Arched', 'Arqueadas', 'Gebogen'],
  'sobrancelhas.grossa': ['Grossas', 'Thick', 'Gruesas', 'Dicht'],
  'sobrancelhas.fina': ['Finas', 'Thin', 'Finas', 'Dünn'],
  nose: ['Nariz', 'Nose', 'Nariz', 'Nase'],
  'nariz.reto': ['Reto', 'Straight', 'Recta', 'Gerade'],
  'nariz.largo': ['Largo', 'Wide', 'Ancha', 'Breit'],
  'nariz.aquilino': ['Aquilino', 'Aquiline', 'Aguileña', 'Adlernase'],
  'nariz.arrebitado': ['Arrebitado', 'Upturned', 'Respingada', 'Stupsnase'],
  mouth: ['Boca', 'Mouth', 'Boca', 'Mund'],
  'boca.media': ['Média', 'Medium', 'Mediana', 'Mittel'],
  'boca.fina': ['Lábios finos', 'Thin lips', 'Labios finos', 'Schmale Lippen'],
  'boca.carnuda': ['Lábios carnudos', 'Full lips', 'Labios carnosos', 'Volle Lippen'],
  ears: ['Orelhas', 'Ears', 'Orejas', 'Ohren'],
  'orelhas.normal': ['Normais', 'Normal', 'Normales', 'Normal'],
  'orelhas.pequena': ['Pequenas', 'Small', 'Pequeñas', 'Klein'],
  'orelhas.abano': ['De abano', 'Protruding', 'Salidas', 'Abstehend'],
  marks: ['Marcas', 'Marks', 'Marcas', 'Merkmale'],
  'marcas.nenhuma': ['Nenhuma', 'None', 'Ninguna', 'Keine'],
  'marcas.sardas': ['Sardas', 'Freckles', 'Pecas', 'Sommersprossen'],
  'marcas.cicatriz': ['Cicatriz', 'Scar', 'Cicatriz', 'Narbe'],
  'marcas.pinta': ['Pinta', 'Beauty mark', 'Lunar', 'Schönheitsfleck'],
  animIdle: ['Parado', 'Idle', 'Quieto', 'Stehen'],
  animWalk: ['Andar', 'Walk', 'Caminar', 'Gehen'],
  animRun: ['Correr', 'Run', 'Correr', 'Rennen'],
  animDance: ['Dançar', 'Dance', 'Bailar', 'Tanzen'],
  animAim: ['Mirar', 'Aim', 'Apuntar', 'Zielen'],
  random: ['Aleatório', 'Random', 'Aleatorio', 'Zufällig'],
  copyJson: ['Copiar JSON', 'Copy JSON', 'Copiar JSON', 'JSON kopieren'],
  copied: ['Configuração copiada (JSON).', 'Config copied (JSON).', 'Configuración copiada (JSON).', 'Konfiguration kopiert (JSON).'],
  exportGlb: ['Exportar GLB', 'Export GLB', 'Exportar GLB', 'GLB exportieren'],
  exported: [
    'Modelo exportado (personagem.glb).',
    'Model exported (personagem.glb).',
    'Modelo exportado (personagem.glb).',
    'Modell exportiert (personagem.glb).',
  ],
  P: ['Cor principal', 'Main color', 'Color principal', 'Hauptfarbe'],
  S: ['Cor secundária', 'Secondary color', 'Color secundario', 'Zweitfarbe'],
  D: ['Detalhe', 'Detail', 'Detalle', 'Detail'],
  arm: ['Braço ou mão', 'Arm or hand', 'Brazo o mano', 'Arm oder Hand'],
  leg: ['Perna', 'Leg', 'Pierna', 'Bein'],
  pcdHint: [
    'Personagem sem um braço, uma mão ou uma perna. A hitbox fica menor; sem mão ou braço recarrega 30% mais devagar, sem perna anda 25% mais devagar. Aparece também nas mãos em primeira pessoa.',
    'A character missing an arm, a hand or a leg. Smaller hitbox; no hand or arm reloads 30% slower, no leg moves 25% slower. Also shown on the first-person hands.',
    'Personaje sin un brazo, una mano o una pierna. La hitbox es más pequeña; sin mano o brazo recarga un 30% más lento, sin pierna camina un 25% más lento. También aparece en las manos en primera persona.',
    'Charakter ohne einen Arm, eine Hand oder ein Bein. Die Hitbox wird kleiner; ohne Hand oder Arm lädt er 30% langsamer nach, ohne Bein läuft er 25% langsamer. Auch an den Händen in der Ego-Perspektive sichtbar.',
  ],
  save: ['SALVAR', 'SAVE', 'GUARDAR', 'SPEICHERN'],
  cancel: ['Cancelar', 'Cancel', 'Cancelar', 'Abbrechen'],
  reset: ['Restaurar padrão', 'Reset to default', 'Restaurar predeterminado', 'Standard wiederherstellen'],
  saved: ['Personagem salvo.', 'Character saved.', 'Personaje guardado.', 'Charakter gespeichert.'],
  effects: ['No jogo', 'In the game', 'En el juego', 'Im Spiel'],
  health: ['Vida', 'Health', 'Vida', 'Leben'],
  reload: ['Recarga', 'Reload', 'Recarga', 'Nachladen'],
  speed: ['Velocidade', 'Speed', 'Velocidad', 'Tempo'],
  hitbox: ['Hitbox', 'Hitbox', 'Hitbox', 'Hitbox'],
  dragHint: [
    'Arraste para girar · role para aproximar',
    'Drag to rotate · scroll to zoom',
    'Arrastra para girar · desplázate para acercar',
    'Ziehen zum Drehen · Scrollen zum Zoomen',
  ],
  none: ['Nenhum', 'None', 'Ninguno', 'Keins'],
  pequeno: ['Pequeno', 'Short', 'Bajo', 'Klein'],
  medio: ['Médio', 'Medium', 'Medio', 'Mittel'],
  alto: ['Alto', 'Tall', 'Alto', 'Groß'],
  magro: ['Magro', 'Slim', 'Delgado', 'Schlank'],
  gordo: ['Gordo', 'Heavy', 'Robusto', 'Kräftig'],
  complete: ['Completo', 'Full', 'Completo', 'Vollständig'],
  bracoEsq: ['Sem braço esq.', 'No left arm', 'Sin brazo izq.', 'Ohne linken Arm'],
  bracoDir: ['Sem braço dir.', 'No right arm', 'Sin brazo der.', 'Ohne rechten Arm'],
  maoEsq: ['Sem mão esq.', 'No left hand', 'Sin mano izq.', 'Ohne linke Hand'],
  maoDir: ['Sem mão dir.', 'No right hand', 'Sin mano der.', 'Ohne rechte Hand'],
  pernaEsq: ['Sem perna esq.', 'No left leg', 'Sin pierna izq.', 'Ohne linkes Bein'],
  pernaDir: ['Sem perna dir.', 'No right leg', 'Sin pierna der.', 'Ohne rechtes Bein'],
  // Groups of the catalog.
  camiseta: ['Camisetas e regatas', 'Tees & tanks', 'Camisetas (con y sin mangas)', 'T-Shirts & Tanktops'],
  blusa: ['Blusas e moletons', 'Sweaters & hoodies', 'Suéteres y sudaderas', 'Pullover & Hoodies'],
  jaqueta: ['Jaquetas e casacos (por cima)', 'Jackets & coats (over)', 'Chamarras y abrigos (encima)', 'Jacken & Mäntel (darüber)'],
  calca: ['Calças', 'Pants', 'Pantalones', 'Hosen'],
  short: ['Shorts e bermudas', 'Shorts', 'Shorts y bermudas', 'Shorts & Bermudas'],
  saia: ['Saias', 'Skirts', 'Faldas', 'Röcke'],
  calcado: ['Calçados', 'Shoes', 'Calzado', 'Schuhe'],
  // Slots.
  tronco: ['Parte de cima', 'Top', 'Parte de arriba', 'Oberteil'],
  sobreposicao: ['Jaqueta', 'Jacket', 'Chamarra', 'Jacke'],
  baixo: ['Parte de baixo', 'Bottoms', 'Parte de abajo', 'Unterteil'],
  cabeca: ['Cabeça', 'Head', 'Cabeza', 'Kopf'],
  rosto: ['Rosto', 'Face', 'Rostro', 'Gesicht'],
  orelhas: ['Orelhas', 'Ears', 'Orejas', 'Ohren'],
  pescoco: ['Pescoço', 'Neck', 'Cuello', 'Hals'],
  pulsoE: ['Pulso esquerdo', 'Left wrist', 'Muñeca izquierda', 'Linkes Handgelenk'],
  pulsoD: ['Pulso direito', 'Right wrist', 'Muñeca derecha', 'Rechtes Handgelenk'],
  maos: ['Mãos', 'Hands', 'Manos', 'Hände'],
  antebraco: ['Antebraço', 'Forearm', 'Antebrazo', 'Unterarm'],
  cotovelos: ['Cotovelos', 'Elbows', 'Codos', 'Ellbogen'],
  ombro: ['Ombro', 'Shoulder', 'Hombro', 'Schulter'],
  ombros: ['Ombros', 'Shoulders', 'Hombros', 'Schultern'],
  colete: ['Colete', 'Vest', 'Chaleco', 'Weste'],
  acessorioColete: ['No colete', 'On the vest', 'En el chaleco', 'An der Weste'],
  peito: ['Peito', 'Chest', 'Pecho', 'Brust'],
  costas: ['Costas', 'Back', 'Espalda', 'Rücken'],
  cintura: ['Cintura', 'Waist', 'Cintura', 'Hüfte'],
  coxaE: ['Coxa esquerda', 'Left thigh', 'Muslo izquierdo', 'Linker Oberschenkel'],
  coxaD: ['Coxa direita', 'Right thigh', 'Muslo derecho', 'Rechter Oberschenkel'],
  joelhos: ['Joelhos', 'Knees', 'Rodillas', 'Knie'],
  pes: ['Pés', 'Feet', 'Pies', 'Füße'],
  pele: ['Pele', 'Skin', 'Piel', 'Haut'],
};

/** A label in the game's language (the key itself when there's none). */
export const l = (key: string) => CUSTOMIZE_LABELS[key]?.[LANGS.indexOf(getLang())] ?? key;
