// Spanish (neutral Latin American, es-419, "tú"): the game's texts. The keys, pt-BR and en are in client/ui/strings.ts;
// the typecheck flags a key missing here. Translated adapting the humor the way the English does (PF-30).
import type { DeathLines, StringKey } from './strings';

export const es: Record<StringKey, string> = {
  title: 'OFFENSIVE COMBAT',
  subtitle: 'Prototipo de disparos · Fase 1',
  play: 'JUGAR',
  resume: 'VOLVER AL JUEGO',
  aimOnNextKey: 'La mira vuelve con tu próxima tecla o clic',
  loading: 'Cargando',
  settings: 'Configuración',
  sensitivity: 'Sensibilidad',
  adsSensitivity: 'Sensibilidad al apuntar',
  fov: 'Campo de visión',
  volume: 'Volumen',
  invertY: 'Invertir eje Y',
  health: 'VIDA',
  reload: 'RECARGA',
  noAmmo: 'SIN MUNICIÓN',
  reloading: 'RECARGANDO…',
  points: 'Puntos',
  kills: 'Bajas',
  accuracy: 'Precisión',
  you: 'Tú',
  kill: 'Baja',
  headshot: 'Tiro a la cabeza',
  longShot: 'Larga distancia',
  respawnIn: 'Reapareciendo en {s}…',
  debugHint: 'F3 depuración · F4 hitboxes y colisionadores (personajes → personajes + assets → ninguno)',
  debugViewChars: 'F4: hitboxes de los personajes',
  debugViewAll: 'F4: personajes + colisionadores del mapa',
  debugViewOff: 'F4: depuración visual desactivada',
  keyMove: 'Moverse',
  keyJump: 'Saltar',
  keyCrouch: 'Agacharse (corriendo: deslizarse)',
  keySprint: 'Correr',
  keyFire: 'Disparar',
  keyAds: 'Apuntar',
  keyReload: 'Recargar',
  keyPause: 'Menú',
  mouseLeft: 'Botón izq.',
  mouseRight: 'Botón der.',
  keyMelee: 'Cuchillada',
  keyTaunt: 'Humillar (cerca del cuerpo)',
  keyDonate: 'Donar el arma del ataúd (zombis)',
  keyRefuse: 'Rechazar el arma del ataúd (zombis)',
  keyGrenade: 'Granada (mantén para cocinarla)',
  keyForward: 'Avanzar',
  keyBack: 'Retroceder',
  keyLeft: 'Moverse a la izquierda',
  keyRight: 'Moverse a la derecha',
  keyScoreboard: 'Marcador',
  keyPrimary: 'Principal',
  keyAlternate: 'Alternativa',
  keyPress: 'Presiona una tecla… (Esc cancela)',
  keyClear: 'Quitar la tecla',
  keyUnbound: 'Sin tecla',
  keyMoved: '{key} estaba en "{action}", que se quedó sin tecla {slot}.',
  keyNoCtrl: 'No se puede usar Ctrl: Ctrl+W cierra la pestaña del navegador.',
  keyFixed: '{key} está reservada para la depuración.',
  keyWheelHold: 'La rueda del mouse no se puede mantener presionada: úsala para saltar, disparar, recargar, dar cuchilladas, lanzar granadas, humillar o cambiar de arma.',
  keysReset: 'Restaurar teclas predeterminadas',
  grenadeName: 'Granada',
  knife: 'Cuchillada',
  knifeName: 'Cuchillo',
  mineLimit: 'Máximo de {n} minas en el mapa',
  cherryTaken: '🍒 Cereza del Dragón: +{n} de vida máxima por {s} s',
  cherryOver: 'Se acabó el efecto de la cereza',
  koiXp: '🐟 Pez abatido: +{n} XP',
  goldenKoiXp: '✨ Carpa koi dorada: +{n} XP',
  goldenKoi: '✨ ¡Carpa koi dorada! Puntería afinada por {s} s',
  goldenKoiOver: 'Se acabó la puntería afinada de la carpa',
  galleryAim: '🎯 ¡Todos los blancos! Puntería afinada por {s} s',
  humanityTaken: '🕯️ Humanidad obtenida: +{n} de vida máxima hasta que mueras',
  biscuitTaken: '🦴 ¡Galleta Scooby! Vida llena. ¡Scooby-Dooby-Doo!',
  promptPotion: 'Beber poción',
  potion_pato: '🦆 ¡Granadas de pato hasta que mueras!',
  potion_veloz: '💨 Poción de la prisa: más rápido por {s} s',
  potion_lerdo: '🐌 Poción de la pachorra: más lento por {s} s',
  potion_critico: '💀 Poción del crítico: cada disparo es crítico por {s} s',
  potion_bebado: '🍺 Poción del borracho: puntería torcida por {s} s',
  potionOver: 'Se acabó el efecto de la poción',
  galleryAimOver: 'Se acabó la puntería afinada del tiro al blanco',
  buffKoi: 'Puntería de la carpa',
  buffGallery: 'Puntería afinada',
  buffCherry: 'Vida extra',
  buffHumanity: 'Humanidad',
  buffDuck: 'Granadas de pato',
  buffVeloz: 'Prisa',
  buffLerdo: 'Pachorra',
  buffCritico: 'Tiro crítico',
  buffBebado: 'Borracho',
  buffUntilDeath: 'hasta morir',
  buffUntilMatchEnd: 'hasta el fin de la partida',
  arsenal: 'Arsenal',
  level: 'Nivel',
  locked: 'Bloqueado',
  xpToNext: 'Faltan {xp} puntos para el nivel {level}',
  maxLevel: '¡Nivel máximo! {xp} puntos',
  unlockShort: 'faltan {xp} pts',
  // Weapons and their upgrades (ids from shared/data/progression.json): arma_<weapon>, upg_<weapon>_<id>, and
  // the description of each (armaDesc_, upgDesc_). client/tests/arsenalText.test.ts checks none is missing.
  arma_rifle: 'Rifle Estándar',
  armaDesc_rifle: 'El de siempre. Miras de hierro y mucha fe. Bueno de cerca, bueno de lejos, genial en ninguna parte.',
  arma_pistola: 'Pistola del Portero',
  armaDesc_pistola: 'Doce balas y toda la autoridad del condominio. Semiautomática: un clic, un disparo. Se desenfunda rápido.',
  arma_smg: 'Subfusil Licuadora',
  armaDesc_smg: 'Hace brrrrr y lo licúa todo. Escupe plomo de cerca y llora de lejos. Más ligero: corres más rápido con él.',
  arma_grampeador: 'Engrapadora de RR. HH.',
  armaDesc_grampeador: 'Clac-clac-clac: tres grapas por clic, directo al memorándum. Buena de cerca y a media distancia, pero entre ráfaga y ráfaga se le atasca el papel.',
  arma_revolver: 'Revólver del Sheriff del Baile Vaquero',
  armaDesc_revolver: 'De la boda del baile vaquero: con él, el sheriff obliga al novio a decir que sí. Seis balas que pegan fuerte, pero el tambor gira lento y recargar es toda una telenovela.',
  arma_furadeira: 'Taladro Dominguero del Vecino',
  armaDesc_furadeira: 'Domingo, ocho de la mañana: rrrrrrrr. Perfora todo en un parpadeo y despierta a toda la cuadra, pero la broca dispara para todos lados y no llega ni al portón.',
  arma_garrucha: 'Doble Cañón del Cangaceiro',
  armaDesc_garrucha: 'Dos cañones, sombrero de cuero y cero paciencia. A quemarropa lo resuelve de un tiro; de lejos es una lloviznita de perdigones que solo hace cosquillas. Dos tiros y se abre para recargar.',
  arma_pistolao: 'Pistolón del Gymbro',
  armaDesc_pistolao: 'Hizo brazo toda la semana solo para esto. Pega como un rifle y un tiro a la cabeza lo resuelve, pero la patada te manda la mira al techo, pesa y las siete balas se acaban rápido.',
  arma_faca: 'Cuchillo de Cocina',
  armaDesc_faca: 'Lo sacaste de la cocina y nunca lo devolviste. Un golpe, una baja.',
  arma_granada: 'Granada de Fragmentación',
  armaDesc_granada: 'Explota al primer contacto. Si la cocinas de más, te explota en la mano.',
  // The old rifles and knives (they use the rifle's and the knife's points and upgrades).
  arma_rifleFita: 'Rifle Parchado con Cinta',
  armaDesc_rifleFita: 'Mitad cinta plateada, mitad coraje. Recarga rápido, pero la cinta está floja y patea más.',
  arma_rifleTia: 'Rifle de la Tía del WhatsApp',
  armaDesc_rifleTia: 'Rosadito, con calcomanía de florecita. ¡Buenos días! Dispara más rápido y apunta en un instante, pero cada bala pega un poco menos.',
  arma_rifleNatal: 'Rifle de Luces Navideñas',
  armaDesc_rifleNatal: 'Envuelto en lucecitas. La patada es mucho más mansa, pero las lucecitas no tienen prisa: dispara más lento.',
  arma_rifleChama: 'Rifle Tuneado con Llamas',
  armaDesc_rifleChama: 'Las calcomanías de llamas dan +10 de velocidad, todo el mundo lo sabe. Dispara más rápido y corres más, pero las balas se dispersan.',
  arma_rifleVovo: 'Rifle del Abuelo',
  armaDesc_rifleVovo: 'Madera barnizada, de cuando los rifles duraban toda la vida. Pega fuerte, pero es lento para disparar y para apuntar.',
  arma_rifleOuro: 'Rifle Dorado de Lujo',
  armaDesc_rifleOuro: 'Todo de oro y cargador de 40. No combina con nada, y eso es lo que importa. Pesado: caminas y recargas más lento.',
  arma_colher: 'Cuchara de Palo de la Abuela',
  armaDesc_colher: 'Quien ya se ganó un cucharazo lo sabe: es letal. Un poco más de alcance, golpes un poco más lentos.',
  arma_frango: 'Pollo de Goma',
  armaDesc_frango: 'Lo aprietas y grita. Embestida mucho más larga, pero todos oyen el grito desde lejos.',
  arma_baguete: 'Baguette de Ayer',
  armaDesc_baguete: 'Dura desde ayer. Crujiente por fuera, mortal por dentro. Más alcance, golpes más lentos.',
  arma_peixe: 'Pescado Congelado',
  armaDesc_peixe: 'Directo del congelador. Embestida larga, pero la cachetada helada tarda en salir.',
  arma_macarrao: 'Fideo de Piscina',
  armaDesc_macarrao: '60 centímetros de espuma. Parece inofensivo. No lo es. Llega lejos, pero es lento y la embestida es corta.',
  arma_sabre: 'Sable de Luz Pirata',
  armaDesc_sabre: 'Comprado en un puesto callejero. El mayor alcance de todos y hace vuuum (todos lo oyen). Las pilas son de las baratas: más tiempo entre golpes.',
  // A progression's short name ("faltam 600 pts de faca").
  prog_rifle: 'rifle',
  prog_pistola: 'pistola',
  prog_smg: 'subfusil',
  prog_faca: 'cuchillo',
  prog_granada: 'granada',
  upg_rifle_pontoVermelho: 'Punto Rojo del Mercado de Pulgas',
  upgDesc_rifle_pontoVermelho: 'Comprado en el mercado de pulgas, pero el puntito sí prende. Mira más firme y un poco de zoom.',
  upg_rifle_empunhadura: 'Empuñadura de Palo de Escoba',
  upgDesc_rifle_empunhadura: 'Un palo de escoba bien amarrado debajo del cañón. Controla la patada y cierra la dispersión.',
  upg_rifle_luneta: 'Mira Telescópica del Abuelo (3x)',
  upgDesc_rifle_luneta: 'La mira de latón que el abuelo usaba para espiar al vecino. Zoom 3x y precisión de lejos, pero apuntar tarda y el arma pesa. Reemplaza al punto rojo.',
  upg_rifle_pente: 'Cargador Doble con Cinta Plateada',
  upgDesc_rifle_pente: 'Dos cargadores pegados con cinta: diez balas más y recarga más rápida.',
  upg_rifle_silenciador: 'Silenciador de Botella de Refresco',
  upgDesc_rifle_silenciador: 'Una botella de 2 litros en el cañón. Solo quien está cerca oye el disparo y nadie ve el trazador. A cambio, menos daño y alcance.',
  upg_rifle_holoLupa: 'Holo con Lupa (1.5x)',
  upgDesc_rifle_holoLupa: 'La holográfica de carita feliz con una lupa abatible detrás. Zoom de 1.5x y mira más firme; tarda un poquito más en apuntar.',
  upg_rifle_luneta2x: 'Mira Telescópica 2x',
  upgDesc_rifle_luneta2x: 'Mira telescópica corta de latón. Zoom 2x y más alcance; apunta más lento y pesa un poco.',
  upg_rifle_luneta4x: 'Mira Telescópica 4x',
  upgDesc_rifle_luneta4x: 'La mira telescópica larga de la vitrina. Zoom 4x y mucho alcance; apuntar tarda y el rifle se pone pesado.',
  upg_pistola_gatilho: 'Gatillo de Arcade',
  upgDesc_pistola_gatilho: 'Arrancado de una máquina de arcade: puedes hacer clic mucho más rápido.',
  upg_pistola_pontoVermelho: 'Mini Punto Rojo',
  upgDesc_pistola_pontoVermelho: 'Chiquitito, pero honesto. Mucho más precisa al apuntar.',
  upg_pistola_coldre: 'Funda de Velcro',
  upgDesc_pistola_coldre: 'Sale de la funda en la mitad del tiempo, y el cargador también se cambia más rápido.',
  upg_pistola_batata: 'Silenciador de Papa',
  upgDesc_pistola_batata: 'Una papa clavada en el cañón. Funciona en las películas, funciona aquí: disparo amortiguado, sin trazador y menos patada. Pero un poco menos de daño.',
  upg_smg_motor: 'Motor Turbo de Licuadora',
  upgDesc_smg_motor: 'Velocidad 5 de la licuadora: más disparos por segundo.',
  upg_smg_holo: 'Mira Holográfica de la Tía del WhatsApp',
  upgDesc_smg_holo: 'Una carita feliz flotando en la mira. ¡Buenos días! Más preciso al apuntar y disparando desde la cadera.',
  upg_smg_tambor: 'Cargador de Tambor Palomitero',
  upgDesc_smg_tambor: '18 balas más en el tambor de una máquina de palomitas. A cambio, recargar y cambiar de arma tardan más y caminas un poco más lento.',
  upg_smg_coronha: 'Culata de Manguera',
  upgDesc_smg_coronha: 'Una manguera de jardín enrollada contra el hombro. Menos retroceso y menos dispersión.',
  upg_faca_afiador: 'Afilador Ambulante',
  upgDesc_faca_afiador: 'El afilador que pasa tocando la flautita lo afiló gratis. Golpes más seguidos y un poco más de alcance.',
  upg_faca_tenis: 'Tenis de Resortes',
  upgDesc_faca_tenis: 'Tenis con resortes en la suela: la embestida llega más lejos y más rápido.',
  upg_faca_maoLeve: 'Mano Ligera',
  upgDesc_faca_maoLeve: 'Golpe rápido, sin rodeos: termina antes y el arma vuelve lista para disparar más pronto.',
  // Each knife's passive (shared/data/weapons/<faca>.json "passiva"), in the Arsenal and when it kicks in.
  passiva_discreta: 'Discreta',
  passivaDesc_discreta: 'El golpe solo se oye de cerca.',
  passiva_coloDeVo: 'Mimos de Abuela',
  passivaDesc_coloDeVo: 'Cada baja con ella te devuelve {vida} de vida.',
  passiva_fugaEscandalosa: 'Huida Escandalosa',
  passivaDesc_fugaEscandalosa: 'Después de una baja con él, corres {pct}% más rápido por {s} s.',
  passiva_lanche: 'Hora de la Merienda',
  passivaDesc_lanche: 'Cada baja con ella llena el cargador del arma que tienes en la mano.',
  passiva_tapaGelado: 'Cachetada Helada',
  passivaDesc_tapaGelado: 'La cuchillada por la espalda vale +{pts} pts en vez de +{base}.',
  passiva_boia: 'Flotador',
  passivaDesc_boia: 'Con él equipado, no recibes daño por caída.',
  passiva_vuuum: 'Vuuum',
  passivaDesc_vuuum: 'El golpe le da a todos los que estén a tu alcance y enfrente, no solo a uno.',
  knifePassive: 'Pasiva: {name}',
  knifePassiveWhere: 'Funciona en combate a muerte, en la práctica y contra bots.',
  passiveFx_coloDeVo: '🥄 Mimos de abuela: +{vida} de vida',
  passiveFx_fugaEscandalosa: '🐔 ¡Huida escandalosa!',
  passiveFx_lanche: '🥖 Hora de la merienda: cargador lleno',
  upg_granada_mina: 'Mina Terrestre',
  upgDesc_granada_mina: 'G planta una mina en el suelo en vez de lanzarla. Se arma en 1 s y explota cuando un enemigo pisa cerca. Desaparece cuando reapareces.',
  upg_granada_dupla: 'Dosis Doble',
  upgDesc_granada_dupla: 'Una G, dos granadas: lanza una y enseguida la otra, gastando una sola carga.',
  upg_granada_cinto: 'Cinturón de Granadas de la Tía',
  upgDesc_granada_cinto: 'Una granada más por vida. La tía siempre carga una de repuesto.',
  upg_granada_polvora: 'Pólvora de la Fiesta del Pueblo',
  upgDesc_granada_polvora: 'Pólvora de los cohetes de la fiesta patronal: la explosión llega un 20% más lejos.',
  // What an upgrade changes, as chips in the Arsenal ({v}: "+15%", "+10", "2,6").
  fx_dano: 'Daño {v}',
  fx_alcance: 'Alcance {v}',
  fx_cadencia: 'Cadencia {v}',
  fx_pente: 'Cargador {v}',
  fx_recarga: 'Recarga {v}',
  fx_dispersao: 'Dispersión {v}',
  fx_mirando: 'Dispersión al apuntar {v}',
  fx_recuo: 'Retroceso {v}',
  fx_adsTempo: 'Tiempo para apuntar {v}',
  fx_zoom: 'Zoom {v}x',
  fx_movimento: 'Movilidad {v}',
  fx_troca: 'Tiempo de cambio {v}',
  fx_silenciador: 'Disparo amortiguado',
  fx_golpe: 'Alcance del golpe {v} m',
  fx_investida: 'Embestida {v} m',
  fx_intervalo: 'Intervalo entre golpes {v}',
  fx_impulso: 'Velocidad de la embestida {v}',
  fx_duracao: 'Duración del golpe {v}',
  fx_granadas: 'Granadas {v}',
  fx_recargaGranada: 'Recarga de granada {v}',
  fx_raio: 'Radio de la explosión {v}',
  fx_lancamento: 'Lanzamiento {v}',
  fx_tipo_mina: 'G planta una mina',
  fx_tipo_dupla: 'G lanza dos',
  // The Arsenal tree (client/ui/arsenal.ts): one row per slot.
  treeRow_primaria: 'Principal',
  treeRow_secundaria: 'Secundaria',
  treeRow_faca: 'Cuchillo',
  treeRow_granada: 'Granada',
  treeEquip: 'Equipar',
  treeEquipped: 'Equipada',
  treeWeaponLocked: 'faltan {xp} pts de {prog}',
  treeWeaponLockedLong: 'Bloqueada: se desbloquea con {total} puntos de {prog}. Faltan {xp}.',
  weaponUnlocked: '{weapon} desbloqueada: equípala en el Arsenal',
  arsenalSaveFailed: 'No se pudo guardar el Arsenal',
  upgradeOn: 'Activada',
  upgradeOff: 'Desactivada',
  upgradeReplacedBy: 'Reemplazada por {upgrade}',
  upgradeOptional: 'Opcional: tiene sus contras',
  upgradeUnlocked: '¡{weapon} nivel {level}: {upgrade}!',
  upgradeTurnOn: 'Actívala en el Arsenal',
  statDamage: 'Daño',
  statRate: 'Cadencia',
  statAccuracy: 'Precisión',
  statRange: 'Alcance',
  statMobility: 'Movilidad',
  statMag: 'Cargador {mag} / reserva {reserve}',
  statSwingReach: 'Alcance del golpe',
  statLunge: 'Embestida',
  statSwingSpeed: 'Rapidez',
  statStealth: 'Sigilo',
  // The Arsenal canvas of the home (client/ui/arsenalCanvas.ts): a frame per slot, the panel, the zoom bar.
  arsenalCanvasHint: 'Arrastra para moverte y usa la rueda del mouse para hacer zoom. Haz clic en un arma para ver sus detalles.',
  arsenalCanvasHintTouch: 'Arrastra para moverte y usa dos dedos para hacer zoom. Toca un arma para ver sus detalles.',
  cvLegendLocked: 'Bloqueada',
  cvRow_primaria: 'Principal',
  cvRow_secundaria: 'Secundaria',
  cvRow_faca: 'Cuerpo a cuerpo',
  cvRow_granada: 'Lanzamiento',
  cvSlot_primaria: 'Primaria',
  cvSlot_secundaria: 'Secundaria',
  cvSlot_faca: 'Cuerpo a cuerpo',
  cvSlot_granada: 'Lanzamiento',
  cvFrameEquipped: 'Equipada: {weapon}',
  cvUpgRow_mira: 'Miras',
  cvUpgRow_modo: 'Modo',
  cvUpgRow_resto: 'Mejoras',
  cvAlwaysEquipped: 'Siempre equipada',
  cvEquipSecondary: 'Llevar como secundaria',
  cvYourSecondary: 'Tu secundaria',
  cvProgress: 'Progreso',
  cvUpgrades: 'Mejoras',
  cvOnCount: '{n} de {total} activadas',
  cvOptional: 'Opcional',
  cvWeaponLocked: 'Arma bloqueada',
  cvUnlockWeaponFirst: 'Desbloquea el arma primero',
  cvToggleOn: 'Activada · toca para desactivar',
  cvToggleOff: 'Desactivada · toca para activar',
  cvPickUpgrade: 'Haz clic en una mejora del árbol para ver qué cambia. El botón de cada una la activa o desactiva directamente en el lienzo.',
  cvFitAll: 'Ver todo',
  cvFitTitle: 'Ver todo (0)',
  cvZoomIn: 'Acercar (+)',
  cvZoomOut: 'Alejar (−)',
  cvClose: 'Cerrar (Esc)',
  keyWeapon1: 'Arma primaria',
  keyWeapon2: 'Arma secundaria',
  keySwapWeapon: 'Cambiar de arma',
  touchSwap: 'Cambiar de arma',
  dogBite: 'Mordida',
  backstab: 'Por la espalda',
  groin: 'Al pajarito',
  groinBanner: '¡AL PAJARITO!',
  humiliation: 'Humillación',
  humiliatedBanner: '¡HUMILLADO!',
  danceName: 'Bailecito de la Victoria',
  promptTaunt: 'Humillar a {name}',
  dancing: 'Humillando a {name}…',
  quality: 'Calidad gráfica',
  qualityAuto: 'Automática',
  objectDetail: 'Detalle de los objetos',
  detailNormal: 'Normal',
  detailLight: 'Ligero',
  spatialAudio: 'Sonido',
  spatialAuto: 'Automático',
  spatialHeadphones: 'Auriculares (3D)',
  spatialSpeakers: 'Altavoces (estéreo)',
  qualityLow: 'Baja',
  qualityMedium: 'Media',
  qualityHigh: 'Alta',
  touchFire: 'Disparar',
  touchAds: 'Apuntar',
  touchJump: 'Saltar',
  touchCrouch: 'Agacharse',
  touchReload: 'Recargar',
  touchMelee: 'Cuchillo',
  touchGrenade: 'Granada',
  touchPause: 'Pausa',
  touchBoard: 'Marcador',
  touchFullscreen: 'Pantalla completa',
  touchSensitivity: 'Sensibilidad táctil',
  touchScale: 'Tamaño de los botones',
  touchOpacity: 'Opacidad de los botones',
  aimAssist: 'Asistencia de apuntado',
  adsHold: 'Mantener para apuntar (desactivado: tocar alterna)',
  padSensitivity: 'Sensibilidad del control',
  padLook: 'Mirar',
  padLeftStick: 'Analógico izquierdo',
  padRightStick: 'Analógico derecho',
  fullscreenOnPlay: 'Pantalla completa al jugar',
  editLayout: 'Acomodar botones',
  editLayoutDone: 'Listo',
  editLayoutReset: 'Posiciones predeterminadas',
  editLayoutHint: 'Arrastra los botones adonde prefieras.',
  rotatePhone: 'Gira el celular para jugar',
  fullscreen: 'Pantalla completa',
  iosFullscreen: 'Para pantalla completa en iPhone: toca Compartir y luego "Agregar a pantalla de inicio".',
  tapHint: 'Toca',
  touchControlsHelp: 'Arrastra a la izquierda para moverte (hasta el borde para correr) · arrastra a la derecha para mirar · botones para disparar, apuntar, saltar, agacharte, recargar, cuchillo y granada (mantén para prepararla).',
  yourName: 'Tu nombre',
  sexLabel: 'Sexo',
  sexMale: '♂ Masculino',
  sexFemale: '♀ Femenino',
  playOnline: 'JUGAR EN LÍNEA',
  playOffline: 'Campo de tiro (muñecos quietos)',
  playBots: 'CONTRA BOTS',
  botSkill: 'Dificultad',
  mapLabel: 'Mapa',
  botCount: 'Bots',
  skillEasy: 'Fácil',
  skillNormal: 'Normal',
  skillHard: 'Difícil',
  botsSubtitle: 'Contra {n} bots · {mode}',
  sessions: 'Sesiones',
  createSession: 'CREAR',
  sessionNamePlaceholder: 'Nombre de la nueva sesión',
  back: 'Volver',
  noSessions: 'No hay sesiones abiertas. JUGAR EN LÍNEA abre la primera.',
  join: 'UNIRSE',
  full: 'LLENA',
  joining: 'Entrando…',
  connecting: 'Conectando al servidor…',
  connectedAs: 'Conectado como {name}.',
  disconnected: 'Se perdió la conexión con el servidor.',
  serverOffline: 'El servidor está caído. Ejecuta "bun run server" (o juega la práctica sin conexión).',
  needName: 'Primero elige un nombre.',
  exitToHome: 'Volver al inicio',
  backToEditor: 'Volver al editor (Stop)',
  scoreboard: 'Marcador',
  player: 'Jugador',
  deaths: 'Muertes',
  humiliationsShort: 'Humill.',
  killedBy: '{name} te eliminó',
  killedByWith: '{name} te eliminó con {weapon}',
  playerJoined: '{name} entró',
  playerLeft: '{name} salió',
  keyChat: 'Chat de la sala',
  chatPlaceholder: 'Mensaje para la sala…',
  chatSend: 'Enviar',
  chatClose: 'Cerrar el chat',
  chatHint: 'Enter envía · Esc cierra',
  chatMuted: 'La moderación silenció tu chat.',
  chatSlow: '¡Calma! Espera un poco antes de mandar otro.',
  touchChat: 'Chat',
  lostConnection: 'Sin conexión con el servidor',
  accountGuest: 'Sin cuenta: la práctica y los bots están disponibles. Para jugar en línea, inicia sesión o crea una cuenta.',
  signIn: 'INICIAR SESIÓN',
  signUp: 'CREAR CUENTA',
  profile: 'PERFIL',
  signOut: 'Salir de la cuenta',
  email: 'Correo electrónico',
  password: 'Contraseña',
  gameName: 'Nombre en el juego',
  signInTitle: 'Iniciar sesión',
  signUpTitle: 'Crear cuenta',
  forgotTitle: 'Olvidé mi contraseña',
  resetTitle: 'Nueva contraseña',
  chooseNameTitle: 'Elige tu nombre en el juego',
  withDiscord: 'Iniciar sesión con Discord',
  forgotLink: 'Olvidé mi contraseña',
  haveAccount: 'Ya tengo cuenta',
  noAccount: 'Crear una cuenta',
  send: 'ENVIAR',
  save: 'GUARDAR',
  resetSent: 'Si ese correo tiene una cuenta, te enviamos un enlace válido por 24 horas.',
  resetDone: 'Contraseña cambiada. Inicia sesión con la nueva.',
  needAccount: 'Inicia sesión para jugar en línea.',
  // Home: signed-in tabs
  tabPlay: 'JUGAR',
  tabArsenal: 'ARSENAL',
  tabAlbum: 'ÁLBUM',
  tabProfile: 'PERFIL',
  tabSettings: 'CONFIGURACIÓN',
  customizeShort: 'PERSONALIZAR',
  equippedLine: '{icons} equipados',
  profileLine: '{kills} bajas · {matches} partidas',
  modeTitle: 'Modo',
  modeOnline: 'En línea',
  modeBots: 'Contra bots',
  modeRange: 'Campo de tiro',
  // Game modes (shared/modes.ts): gameMode_<id> and gameModeDesc_<id>.
  gameModeTitle: 'Tipo de partida',
  'gameMode_mata-mata': 'Combate a muerte',
  'gameModeDesc_mata-mata': 'Todos contra todos con tu Arsenal, elegido antes de entrar.',
  'gameMode_corrida-armada': 'Carrera armada',
  'gameModeDesc_corrida-armada': 'Todos suben la misma escalera de armas. Gana la baja con el Sable de Luz.',
  gameMode_zumbi: 'Zombis',
  gameModeDesc_zumbi: 'En equipo contra 12 oleadas de zombis y 3 jefes, con ataúd y barricadas.',
  // Zumbi (shared/zombies.ts): zombies (ztype_<kind>), bosses (zboss_<id>), the coffin's items (zitem_<id>),
  // rarities (rar_<id>), the HUD, the coffin, revives and the end-of-match summary.
  ztype_comum: 'Zombi',
  ztype_corredor: 'Maratonista',
  ztype_inchado: 'Tío Parrillero',
  ztype_brutamontes: 'Guardia de la Disco',
  ztype_cuspidor: 'Tía Chismosa',
  zboss_coveiro: 'El Sepulturero',
  zboss_noiva: 'La Novia',
  zboss_prefeito: 'El Alcalde',
  zbossIntro_coveiro: '¡EL SEPULTURERO SALIÓ DE LA TUMBA!',
  zbossIntro_noiva: 'LA NOVIA QUEDÓ PLANTADA EN EL ALTAR…',
  zbossIntro_prefeito: '¡EL ALCALDE QUIERE TU VOTO!',
  zitem_riflePadrao: 'Rifle Estándar',
  zitem_pistolaInicial: 'Pistola del Portero',
  zitem_rifleMira: 'Rifle con Punto Rojo',
  zitem_rifleSilencioso: 'Rifle Silencioso',
  zitem_pistola: 'Pistola del Portero',
  zitem_pistolaBatata: 'Pistola de la Papa',
  zitem_liquidificador: 'Licuadora',
  zitem_grampeador: 'Engrapadora de RR. HH.',
  zitem_revolver: 'Revólver del Sheriff del Baile Vaquero',
  zitem_furadeira: 'Taladro Dominguero del Vecino',
  zitem_garrucha: 'Doble Cañón del Cangaceiro',
  zitem_pistolao: 'Pistolón del Gymbro',
  zitem_rifleFirme: 'Rifle Firme',
  zitem_rifleVovo: 'Rifle del Abuelo',
  zitem_pistolaLigeira: 'Pistola Ligera',
  zitem_liquidificadorMotor: 'Licuadora con Motor',
  zitem_rifleRemendado: 'Rifle Parchado',
  zitem_liquidificadorTurbo: 'Licuadora Turbo',
  zitem_liquidificadorPipoca: 'Licuadora Palomitera',
  zitem_rifleCompleto: 'Rifle Completo',
  zitem_liquidificadorSupremo: 'Licuadora Suprema',
  zitem_sabre: 'Sable de Luz Pirata',
  rar_inicial: 'Inicial',
  rar_comum: 'Común',
  rar_raro: 'Rara',
  rar_epico: 'Épica',
  rar_lendario: 'Legendaria',
  zWave: 'OLEADA {n}/{total}',
  zLeft: '{n} zombis',
  zLeftOne: '1 zombi',
  zCountdown: 'AHÍ VIENE LA HORDA',
  zCountdownSub: 'en {s}s · ¡encuentra el ataúd!',
  zBreak: 'DESCANSO',
  zBreakSub: 'próxima oleada en {s}s',
  zWaiting: 'Esperando jugadores',
  zOver: 'FIN DE LA PARTIDA',
  zWaveBanner: 'OLEADA {n}',
  zLastWave: '¡ÚLTIMA OLEADA!',
  zBreakBanner: '¡Oleada {n} superada! Munición y granadas al máximo',
  zBossDown: '¡{boss} CAYÓ!',
  zAssist: 'Asistencia',
  zRevive: 'Reanimación',
  zWaveBonus: 'Oleada superada',
  zBossReward: 'Jefe derrotado',
  zBlast: 'Explosión',
  zBoxBuy: 'Ataúd Misterioso: arma aleatoria por ${cost}',
  zTotemBuy: 'Tótem: enciende la Vigilia Sin Tregua por ${cost} (sin descansos hasta el final, +20% de dinero y +10% de XP)',
  zTotemPoor: 'Tótem: Vigilia Sin Tregua por ${cost} (tienes ${money})',
  zTotemLit: 'La Vigilia Sin Tregua está encendida: sin descansos hasta el fin de la partida',
  zTotemOn: '¡{name} encendió la Vigilia Sin Tregua! Sin descansos hasta el final',
  zBoxPoor: 'Ataúd Misterioso: ${cost} (tienes ${money})',
  zBoxSpinning: 'Girando…',
  zBoxTake: 'Tomar {item} ({rarity})',
  zBoxOther: '{name} está eligiendo el arma',
  zBoxDonateKey: '[{key}] donar',
  zBoxRefuseKey: '[{key}] rechazar',
  zBoxTakeDonated: '{take} · donada por {name}',
  zBoxYouDonated: 'Donaste {item}: cualquier otro puede tomarla',
  zBoxDonatedNotice: '{name} dejó {item} ({rarity}) en el ataúd: ¡el que quiera, que la tome!',
  zBoxGot: 'Obtuviste: {item} ({rarity})',
  zBoxTakeDamaged: 'Tomar {item} ({rarity}) · DAÑADA: {flaw}',
  zBoxGotDamaged: 'Obtuviste: {item} ({rarity}) · DAÑADA',
  zBoxDamagedOffer: 'Salió DAÑADA: {flaw}',
  zDamaged: 'Dañada',
  zFlaw_municao: 'menos munición',
  zFlaw_dano: 'menos daño',
  zFlaw_ambos: 'menos munición y daño',
  zFlawAmmo: '−{p}% de cargador y −{r}% de reserva',
  zFlawDamage: '−{d}% de daño',
  zgap_portao: 'Portón Principal',
  zgap_oeste: 'Brecha Oeste',
  zgap_leste: 'Brecha Este',
  zgap_noroeste: 'Brecha Noroeste',
  zgap_nordeste: 'Brecha Noreste',
  zBarBuild: 'Mantén presionado para levantar la barricada: {gap} (${cost})',
  zBarPoor: 'Barricada: ${cost} (tienes ${money})',
  zBarBuilding: 'Levantando la barricada…',
  zBarRepair: 'Mantén presionado para clavar tablas ({n}/{max})',
  zBarRepairing: 'Clavando tablas ({n}/{max})…',
  zBarBlocked: 'Paso ocupado: nadie puede quedarse en el hueco',
  zBarNail: 'Tabla clavada',
  zBarBuilt: '{name} levantó la barricada: {gap}',
  zBarBroken: '¡Derribaron la barricada: {gap}!',
  zRevivePrompt: 'Mantén presionado para reanimar a {name}',
  zReviving: 'Reanimando a {name}…',
  zBeingRevived: '¡{name} te está reanimando!',
  zDownTitle: '¡CAÍDO!',
  zDownSub: 'Un amigo puede reanimarte · te desangras en {s}s',
  zTeammateDown: '¡{name} cayó! Ve a reanimar',
  zRevived: '{name} reanimó a {who}',
  zBledOut: '{name} se desangró',
  zDeadWait: 'Vuelves en el descanso (sin las armas del ataúd)',
  zJoinWaitTitle: 'Oleada en curso',
  zJoinWait: 'Entras cuando termine esta oleada',
  zSpectating: 'OBSERVANDO',
  zProfaneYou: '¡SACRILEGIO! Toda la horda va tras de ti',
  zProfaneHint: 'Nadie se sube al altar: por {s} s, todos los zombis te persiguen',
  zProfaned: '{name} profanó el altar y es el blanco de la horda por {s} s',
  zCrowsYou: '¡CUERVOS! Bájate del árbol',
  zCrowsHint: 'Picotean mientras estés en el árbol y {s} s más',
  buffProfaned: 'Profanado',
  buffCrows: 'Cuervos',
  buffCrowsUntil: 'en el árbol y {s} s más',
  zSpecHealth: '{hp} de vida',
  zSpecDown: 'Caído: ¡necesita ayuda!',
  zSpecKeys: '[{prev}] anterior · [{next}] siguiente',
  zJump: '¡SALTA LA ONDA!',
  zWon: '¡SOBREVIVIERON A LA HORDA!',
  zLost: 'LA HORDA GANÓ',
  zSumSub: 'Oleada {wave} de {total} · {time}',
  zSumNext: 'Nueva partida en {s}s…',
  zColKills: 'Bajas',
  zColHead: 'A la cabeza',
  zColEarned: 'Dinero',
  zColDowns: 'Cayó',
  zColRevives: 'Reanimó',
  zColXp: 'XP',
  zColMoney: 'Dinero',
  zArsenalTitle: 'Ataúd Misterioso',
  zArsenalCarry: 'Llevas',
  zSolo: 'ENFRENTAR A LA HORDA SOLO',
  zMapOnly: 'Solo en el Cementerio de la Capilla',
  buffChilled: 'Aterrado',
  buffVigil: 'Vigilia Sin Tregua',
  buffBleeding: 'Sangrando',
  zThorns: '¡Espinas! Quien se sube a la reja o al seto sangra.',
  zGhostsYou: '¡A la lápida no le gustó!',
  zGhostsHint: '👻 Fantasmas tras de ti por {s} s: un cuchillo o una granada los espantan',
  // Mata-mata: the loadout is locked once the match starts.
  upgradeNextMatch: 'Aplica desde la próxima partida',
  upgradeTurnOnNext: 'Actívala en el Arsenal antes de la próxima partida',
  // Corrida armada: the ladder (ids from shared/data/corrida_armada.json: ladder_<id>), HUD and rounds.
  ladderTitle: 'Escalera de la carrera armada',
  ladderHud: 'ARMA {n}/{total}',
  ladderStep: 'Escalón {n}',
  ladderFinalKills: 'baja final',
  ladderNext: '¡Siguiente arma: {weapon}!',
  ladderDown: '¡Acuchillado! Volviste a {weapon}',
  ladderLostKill: '¡Acuchillado! Perdiste una baja ({n}/{total})',
  ladderFinal: '¡SABLE DE LUZ! Una baja con él y ganas',
  ladder_rifleCompleto: 'Rifle Completo',
  ladder_smgTurbo: 'Licuadora Turbo',
  ladder_rifleLuneta: 'Rifle con Mira Telescópica',
  ladder_rifleSilenciado: 'Rifle con Silenciador',
  ladder_garrucha: 'Doble Cañón del Cangaceiro',
  ladder_grampeador: 'Engrapadora de RR. HH.',
  ladder_pistolaRapida: 'Pistola Ligera',
  ladder_pistolaBatata: 'Pistola de la Papa',
  ladder_sabre: 'Sable de Luz',
  roundWinner: '¡{name} ganó la carrera armada!',
  roundYouWon: '¡GANASTE LA CARRERA ARMADA!',
  roundNext: 'Nueva ronda en {s}…',
  roundStart: 'Nueva ronda: ¡todos de vuelta a la primera arma!',
  ladderShort: 'Arma',
  openSessions: 'Sesiones abiertas ({n})',
  moreSessions: 'VER MÁS ({n})',
  versusBots: 'CONTRA {n} BOTS',
  playAnyMap: 'Cualquier mapa',
  playAnyMapSub: 'Donde haya más gente',
  playPlayers: '{n} jugando',
  playNobody: 'nadie ahora',
  playAllMaps: 'Todos los mapas ›',
  playSessionsOn: 'Sesiones en {map} ({n})',
  noSessionsMap: 'Nadie en {map} ahora. JUGAR EN LÍNEA abre una sesión nueva.',
  playSessionsLoading: 'Buscando sesiones…',
  playSessionsOffline: 'Sin servidor ahora. Los bots y la práctica funcionan sin conexión.',
  playCreateToggle: '+ Crear sesión con nombre',
  playCreateShort: '+ CREAR',
  playCreateWhere: 'en {map} · {mode}',
  playCreatePickMap: 'Elige un mapa para crear una sesión con nombre.',
  playSessionsBtn: 'SESIONES ({n})',
  playBackMaps: '‹ MAPAS',
  modeOnlineShort: 'EN LÍNEA',
  modeBotsShort: 'BOTS',
  modeRangeShort: 'PRÁCTICA',
  'gameModeShort_corrida-armada': 'Carrera',
  playBotsTitle: 'Partida contra bots',
  playBotsN: '{n} bots',
  playHordeTitle: 'Solo contra la horda',
  playHordeInfo: '12 oleadas y 3 jefes. Caer es perder; el dinero de la partida no se queda.',
  playHordeShort: 'Solo · 12 oleadas',
  playRangeTitle: 'Campo de tiro',
  playRangeInfo: 'Muñecos quietos para probar tu puntería y las armas. Puedes cambiar el Arsenal en la pausa.',
  playRangeType: 'Práctica libre: sin tipo de partida y sin marcador.',
  playCtaOnline: '{mode} · {map} · {players}',
  playCtaNew: 'abre una sesión nueva',
  playCtaBots: '{mode} · {map} · {skill}',
  // Home: landing (signed out)
  navGame: 'El juego',
  navMaps: 'Mapas',
  navModes: 'Modos',
  navAccount: 'Crear cuenta',
  heroText: 'Tiroteos de barrio directo en el navegador. Puntería precisa, armas absurdas y un bailecito de victoria encima de quien cayó.',
  startPlaying: 'EMPEZAR A JUGAR',
  heroNote: 'Sin cuenta: la práctica y los bots están disponibles. PC, celular y control.',
  aboutTitle: 'Cómo es el juego',
  aboutSub: 'Serio en la mecánica. Nada serio en el tono.',
  pillarAimKicker: 'PUNTERÍA',
  pillarAimTitle: 'Disparos que respetan tu puntería',
  pillarAimDesc: 'Dispersión, retroceso y daño por zona del cuerpo. En la cabeza duele más. Al pajarito, duele de otra manera.',
  pillarTauntKicker: 'HUMILLACIÓN',
  pillarTauntTitle: 'Un bailecito vale 150',
  pillarTauntDesc: 'Una baja da 100 puntos. Bailar encima de quien cayó da 150. Provocar es parte del juego.',
  pillarArsenalKicker: 'ARSENAL',
  pillarArsenalTitle: 'Armas que evolucionan',
  pillarArsenalDesc: 'Cada baja hace evolucionar el arma que la logró y desbloquea armas nuevas: del cuchillo de cocina al sable de luz, del rifle estándar al Dorado de Lujo.',
  mapsTitle: 'Mapas',
  mapsSub: 'Tres vecindarios, cada uno con sus chistes y secretos.',
  mapRuaWhen: 'Día soleado',
  mapRuaGag: 'Suburbio con piscina vacía, camión de helados y flamencos. Cuidado con Amora: su mordida es letal.',
  mapJardimWhen: 'Noche de faroles',
  mapJardimGag: 'Jardín oriental iluminado con faroles. Hay carpas koi en los estanques y una cereza que da más vida por 30 s.',
  mapHalloweenWhen: 'Luna llena',
  mapHalloweenGag: 'Cementerio, mansión, parque de diversiones y alcantarilla. Una bruja reparte pociones de efecto aleatorio y una rata gigante vive allá abajo.',
  mapCemiterioWhen: 'Noche de neblina',
  mapCemiterioGag: 'El cementerio amurallado del modo zombi: la horda sale de las tumbas de afuera y solo entra por las cinco brechas del muro. Clava tablas en las brechas y elige por dónde llega.',
  modesTitle: 'Modos de juego',
  tagAccount: 'CON CUENTA',
  tagNoAccount: 'SIN CUENTA',
  landOnlineDesc: 'Combate a muerte (todos contra todos, con tu Arsenal), carrera armada o zombis (oleadas en equipo), con chat y marcador con nivel y ping.',
  landOnlineFacts: 'Hasta 10 jugadores|Salas por mapa|Suma al Arsenal',
  landBotsDesc: 'Las mismas reglas, contra bots con nombres como Capitão Lag y Recruta 404.',
  landBotsFacts: '3, 5, 7 o 9 bots|Fácil · Normal · Difícil|2 s de protección al aparecer',
  landRangeDesc: 'Muñecos de práctica en el mapa elegido, algunos patrullando. Para afinar la puntería sin que nadie te vea.',
  landRangeFacts: 'Sin rivales|Cualquier mapa|Reapareces en 3 s',
  accountWhy: 'Para jugar en línea, guardar la evolución de tus armas y armar tu personaje.',
  startTitle: 'Empezar a jugar',
  startGuest: 'Sin registro, ahora mismo. Entras como {name}.',
  passwordHint: 'De 8 a 128 caracteres.',
  nameHint: 'De 3 a 16 letras o números. Aparece como Nombre#1234.',
  levelShort: 'Nv {level}',
  accountLevelUp: '🏅 ¡Cuenta nivel {level}!',
  sessionEnded: 'Tu sesión se cerró (cierre de sesión, cambio de contraseña, eliminación o suspensión).',
  connectedElsewhere: 'Tu cuenta entró al juego desde otro lugar.',
  profileTitle: 'Perfil',
  statsTitle: 'Estadísticas',
  recentTitle: 'Últimas participaciones',
  noParticipations: 'Todavía no hay partidas en línea.',
  statKills: 'Bajas',
  statDeaths: 'Muertes',
  statHead: 'A la cabeza',
  statGroin: 'Al pajarito',
  statKnife: 'Cuchilladas',
  statBackstab: 'Por la espalda',
  statGrenade: 'Con granada',
  statHumiliations: 'Humillaciones',
  statTime: 'Tiempo jugado',
  statMatches: 'Participaciones',
  zstatsTitle: 'Modo zombi',
  zstatMatches: 'Partidas',
  zstatWins: 'Victorias',
  zstatBestWave: 'Mejor oleada',
  zstatWaves: 'Oleadas sobrevividas',
  zstatKills: 'Zombis abatidos',
  zstatDowns: 'Caídas',
  zstatRevives: 'Reanimaciones',
  zstatCoffin: 'Giros en el ataúd',
  albumTitle: 'Álbum de estampas',
  albumHint: 'Cada meta es un acabado más, hasta la Dorada. Solo cuenta lo que haces en línea.',
  albumCount: '{stuck} de {total} estampas · {finishes} de {finishesTotal} acabados',
  albumDone: '¡Completa!',
  albumRepeats: 'Repetidas: ×{n}',
  finishNone: 'Todavía sin pegar',
  finishComum: 'Común',
  finishBrilhante: 'Brillante',
  finishHolografica: 'Holográfica',
  finishDourada: 'Dorada',
  stickerUp: '{icon} ¡Estampa {finish}: {name}!',
  stickerSecret: '🔓 ¡Estampa secreta descubierta: {icon} {name}!',
  albumHidden: 'Estampa secreta',
  albumShowcase: 'Destacada',
  albumNoShowcase: 'Ninguna: elige una estampa pegada',
  albumTitleLabel: 'Título',
  albumNoTitle: 'Sin título',
  albumFeature: 'Usar como destacada',
  albumUnfeature: 'Dejar de destacar',
  albumTitlesSummary: 'Títulos: {got} de {total}',
  albumTitlesHint: 'Cada página da un título cuando todas sus estampas están Holográficas o Doradas. Tu título y tu estampa destacada aparecen para los demás en el marcador y cuando los eliminas.',
  errStickerLocked: 'Todavía no tienes esa estampa o ese título.',
  customize: 'PERSONALIZAR PERSONAJE',
  changeName: 'Cambiar nombre',
  nameFreeAt: 'Próximo cambio disponible el {date}.',
  nameRule: 'El primer cambio es gratis; después, uno cada 7 días.',
  linkDiscord: 'Vincular Discord',
  unlinkDiscord: 'Desvincular Discord',
  discordLinked: 'Discord vinculado.',
  deleteAccount: 'Eliminar cuenta',
  deleteConfirm: '¿Eliminar la cuenta? Tienes 30 días para arrepentirte iniciando sesión de nuevo. Después, el nombre y el correo se borran.',
  cancelDeletion: 'Cancelar eliminación',
  deletionPending: 'Cuenta programada para eliminarse el {date}. El juego en línea queda bloqueado hasta que la canceles.',
  saved: 'Guardado.',
  errCredentials: 'Correo o contraseña incorrectos.',
  errTooMany: 'Demasiados intentos. Espera un minuto e inténtalo de nuevo.',
  errSuspended: 'Esta cuenta está suspendida.',
  errPendingDeletion: 'Esta cuenta está programada para eliminarse. Cancélalo en Perfil para jugar en línea.',
  errEmailUsed: 'Ese correo ya tiene cuenta. Inicia sesión o usa "Olvidé mi contraseña".',
  errEmailInvalid: 'Correo inválido.',
  errPasswordInvalid: 'La contraseña debe tener de 8 a 128 caracteres.',
  errNameInvalid: 'Nombre inválido: de 3 a 16 letras o números.',
  errNameTaken: 'Ese nombre ya no tiene números libres. Prueba otro.',
  errNameCooldown: 'Podrás cambiar de nombre otra vez el {date}.',
  errTokenInvalid: 'Enlace inválido o vencido. Pide otro en "Olvidé mi contraseña".',
  errOnlyLogin: 'Discord es la única forma de entrar a esta cuenta.',
  errDiscordUnavailable: 'Iniciar sesión con Discord no está disponible en esta dirección.',
  errDiscordLinked: 'Ese Discord ya está vinculado a una cuenta.',
  errUnauthorized: 'Inicia sesión de nuevo.',
  errOffline: 'Servidor caído. Ejecuta "bun run dev:online" (o juega la práctica sin conexión).',
  errGeneric: 'Algo salió mal. Inténtalo de nuevo.',
  onlineSubtitle: 'Sesión: {name} · {mode}',
  // Mapas and Gerenciamento tabs (PF-6: client/ui/maps.ts, client/ui/management.ts).
  tabMaps: 'MAPAS',
  tabManagement: 'ADMINISTRACIÓN',
  mapsOfficial: 'Oficiales',
  mapsCommunity: 'Comunidad',
  mapsNew: '+ Nuevo mapa',
  mapsSearch: 'Buscar…',
  mapsSearchBy: 'Buscar por',
  mapsByName: 'Nombre',
  mapsByAuthor: 'Autor',
  mapsOrder: 'Orden',
  mapsOrderPlayed: 'Más jugados',
  mapsOrderRecent: 'Más recientes',
  mapsShowHidden: 'Mostrar ocultos',
  mapsEmpty: 'No se encontraron mapas.',
  mapsMore: 'Ver más',
  mapsPlays: '{n} partidas',
  mapsPlaysOne: '1 partida',
  mapsVersion: 'versión {v}',
  mapsBy: 'por {autor}',
  mapsOfficialBy: 'Mapa oficial',
  mapsCommunitySub: 'Mapa de la comunidad',
  mapsZombieOnly: 'Solo zombis',
  mapsHiddenTag: 'Oculto',
  mapsHiddenWhy: 'Oculto: {motivo}',
  mapsPlay: 'Jugar',
  mapsBots: 'Contra bots',
  mapsRange: 'Campo de tiro',
  mapsEdit: 'Editar',
  mapsDuplicate: 'Duplicar',
  mapsDelete: 'Eliminar',
  mapsHide: 'Ocultar',
  mapsUnhide: 'Mostrar',
  mapsVersions: 'Versiones',
  mapsCancel: 'Cancelar',
  mapsClose: 'Cerrar',
  mapsDeleteConfirm: '¿Eliminar "{nome}"? Sale de las listas y ya no abre partidas (las partidas en curso terminan en él).',
  mapsHideReason: 'Motivo (opcional)',
  mapsHideConfirm: '¿Ocultar "{nome}" de las listas? Solo su autor y el equipo podrán seguir viéndolo.',
  mapsVersionsTitle: 'Versiones guardadas',
  mapsRestore: 'Restaurar',
  mapsCurrent: 'actual',
  mapsRestored: 'Versión {v} restaurada: las partidas nuevas la usan.',
  mapsDuplicated: 'Copia de "{nome}" creada en Comunidad.',
  mapsDeleted: 'Mapa eliminado.',
  mapsHidden: 'Mapa ocultado.',
  mapsUnhidden: 'El mapa volvió a las listas.',
  mapsLoading: 'Cargando…',
  mgTitle: 'Administración',
  mgHint: 'Busca una cuenta por su nombre o su etiqueta (Nombre#1234).',
  mgSearch: 'Nombre o Nombre#1234',
  mgFind: 'Buscar',
  mgOpen: 'Abrir',
  mgEmpty: 'No se encontraron cuentas.',
  mgBanned: 'Baneada',
  mgMuted: 'Silenciada',
  mgSuspended: 'Suspendida',
  mgPendingDeletion: 'En eliminación',
  mgRole_admin: 'Admin',
  mgRole_moderador: 'Moderador',
  mgPlayer: 'Jugador',
  mgReadOnly: 'No puedes modificar esta cuenta: un moderador no actúa sobre un admin.',
  mgSanctions: 'Sanciones',
  mgNoPunish: 'No puedes sancionar esta cuenta.',
  mgBan: 'Banear',
  mgMute: 'Silenciar',
  mgReason: 'Motivo',
  mgDuration: 'Duración',
  mgDur_1h: '1 hora',
  mgDur_12h: '12 horas',
  mgDur_1d: '1 día',
  mgDur_7d: '7 días',
  mgDur_30d: '30 días',
  mgDur_permanente: 'Permanente',
  mgApply: 'Aplicar',
  mgUnban: 'Quitar el baneo',
  mgUnmute: 'Quitar el silencio',
  mgHistory: 'Historial',
  mgNoSanctions: 'Sin sanciones.',
  mgSanction_banimento: 'Baneo',
  mgSanction_silencio: 'Silencio',
  mgUntil: 'hasta el {data}',
  mgForever: 'sin fin',
  mgRevoked: 'retirada el {data}',
  mgBy: 'por {tag}',
  mgNeedReason: 'Escribe el motivo.',
  mgName: 'Nombre',
  mgNameHint: 'Cambia al instante, sin la espera de 7 días; la espera del jugador vuelve a empezar.',
  mgLook: 'Apariencia',
  mgEditLook: 'Editar apariencia',
  mgProgress: 'Progreso',
  mgAccountXp: 'XP de la cuenta (nivel {n})',
  mgWeaponXp: 'XP de las armas',
  mgSaveProgress: 'Guardar progreso',
  mgBadNumber: 'Usa números enteros de 0 a 1000 millones.',
  mgRoles: 'Roles',
  mgPromote: 'Ascender a {papel}',
  mgDemote: 'Quitar {papel}',
  mgRolesNone: 'No puedes cambiar los roles de esta cuenta.',
  mgDone: 'Listo.',
  errNoPermission: 'No tienes permiso para eso.',
  errNotFound: 'No encontrado.',
  errBadInput: 'Datos inválidos.',
  errLastAdmin: 'El último admin no se puede quitar.',
  errProtectedMap: 'Los cuatro mapas oficiales originales no se pueden borrar ni ocultar.',
  // Pause menu (client/ui/menu.ts, client/ui/pauseMenu.ts): the rail (where we are, the banner, the exit), the
  // mode's tab and the settings' tab in the panel, and the exit's confirmation. Same texts on the start card.
  pmLineSession: 'Sesión: {name} · {n}/{max} jugadores',
  pmLineBots: 'Contra {n} bots · {skill}',
  // {wave}: pmLineWave, or before the first wave the HUD's countdown title (zCountdown).
  pmLineWave: 'Oleada {n}/{total}',
  pmLineWaveTeam: '{wave} · {players} jugadores',
  pmLineWaveAlone: '{wave} · 1 jugador',
  pmLineWaveSolo: '{wave} · solo',
  pmLineRange: 'Práctica sin conexión con los muñecos',
  pmPreview: 'Vista previa: {file}',
  pmLiveOnline: 'En línea: el juego sigue y te pueden balear.',
  pmLiveHorde: 'En línea: la horda no espera. Tu equipo sigue peleando.',
  pmPausedBots: 'Juego en pausa: los bots te esperan.',
  pmPaused: 'Juego en pausa.',
  pmExitSession: 'Salir de la sesión',
  pmExitMatch: 'Salir de la partida',
  pmExitRace: 'Salir de la carrera',
  pmExitRange: 'Salir de la práctica',
  pmConfirmSession: 'Sales de la sesión {name} y vuelves a la pantalla de inicio. Los puntos que tus armas ya ganaron se quedan en tu cuenta.',
  pmConfirmBots: 'La partida contra los bots termina y vuelves a la pantalla de inicio.',
  pmConfirmRace: 'Sales de la carrera y pierdes el escalón en el que estás. De vuelta a la pantalla de inicio.',
  pmConfirmRaceBots: 'La carrera contra los bots termina y vuelves a la pantalla de inicio.',
  pmConfirmZombieTeam: 'Tu equipo sigue sin ti. El dinero de esta partida no se guarda.',
  pmConfirmZombieAlone: 'La partida vuelve a empezar para el próximo que entre. El dinero de esta partida no se guarda.',
  pmConfirmZombieSolo: 'La partida termina y el dinero no se guarda.',
  pmConfirmRange: 'Sales del campo de tiro y vuelves a la pantalla de inicio.',
  pmConfirmEditor: 'El juego se detiene y vuelves al editor, justo donde estabas.',
  pmStay: 'QUEDARSE',
  pmLeave: 'SALIR',
  pmStayHint: 'sigues en la partida',
  pmClose: 'Cerrar',
  pmBack: 'Volver',
  pmHintResume: 'Volver al juego',
  pmHintBack: 'Volver',
  pmHintPick: 'Elegir',
  pmBadgeReadOnly: '🔒 Solo consulta',
  pmBadgeEditable: 'Editable en la práctica',
  pmArsenalSubReadOnly: 'Tu equipamiento · solo consulta',
  pmArsenalSubEditable: 'Cambia armas y mejoras',
  pmArsenalHintReadOnly: 'Lo que trajiste a esta partida.',
  pmArsenalHintEditable: 'El campo de tiro te deja cambiar todo, y se aplica al instante.',
  pmArsenalFootReadOnly: 'Bloqueado durante la partida. Cambia armas y mejoras en el Arsenal de la pantalla de inicio: los cambios se aplican desde la próxima partida.',
  pmArsenalFootEditable: 'En el campo de tiro el Arsenal es editable y los cambios se aplican al instante.',
  pmArsenalFootGuest: 'Crea una cuenta para que tus armas evolucionen',
  pmUpgradesUnlocked: 'Mejoras desbloqueadas',
  pmNoUpgrades: 'Todavía no hay mejoras desbloqueadas',
  pmMoreUpgrades: '🔒 {n} mejoras más por desbloquear. Siguiente: {upgrade}, te faltan {xp} pts de {prog}.',
  pmMoreUpgrade: '🔒 1 mejora más por desbloquear: {upgrade}, te faltan {xp} pts de {prog}.',
  pmNextMatch: 'Aplica en la próxima partida',
  pmWeaponsUnlocked: 'Armas desbloqueadas',
  pmTabLadder: 'Escalera',
  pmTabLadderSub: 'Escalón {n} de {total} · {k}/{need} bajas',
  pmLadderHint: 'Todos usan las mismas armas, con los mismos atributos.',
  pmLadderYou: 'Tú · {k}/{need}',
  pmLadderNow: 'Ahora · escalón {n}',
  pmLadderNext: 'Siguiente · escalón {n}',
  pmLadderToGo: 'faltan {n} bajas para subir',
  pmLadderToGoOne: 'falta 1 baja para subir',
  pmLadderToWin: 'faltan {n} bajas para ganar',
  pmLadderToWinOne: 'falta 1 baja para ganar',
  pmLadderGun: '{mag} balas · {rpm} rpm',
  pmLadderSilenced: 'disparo amortiguado',
  pmLadderFinal: 'Baja final',
  pmLadderFinalOne: 'Una baja con el {weapon} gana la ronda',
  pmLadderFinalMany: '{n} bajas con el {weapon} ganan la ronda',
  pmRuleClimb: '{n} bajas con el arma actual o con el cuchillo te suben un escalón.',
  pmRuleStab: 'Morir por una cuchillada te quita una baja. Sin bajas en el escalón, retrocedes un arma.',
  pmRuleFinalOne: 'En el último escalón, una baja con el {weapon} gana la ronda.',
  pmRuleFinalMany: 'En el último escalón, {n} bajas con el {weapon} ganan la ronda.',
  pmLeader: 'Líder',
  pmLeaderOther: '{name} · escalón {n} ({weapon})',
  pmLeaderYou: 'Vas en primer lugar',
  pmTabCoffin: 'Ataúd',
  pmTabCoffinSub: 'Lo que llevas y las probabilidades',
  pmCoffinHintOnline: '${cost} por arma, sorteada en el servidor. La rareza multiplica el daño contra zombis.',
  pmCoffinHintSolo: '${cost} por arma. La rareza multiplica el daño contra zombis.',
  pmCoffinFoot: 'El arma nueva reemplaza a la del mismo tipo (rifle, secundaria o cuchillo). Si sale dañada, no tiene arreglo: solo queda otro giro.',
  pmCoffinOdds: 'Probabilidades · ${cost}',
  pmCoffinMul: '×{m} de daño',
  pmCoffinBroken: '{n}% sale dañada',
  pmConfigSub: 'Puntería, video, audio y teclas',
  pmConfigHint: 'Todo se aplica al instante.',
  pmSubAim: 'Puntería',
  pmSubVideo: 'Video',
  pmSubAudio: 'Audio',
  pmSubKeys: 'Teclas',
  pmSubPad: 'Control',
  pmSubTouch: 'Táctil',
  pmDescSens: 'Mouse, sin apuntar',
  pmDescAds: 'Multiplica la sensibilidad mientras apuntas',
  pmDescPadSens: 'Stick derecho',
  pmDescAssist: 'La mira va más lenta sobre un enemigo, pero no te arrastra desde lejos',
  pmDescInvert: 'Mover hacia arriba mira hacia abajo',
  pmDescFov: 'Más amplio, ves más hacia los lados',
  pmDescQuality: 'Automática: se ajusta sola para mantener los FPS',
  pmDescDetail: 'Ligero simplifica árboles, follaje y adornos (aplica desde la próxima partida)',
  pmDescFullscreen: 'En pantalla completa, Esc abre y cierra el menú al instante',
  // The language (PF-30): the row in the settings' Video tab, the landing's button, the page title and the
  // game server's refusals by code (shared/protocol.ts WsErrorCode).
  language: 'Idioma',
  pmDescLanguage: 'Textos, menús y el correo de contraseña. Fuera de la partida, la pantalla se recarga al instante',
  langLater: 'Idioma guardado: se aplica al volver al inicio',
  docTitle: 'Offensive Combat — Prototipo',
  wsErr_sem_ola: 'La conexión no se presentó. Intenta de nuevo.',
  wsErr_sessao_lotada: 'Sesión llena.',
  wsErr_sessao_inexistente: 'Esa sesión ya no existe.',
  wsErr_mapa_indisponivel: 'Ese mapa no está disponible.',
  wsErr_modo_fora_do_mapa: 'Ese modo no se juega en ese mapa.',
  wsErr_sem_mapa: 'No hay mapas disponibles para ese modo.',
  wsErr_entrada_falhou: 'No se pudo entrar ahora.',
  pmDescVolume: 'Volumen general del juego',
  pmDescSpatial: 'Automático: 3D en PC, estéreo en celular',
  pmOn: 'Activado',
  pmOff: 'Desactivado',
  keyGroupMove: 'Movimiento',
  keyGroupCombat: 'Combate',
  keyGroupOther: 'Otros',
  pmKeyPress: 'Presiona…',
  pmEscFixed: 'abre el menú (fija)',
  pmPadNote: 'Distribución fija del control (estilo CoD). Las teclas del teclado se pueden reasignar.',
  gpuWarning: 'Tu navegador está dibujando el juego sin tarjeta de video (renderizador: {gpu}), por eso se queda en ~10 FPS. Activa “Usar aceleración de gráficos cuando esté disponible” en chrome://settings/system (en Edge: edge://settings/system) y reinicia el navegador.',
  // Galpão (client/ui/galpao): the 3D home's menu, stations, signs, Arsenal board and launch.
  gpQuick: 'ENTRADA RÁPIDA',
  gpQuickLine: '{mode} · En línea · {map}',
  gpBack: '‹ GALPÓN',
  gpLaunching: 'ENTRANDO A LA PARTIDA',
  gpLaunchOnline: '{map} · {mode} · {n}/{max} jugadores',
  gpLaunchBots: 'Contra {n} bots · {map}',
  gpLaunchHorde: 'Solo contra la horda · {map}',
  gpLaunchRange: 'Práctica sin conexión · {map}',
  gpSt_play: 'Jugar',
  gpSt_maps: 'Mapas',
  gpSt_arsenal: 'Arsenal',
  gpSt_album: 'Álbum',
  gpSt_profile: 'Perfil',
  gpSt_settings: 'Configuración',
  gpSt_admin: 'Administración',
  gpStSub_play: 'En línea, contra bots o campo de tiro',
  gpStSub_maps: 'Oficiales y de la comunidad: juega, duplica o crea',
  gpStSub_arsenal: 'Armas, mejoras y equipamiento',
  gpStSub_album: 'Estampas, títulos y destacada',
  gpStSub_profile: 'Cuenta, estadísticas y personaje',
  gpStSub_settings: 'Puntería, video, audio y teclas',
  gpStSub_admin: 'Moderación · solo para el equipo',
  gpHint_play: 'Elige el mapa y juega. El botón naranja inicia.',
  gpHint_maps: 'Juega un mapa, duplica uno para editarlo o crea uno desde cero.',
  gpHint_arsenal: 'Arrastra para moverte, rueda del mouse para hacer zoom. Haz clic en un arma para ver los detalles. Verde: equipada · roja: bloqueada.',
  gpHint_arsenalTouch: 'Arrastra para moverte, pellizca para hacer zoom. Toca un arma para ver los detalles. Verde: equipada · roja: bloqueada.',
  gpHint_album: 'Haz clic en una estampa para ver cómo pegarla. Las pestañas pasan las páginas.',
  gpHint_profile: 'Tu ficha: estadísticas, últimas partidas y las opciones de la cuenta.',
  gpHint_settings: 'Elige una sección arriba del tablero. Los cambios se aplican al instante.',
  gpHint_admin: 'Busca la cuenta, revisa su situación y elige una acción. Nada cambia hasta que lo confirmes.',
  gpSign_play: '01 · OPERACIONES',
  gpSign_maps: '02 · MAPAS',
  gpSign_arsenal: '03 · ARSENAL',
  gpSign_profile: '05 · VESTIDOR',
  gpSign_settings: '06 · TALLER',
  gpSign_admin: '08 · SEGURIDAD',
  gpSign_pets: '07 · MASCOTAS',
  gpSt_pets: 'Mascotas',
  gpStSub_pets: 'Compañeros: elige, ponle nombre y collar',
  gpHint_pets: 'Haz clic en un gancho para llamar a la mascota. Solo "Llevar esta" cambia la que va contigo.',
  gpHint_petsTouch: 'Toca un gancho para llamar a la mascota. Solo "Llevar esta" cambia la que va contigo.',
  gpBoard_primaria: 'PRINCIPAL',
  gpBoard_secundaria: 'SECUNDARIA',
  gpBoard_faca: 'CUCHILLO',
  gpBoard_granada: 'GRANADA',
  gpAdminScreen: 'ADMINISTRACIÓN',
  gpAdminScreenSub: 'ACCESO RESTRINGIDO · EQUIPO',
  gpDanger: 'PELIGRO',
  gpHighVoltage: 'ALTO VOLTAJE',
  gpYard: 'PATIO',
  gpAlbumCover1: 'OFFENSIVE COMBAT · ÁLBUM OFICIAL',
  gpAlbumCover2: 'ESTAM',
  gpAlbumCover3: 'PAS',
  gpAlbumCover4: '{n} ESTAMPAS',
  gpTagLevel: 'NV{level}',
  gpTagLocked: 'BLOQ.',
  gpTagOn: 'ON',
  gpTagOff: 'OFF',
  gpLockedChip: 'BLOQUEADA',
  gpSharesProg: 'Usa los puntos y las mejoras de {prog}',
  gpAutoOn: 'Se activa sola al desbloquearse',
  gpUpgradesOf: 'MEJORAS DE {prog}',
  gpPlayHintOnline: 'En línea, con otras personas. Da XP para la cuenta.',
  gpPlayHintBots: 'Partida sin conexión contra bots, con tu Arsenal y las mejoras de la cuenta.',
  gpPlayHintRange: 'Práctica sin conexión con muñecos quietos.',
  gpCtaLine: '{mode} · {map}',
  gpRangeTargets: 'Muñecos quietos',
  tabPets: 'MASCOTAS',
  petsTitle: 'Mascotas',
  petsSub: 'Una mascota va contigo: adorno en el PvP, ayuda en el modo zombi. Todas gratis por ahora.',
  petTake: 'Llevar esta',
  petWithYou: '✓ Va contigo',
  petLeave: 'Dejar en el patio',
  petNoneWithYou: 'Ninguna mascota va contigo ahora.',
  petTagWith: 'CONTIGO',
  petLocked: 'APOYO',
  petLockedHow: 'Se desbloquea con el paquete de apoyo.',
  petNameLabel: 'Nombre (solo tú lo ves)',
  petNameFixed: 'Amora es Amora: su nombre y su pelaje no cambian, solo el collar.',
  petCoat: 'Pelaje',
  petRobe: 'Túnica',
  petCollar: 'Collar',
  petPvp: 'Contigo en el PvP',
  petPvpSub: 'Solo adorno: pegada a ti, sin ruido, desaparece cuando no estás a la vista',
  petPve: 'Contigo en el modo zombi',
  petPveSub: 'Actúa sola con su habilidad, sin daño y sin dinero',
  petAbilityTitle: 'EN EL MODO ZOMBI',
  petSaveFailed: 'No se pudo guardar la mascota',
  petSaved: 'Mascota guardada',
  petCooldown: 'Recarga: {s} s',
  petCharges: '{n} veces por partida',
  petAbility_amora: '¡Agárralo, Amora!',
  petAbility_bruxinha: 'Hechizo del Pato',
  petAbility_gato: 'Séptima Vida',
  petAbility_fuinha: 'Manos a la Obra',
  petAbility_lontra: 'Pedrada',
  petAbility_iguana: 'Cola de Carnada',
  petAbilityDesc_amora: 'Ladra, muerde la espinilla del zombi más cercano (hasta {r} m) y lo sujeta por {s} s. Al Guardia de la Disco y a los jefes solo les da un tirón.',
  petAbilityDesc_bruxinha: 'Atrapa al zombi peligroso más cercano (hasta {r} m) en un flotador de patito por {s} s: quieto, y recibiendo disparos. Los jefes son inmunes.',
  petAbilityDesc_gato: 'Cuando caes, ella te levanta sola en {s} s (un compañero tarda menos). Si un compañero empieza a reanimarte, ella le cede el turno.',
  petAbilityDesc_fuinha: 'Clava tablas despacio, una cada {s} s, en la barricada más dañada cerca de ti (hasta {r} m).',
  petAbilityDesc_lontra: 'Una pedrada interrumpe el escupitajo de la Tía Chismosa o la hinchazón del Tío Parrillero cerca de ti (hasta {r} m).',
  petAbilityDesc_iguana: 'Con poca vida, cuando un zombi te golpea ella suelta la cola: los zombis cercanos (hasta {r} m) van tras ella por {s} s.',
  petAct_hold: '¡Lo agarró!',
  petAct_nudge: '¡Tirón!',
  petAct_duck: '¡Pato!',
  petAct_lift: 'Levantando…',
  petAct_yield: 'Esperando al compañero',
  petAct_up: '¡De pie!',
  petAct_nail: '¡Tabla!',
  petAct_stone: '¡Pedrada!',
  petAct_tail: '¡Cola!',
  zCatLifting: 'La gata te está levantando · {s}s',
  zCatLiftingNamed: '{name} te está levantando · {s}s',
  hidePets: 'Ocultar las mascotas de los demás',
  pmDescHidePets: 'Solo en el PvP: las mascotas de los demás desaparecen (la tuya se queda)',
};

export const tips: string[] = [
  'Consejo: dispararle al enemigo suele funcionar mejor que dispararle a la pared.',
  'Consejo: el muñeco no te devuelve los disparos. Todavía.',
  'Consejo: caer de 7 metros duele. Pregúntale a tu rodilla.',
  'Consejo: apuntar a la cabeza hace el doble de daño y el triple de arrogancia.',
  'Consejo: no se puede correr y disparar al mismo tiempo. Lo prohíbe el sindicato de brazos.',
  'Consejo: el camión de helados no vende helados. Pero pone música.',
  'Consejo: los flamencos no tienen la culpa de nada.',
];

export const quickChat: string[] = ['GG', '¡Buena!', 'Jajaja', '¡Cuidado!', '¿1v1?', '¡Gracias!'];

export const deathMessages: DeathLines = {
  fall: ['Le ganaste a la gravedad. Mentira, ella te ganó a ti.', 'La próxima vez, intenta caer de pie.', 'La acera te manda saludos.'],
  void: ['Te saliste del mapa. El mapa no te extrañó.', 'Explorador valiente. Explorador muerto.'],
  explosion: ['Cocinaste de más. A la granada, y a ti mismo.', 'Consejo: la granada se lanza hacia el enemigo.'],
  dog: ['A Amora no le gustó tu visita.', 'Mordido por Amora. Tierna, pero brava.', 'Patio equivocado. Guau.'],
  zombie: ['Te convertiste en almuerzo de zombi.', 'El vecino te mordió. Y no era de cariño.', 'Nadie vino a reanimarte. Qué vecindario.'],
  thorns: ['La reja tenía espinas. No lo decía en ninguna parte.', 'Saltar el muro: 0. Espinas: 1.', 'Te desangraste. El seto te lo agradece.'],
  sacrilege: ['Te subiste al altar. Al altar no le gustó.', 'Sacrilegio: la capilla cobra caro.', 'El tótem es para encenderlo, no para pisarlo.'],
  crows: ['Los cuervos te encontraron primero.', 'Un árbol no es escondite. Los cuervos te avisaron.', 'Picoteado hasta el final.'],
};
