// Every user-facing string lives here (section 5: pt-BR and en at minimum).
const ptBR = {
  title: 'OFFENSIVE COMBAT',
  subtitle: 'Protótipo de tiro · Fase 1',
  play: 'JOGAR',
  resume: 'VOLTAR AO JOGO',
  aimOnNextKey: 'A mira volta com a próxima tecla ou clique',
  loading: 'Carregando',
  settings: 'Configurações',
  sensitivity: 'Sensibilidade',
  adsSensitivity: 'Sensibilidade na mira',
  fov: 'Campo de visão',
  volume: 'Volume',
  invertY: 'Inverter eixo Y',
  health: 'VIDA',
  reload: 'RECARREGUE',
  noAmmo: 'SEM MUNIÇÃO',
  reloading: 'RECARREGANDO…',
  points: 'Pontos',
  kills: 'Abates',
  accuracy: 'Precisão',
  you: 'Você',
  kill: 'Abate',
  headshot: 'Tiro na cabeça',
  longShot: 'Longa distância',
  respawnIn: 'Renascendo em {s}…',
  debugHint: 'F3 depuração · F4 hitboxes e colisores (personagem → personagem + assets → nenhum)',
  debugViewChars: 'F4: hitboxes dos personagens',
  debugViewAll: 'F4: personagens + colisores do mapa',
  debugViewOff: 'F4: depuração visual desligada',
  keyMove: 'Mover',
  keyJump: 'Pular',
  keyCrouch: 'Agachar (correndo: derrapar)',
  keySprint: 'Correr',
  keyFire: 'Atirar',
  keyAds: 'Mirar',
  keyReload: 'Recarregar',
  keyPause: 'Menu',
  mouseLeft: 'Botão esq.',
  mouseRight: 'Botão dir.',
  keyMelee: 'Facada',
  keyTaunt: 'Oprimir (perto do corpo)',
  keyDonate: 'Doar a arma do caixão (zumbi)',
  keyRefuse: 'Recusar a arma do caixão (zumbi)',
  keyGrenade: 'Granada (segure para cozinhar)',
  keyForward: 'Andar para frente',
  keyBack: 'Andar para trás',
  keyLeft: 'Andar à esquerda',
  keyRight: 'Andar à direita',
  keyScoreboard: 'Placar',
  keyPrimary: 'Principal',
  keyAlternate: 'Alternativa',
  keyPress: 'Pressione uma tecla… (Esc cancela)',
  keyClear: 'Tirar a tecla',
  keyUnbound: 'Sem tecla',
  keyMoved: '{key} estava em "{action}", que ficou sem tecla {slot}.',
  keyNoCtrl: 'O Ctrl não pode ser usado: Ctrl+W fecha a aba do navegador.',
  keyFixed: '{key} é reservada para a depuração.',
  keyWheelHold: 'A roda do mouse não fica pressionada: use-a em pular, atirar, recarregar, facada, granada, oprimir ou trocar de arma.',
  keysReset: 'Restaurar teclas padrão',
  grenadeName: 'Granada',
  knife: 'Facada',
  knifeName: 'Faca',
  mineLimit: 'Máximo de {n} minas no mapa',
  cherryTaken: '🍒 Cereja do Dragão: +{n} de vida máxima por {s} s',
  cherryOver: 'O efeito da cereja acabou',
  koiXp: '🐟 Peixe abatido: +{n} XP',
  goldenKoiXp: '✨ Carpa dourada: +{n} XP',
  goldenKoi: '✨ Carpa dourada! Mira afiada por {s} s',
  goldenKoiOver: 'A mira afiada da carpa acabou',
  galleryAim: '🎯 Todos os alvos! Mira afiada por {s} s',
  humanityTaken: '🕯️ Humanidade obtida: +{n} de vida máxima até morrer',
  biscuitTaken: '🦴 Biscoito Scooby! Vida cheia. Scooby-Dooby-Doo!',
  promptPotion: 'Beber Poção',
  potion_pato: '🦆 Granadas de pato até morrer!',
  potion_veloz: '💨 Poção da pressa: mais rápido por {s} s',
  potion_lerdo: '🐌 Poção da lerdeza: mais lento por {s} s',
  potion_critico: '💀 Poção do crítico: todo tiro é crítico por {s} s',
  potion_bebado: '🍺 Poção do bêbado: mira torta por {s} s',
  potionOver: 'O efeito da poção acabou',
  galleryAimOver: 'A mira afiada do tiro ao alvo acabou',
  buffKoi: 'Mira da carpa',
  buffGallery: 'Mira afiada',
  buffCherry: 'Vida extra',
  buffHumanity: 'Humanidade',
  buffDuck: 'Granadas de pato',
  buffVeloz: 'Pressa',
  buffLerdo: 'Lerdeza',
  buffCritico: 'Tiro crítico',
  buffBebado: 'Bêbado',
  buffUntilDeath: 'até morrer',
  buffUntilMatchEnd: 'até o fim da partida',
  arsenal: 'Arsenal',
  level: 'Nível',
  locked: 'Bloqueado',
  xpToNext: 'Faltam {xp} pontos para o nível {level}',
  maxLevel: 'Nível máximo! {xp} pontos',
  unlockShort: 'faltam {xp} pts',
  // Weapons and their upgrades (ids from shared/data/progression.json): arma_<weapon>, upg_<weapon>_<id>, and
  // the description of each (armaDesc_, upgDesc_). client/tests/arsenalText.test.ts checks none is missing.
  arma_rifle: 'Rifle Padrão',
  armaDesc_rifle: 'O de sempre. Mira de ferro e fé. Bom de perto, bom de longe, ótimo de lado nenhum.',
  arma_pistola: 'Pistola do Porteiro',
  armaDesc_pistola: 'Doze tiros e toda a autoridade do condomínio. Semiautomática: um clique, um tiro. Sai rápido do coldre.',
  arma_smg: 'Submetralhadora Liquidificador',
  armaDesc_smg: 'Faz vrrrrr e bate tudo. Cospe bala de perto e chora de longe. Mais leve: você corre mais com ela.',
  arma_grampeador: 'Grampeador do RH',
  armaDesc_grampeador: 'Tec-tec-tec: três grampos por clique, direto no memorando. Bom de perto e no meio do caminho, mas entre uma rajada e outra ele engasga com o papel.',
  arma_revolver: 'Revólver do Delegado da Quadrilha',
  armaDesc_revolver: 'Do casamento caipira: é com ele que o delegado obriga o noivo a casar. Seis balas que batem forte, mas o tambor gira devagar e recarregar é uma novela.',
  arma_furadeira: 'Furadeira do Vizinho de Domingo',
  armaDesc_furadeira: 'Oito da manhã de domingo: rrrrrrrr. Fura tudo num piscar e acorda o bairro, mas a broca espalha e não alcança nem o portão.',
  arma_garrucha: 'Garrucha do Cangaceiro',
  armaDesc_garrucha: 'Dois canos, chapéu de couro e nenhuma paciência. De pertinho resolve num tiro; de longe é chuva de chumbinho que só faz cosquinha. Dois tiros e abre pra recarregar.',
  arma_pistolao: 'Pistolão do Marombeiro',
  armaDesc_pistolao: 'Treinou braço a semana inteira só pra isso. Bate como um rifle e um tiro na cabeça resolve, mas o coice joga a mira pro teto, pesa e as sete balas acabam rápido.',
  arma_faca: 'Faca de Cozinha',
  armaDesc_faca: 'Pegou emprestada da cozinha e não devolveu. Um golpe, um abate.',
  arma_granada: 'Granada de Fragmentação',
  armaDesc_granada: 'Explode no primeiro contato. Cozinhe demais e ela explode na sua mão.',
  // The old rifles and knives (they use the rifle's and the knife's points and upgrades).
  arma_rifleFita: 'Rifle Remendado com Fita',
  armaDesc_rifleFita: 'Metade silver tape, metade coragem. Recarrega rápido, mas a fita está solta e o coice pula mais.',
  arma_rifleTia: 'Rifle da Tia do Zap',
  armaDesc_rifleTia: 'Cor-de-rosa, com adesivo de florzinha. Bom dia! Atira mais rápido e mira num instante, mas cada bala bate um pouco menos.',
  arma_rifleNatal: 'Rifle Pisca-Pisca de Natal',
  armaDesc_rifleNatal: 'Enrolado em luzinhas. O coice é bem mais manso, mas pisca-pisca não tem pressa: atira mais devagar.',
  arma_rifleChama: 'Rifle Tunado com Adesivo de Chama',
  armaDesc_rifleChama: 'Adesivo de chama dá +10 de velocidade, todo mundo sabe. Atira mais rápido e você corre mais, mas as balas espalham.',
  arma_rifleVovo: 'Rifle do Vovô',
  armaDesc_rifleVovo: 'Madeira envernizada, do tempo em que rifle durava. Bate forte, mas é lento para atirar e para mirar.',
  arma_rifleOuro: 'Rifle Dourado Ostentação',
  armaDesc_rifleOuro: 'Todo de ouro e pente de 40. Não combina com nada, e é isso que importa. Pesado: você anda e recarrega mais devagar.',
  arma_colher: 'Colher de Pau da Vó',
  armaDesc_colher: 'Quem já levou uma sabe: é letal. Um pouco mais de alcance, golpes um pouco mais lentos.',
  arma_frango: 'Frango de Borracha',
  armaDesc_frango: 'Aperta e grita. Investida bem mais longa, mas todo mundo ouve o grito de longe.',
  arma_baguete: 'Baguete Amanhecida',
  armaDesc_baguete: 'Dura de ontem. Crocante por fora, fatal por dentro. Mais alcance, golpes mais lentos.',
  arma_peixe: 'Peixe Congelado',
  armaDesc_peixe: 'Tirado direto do freezer. Investida longa, mas o tapa gelado demora a sair.',
  arma_macarrao: 'Macarrão de Piscina',
  armaDesc_macarrao: 'Espuma de 60 centímetros. Parece inofensivo. Não é. Alcança longe, mas é lento e a investida é curta.',
  arma_sabre: 'Sabre de Luz Paraguaio',
  armaDesc_sabre: 'Comprado na 25 de Março. O maior alcance de todos e faz vuuum (todo mundo ouve). As pilhas são fracas: mais tempo entre golpes.',
  // A progression's short name ("faltam 600 pts de faca").
  prog_rifle: 'rifle',
  prog_pistola: 'pistola',
  prog_smg: 'submetralhadora',
  prog_faca: 'faca',
  prog_granada: 'granada',
  upg_rifle_pontoVermelho: 'Mira de Ponto Vermelho da Feira',
  upgDesc_rifle_pontoVermelho: 'Comprada no camelô, mas o pontinho acende. Mira mais firme e um pouco de zoom.',
  upg_rifle_empunhadura: 'Empunhadura de Cabo de Vassoura',
  upgDesc_rifle_empunhadura: 'Um cabo de vassoura preso com abraçadeira embaixo do cano. Segura o coice e aperta o tiro.',
  upg_rifle_luneta: 'Luneta do Vovô (3x)',
  upgDesc_rifle_luneta: 'A luneta de latão que o vovô usava para espiar o vizinho. Zoom 3x e precisão de longe, mas mirar demora e a arma pesa. Substitui o ponto vermelho.',
  upg_rifle_pente: 'Pente Duplo com Silver Tape',
  upgDesc_rifle_pente: 'Dois pentes colados com fita: dez balas a mais e recarga mais rápida.',
  upg_rifle_silenciador: 'Silenciador de Garrafa PET',
  upgDesc_rifle_silenciador: 'Uma garrafa de 2 litros no cano. Só quem está perto ouve o tiro e ninguém vê o traçante. Em troca, menos dano e alcance.',
  upg_rifle_holoLupa: 'Holo com Lupa (1,5x)',
  upgDesc_rifle_holoLupa: 'A holográfica de carinha feliz com uma lupa de dobrar atrás. Zoom de 1,5x e mira mais firme; demora um tiquinho mais para mirar.',
  upg_rifle_luneta2x: 'Luneta 2x',
  upgDesc_rifle_luneta2x: 'Luneta curta de latão. Zoom 2x e mais alcance; mira mais devagar e pesa um pouco.',
  upg_rifle_luneta4x: 'Luneta 4x',
  upgDesc_rifle_luneta4x: 'A luneta comprida da vitrine. Zoom 4x e muito alcance; mirar demora e o rifle fica pesado.',
  upg_pistola_gatilho: 'Gatilho de Fliperama',
  upgDesc_pistola_gatilho: 'Arrancado de uma máquina de fliperama: dá para clicar bem mais rápido.',
  upg_pistola_pontoVermelho: 'Mini Ponto Vermelho',
  upgDesc_pistola_pontoVermelho: 'Pequenininho, mas honesto. Muito mais precisa mirando.',
  upg_pistola_coldre: 'Coldre de Velcro',
  upgDesc_pistola_coldre: 'Sai do coldre na metade do tempo, e o pente troca mais rápido também.',
  upg_pistola_batata: 'Silenciador de Batata',
  upgDesc_pistola_batata: 'Uma batata espetada no cano. Funciona nos filmes, funciona aqui: tiro abafado, sem traçante e menos coice. Mas um pouco menos de dano.',
  upg_smg_motor: 'Motor Turbo de Liquidificador',
  upgDesc_smg_motor: 'Velocidade 5 do liquidificador: mais tiros por segundo.',
  upg_smg_holo: 'Mira Holográfica da Tia do Zap',
  upgDesc_smg_holo: 'Uma carinha feliz flutuando na mira. Bom dia! Mais precisa mirando e no quadril.',
  upg_smg_tambor: 'Pente Tambor de Pipoqueira',
  upgDesc_smg_tambor: 'Mais 18 balas num tambor de pipoqueira. Em troca, a recarga e a troca de arma demoram mais e você anda um pouco mais devagar.',
  upg_smg_coronha: 'Coronha de Mangueira',
  upgDesc_smg_coronha: 'Uma mangueira de jardim enrolada no ombro. Menos recuo e menos dispersão.',
  upg_faca_afiador: 'Afiador da Feira',
  upgDesc_faca_afiador: 'O moço da feira afiou de graça. Golpes mais seguidos e um pouco mais de alcance.',
  upg_faca_tenis: 'Tênis de Molinha',
  upgDesc_faca_tenis: 'Tênis com molinha na sola: a investida vai mais longe e mais rápido.',
  upg_faca_maoLeve: 'Mão Leve',
  upgDesc_faca_maoLeve: 'Golpe rápido, sem enrolar: o golpe termina antes e a arma volta pronta para atirar mais cedo.',
  // Each knife's passive (shared/data/weapons/<faca>.json "passiva"), in the Arsenal and when it kicks in.
  passiva_discreta: 'Discreta',
  passivaDesc_discreta: 'O golpe só é ouvido de perto.',
  passiva_coloDeVo: 'Colo de Vó',
  passivaDesc_coloDeVo: 'Cada abate com ela recupera {vida} de vida.',
  passiva_fugaEscandalosa: 'Fuga Escandalosa',
  passivaDesc_fugaEscandalosa: 'Depois de um abate com ele, você corre {pct}% mais rápido por {s} s.',
  passiva_lanche: 'Pausa pro Lanche',
  passivaDesc_lanche: 'Cada abate com ela enche o pente da arma na mão.',
  passiva_tapaGelado: 'Tapa Gelado',
  passivaDesc_tapaGelado: 'A facada pelas costas vale +{pts} pts em vez de +{base}.',
  passiva_boia: 'Boia',
  passivaDesc_boia: 'Com ele equipado, você não leva dano de queda.',
  passiva_vuuum: 'Vuuum',
  passivaDesc_vuuum: 'O golpe acerta todos que estão no alcance e na frente, não só um.',
  knifePassive: 'Passiva: {name}',
  knifePassiveWhere: 'Vale no mata-mata, no treino e contra bots.',
  passiveFx_coloDeVo: '🥄 Colo de Vó: +{vida} de vida',
  passiveFx_fugaEscandalosa: '🐔 Fuga escandalosa!',
  passiveFx_lanche: '🥖 Pausa pro lanche: pente cheio',
  upg_granada_mina: 'Mina Terrestre',
  upgDesc_granada_mina: 'G planta uma mina no chão em vez de lançar. Arma em 1 s e explode quando um inimigo pisa perto. Some quando você renasce.',
  upg_granada_dupla: 'Dose Dupla',
  upgDesc_granada_dupla: 'Um G, duas granadas: lança uma e logo em seguida a outra, gastando uma carga só.',
  upg_granada_cinto: 'Cinto de Granadas da Tia',
  upgDesc_granada_cinto: 'Uma granada a mais por vida. A tia sempre carrega uma reserva.',
  upg_granada_polvora: 'Pólvora de São João',
  upgDesc_granada_polvora: 'Pólvora de fogos juninos: a explosão alcança 20% mais longe.',
  // What an upgrade changes, as chips in the Arsenal ({v}: "+15%", "+10", "2,6").
  fx_dano: 'Dano {v}',
  fx_alcance: 'Alcance {v}',
  fx_cadencia: 'Cadência {v}',
  fx_pente: 'Pente {v}',
  fx_recarga: 'Recarga {v}',
  fx_dispersao: 'Dispersão {v}',
  fx_mirando: 'Dispersão mirando {v}',
  fx_recuo: 'Recuo {v}',
  fx_adsTempo: 'Tempo de mira {v}',
  fx_zoom: 'Zoom {v}x',
  fx_movimento: 'Mobilidade {v}',
  fx_troca: 'Tempo de troca {v}',
  fx_silenciador: 'Tiro abafado',
  fx_golpe: 'Alcance do golpe {v} m',
  fx_investida: 'Investida {v} m',
  fx_intervalo: 'Intervalo entre golpes {v}',
  fx_impulso: 'Velocidade da investida {v}',
  fx_duracao: 'Duração do golpe {v}',
  fx_granadas: 'Granadas {v}',
  fx_recargaGranada: 'Volta da granada {v}',
  fx_raio: 'Raio da explosão {v}',
  fx_lancamento: 'Arremesso {v}',
  fx_tipo_mina: 'G planta uma mina',
  fx_tipo_dupla: 'G lança duas',
  // The Arsenal tree (client/ui/arsenal.ts): one row per slot.
  treeRow_primaria: 'Principal',
  treeRow_secundaria: 'Secundária',
  treeRow_faca: 'Faca',
  treeRow_granada: 'Granada',
  treeEquip: 'Equipar',
  treeEquipped: 'Equipada',
  treeWeaponLocked: 'faltam {xp} pts de {prog}',
  treeWeaponLockedLong: 'Trancada: libera com {total} pontos de {prog}. Faltam {xp}.',
  weaponUnlocked: '{weapon} liberada: equipe no Arsenal',
  arsenalSaveFailed: 'Não foi possível salvar o Arsenal',
  upgradeOn: 'Ligada',
  upgradeOff: 'Desligada',
  upgradeReplacedBy: 'Substituída por {upgrade}',
  upgradeOptional: 'Opcional: tem troca',
  upgradeUnlocked: '{weapon} nível {level}: {upgrade}!',
  upgradeTurnOn: 'Ligue no Arsenal',
  statDamage: 'Dano',
  statRate: 'Cadência',
  statAccuracy: 'Precisão',
  statRange: 'Alcance',
  statMobility: 'Mobilidade',
  statMag: 'Pente {mag} / reserva {reserve}',
  statSwingReach: 'Alcance do golpe',
  statLunge: 'Investida',
  statSwingSpeed: 'Rapidez',
  statStealth: 'Discrição',
  // The Arsenal canvas of the home (client/ui/arsenalCanvas.ts): a frame per slot, the panel, the zoom bar.
  arsenalCanvasHint: 'Arraste para navegar e use a roda do mouse para dar zoom. Clique numa arma para ver os detalhes dela.',
  arsenalCanvasHintTouch: 'Arraste para navegar e use dois dedos para dar zoom. Toque numa arma para ver os detalhes dela.',
  cvLegendLocked: 'Bloqueada',
  cvRow_primaria: 'Principal',
  cvRow_secundaria: 'Secundária',
  cvRow_faca: 'Corpo a corpo',
  cvRow_granada: 'Arremesso',
  cvSlot_primaria: 'Primária',
  cvSlot_secundaria: 'Secundária',
  cvSlot_faca: 'Corpo a corpo',
  cvSlot_granada: 'Arremesso',
  cvFrameEquipped: 'Equipada: {weapon}',
  cvUpgRow_mira: 'Miras',
  cvUpgRow_modo: 'Modo',
  cvUpgRow_resto: 'Melhorias',
  cvAlwaysEquipped: 'Sempre equipada',
  cvEquipSecondary: 'Levar como secundária',
  cvYourSecondary: 'Sua secundária',
  cvProgress: 'Progresso',
  cvUpgrades: 'Melhorias',
  cvOnCount: '{n} de {total} ligadas',
  cvOptional: 'Opcional',
  cvWeaponLocked: 'Arma bloqueada',
  cvUnlockWeaponFirst: 'Libere a arma primeiro',
  cvToggleOn: 'Ligada · toque para desligar',
  cvToggleOff: 'Desligada · toque para ligar',
  cvPickUpgrade: 'Clique numa melhoria da árvore para ver o que ela muda. O botão de cada uma liga ou desliga direto no canvas.',
  cvFitAll: 'Ver tudo',
  cvFitTitle: 'Ver tudo (0)',
  cvZoomIn: 'Aumentar zoom (+)',
  cvZoomOut: 'Diminuir zoom (−)',
  cvClose: 'Fechar (Esc)',
  keyWeapon1: 'Arma primária',
  keyWeapon2: 'Arma secundária',
  keySwapWeapon: 'Trocar de arma',
  touchSwap: 'Trocar de arma',
  dogBite: 'Mordida',
  backstab: 'Pelas costas',
  groin: 'No pássaro',
  groinBanner: 'NO PÁSSARO!',
  humiliation: 'Opressão',
  humiliatedBanner: 'OPRIMIDO!',
  danceName: 'Dancinha da Vitória',
  promptTaunt: 'Oprimir {name}',
  dancing: 'Oprimindo {name}…',
  quality: 'Qualidade gráfica',
  qualityAuto: 'Automática',
  objectDetail: 'Detalhe dos objetos',
  detailNormal: 'Normal',
  detailLight: 'Leve',
  spatialAudio: 'Som',
  spatialAuto: 'Automático',
  spatialHeadphones: 'Fone (3D)',
  spatialSpeakers: 'Caixa de som (estéreo)',
  qualityLow: 'Baixa',
  qualityMedium: 'Média',
  qualityHigh: 'Alta',
  touchFire: 'Atirar',
  touchAds: 'Mirar',
  touchJump: 'Pular',
  touchCrouch: 'Agachar',
  touchReload: 'Recarregar',
  touchMelee: 'Faca',
  touchGrenade: 'Granada',
  touchPause: 'Pausar',
  touchBoard: 'Placar',
  touchFullscreen: 'Tela cheia',
  touchSensitivity: 'Sensibilidade do toque',
  touchScale: 'Tamanho dos botões',
  touchOpacity: 'Opacidade dos botões',
  aimAssist: 'Assistência de mira',
  adsHold: 'Segurar para mirar (desligado: tocar alterna)',
  padSensitivity: 'Sensibilidade do controle',
  padLook: 'Mirar',
  padLeftStick: 'Analógico esquerdo',
  padRightStick: 'Analógico direito',
  fullscreenOnPlay: 'Tela cheia ao jogar',
  editLayout: 'Ajustar botões',
  editLayoutDone: 'Pronto',
  editLayoutReset: 'Posições padrão',
  editLayoutHint: 'Arraste os botões para onde preferir.',
  rotatePhone: 'Gire o celular para jogar',
  fullscreen: 'Tela cheia',
  iosFullscreen: 'Para tela cheia no iPhone: toque em Compartilhar e depois em "Adicionar à Tela de Início".',
  tapHint: 'Toque',
  touchControlsHelp: 'Arraste à esquerda para andar (até a borda corre) · arraste à direita para mirar · botões para atirar, mirar, pular, agachar, recarregar, faca e granada (segure para preparar).',
  yourName: 'Seu nome',
  sexLabel: 'Sexo',
  sexMale: '♂ Masculino',
  sexFemale: '♀ Feminino',
  playOnline: 'JOGAR ONLINE',
  playOffline: 'Campo de tiro (bonecos parados)',
  playBots: 'CONTRA BOTS',
  botSkill: 'Dificuldade',
  mapLabel: 'Mapa',
  botCount: 'Bots',
  skillEasy: 'Fácil',
  skillNormal: 'Normal',
  skillHard: 'Difícil',
  botsSubtitle: 'Contra {n} bots · {mode}',
  sessions: 'Sessões',
  createSession: 'CRIAR',
  sessionNamePlaceholder: 'Nome da nova sessão',
  back: 'Voltar',
  noSessions: 'Nenhuma sessão aberta. Crie a primeira!',
  join: 'ENTRAR',
  full: 'LOTADA',
  joining: 'Entrando…',
  connecting: 'Conectando ao servidor…',
  connectedAs: 'Conectado como {name}.',
  disconnected: 'Conexão com o servidor perdida.',
  serverOffline: 'Servidor fora do ar. Rode "bun run server" (ou jogue o treino offline).',
  needName: 'Escolha um nome primeiro.',
  exitToHome: 'Sair para o início',
  backToEditor: 'Voltar ao editor (Stop)',
  scoreboard: 'Placar',
  player: 'Jogador',
  deaths: 'Mortes',
  humiliationsShort: 'Opress.',
  killedBy: '{name} te eliminou',
  killedByWith: '{name} te eliminou com {weapon}',
  playerJoined: '{name} entrou',
  playerLeft: '{name} saiu',
  keyChat: 'Chat da sala',
  chatPlaceholder: 'Mensagem para a sala…',
  chatSend: 'Enviar',
  chatClose: 'Fechar o chat',
  chatHint: 'Enter envia · Esc fecha',
  chatMuted: 'Seu chat está silenciado pela moderação.',
  chatSlow: 'Calma! Espere um pouco para mandar outra.',
  touchChat: 'Chat',
  lostConnection: 'Sem conexão com o servidor',
  accountGuest: 'Sem conta: treino e bots estão liberados. Para jogar online, entre ou crie uma conta.',
  signIn: 'ENTRAR',
  signUp: 'CRIAR CONTA',
  profile: 'PERFIL',
  signOut: 'Sair da conta',
  email: 'E-mail',
  password: 'Senha',
  gameName: 'Nome no jogo',
  signInTitle: 'Entrar',
  signUpTitle: 'Criar conta',
  forgotTitle: 'Esqueci a senha',
  resetTitle: 'Nova senha',
  chooseNameTitle: 'Escolha seu nome no jogo',
  withDiscord: 'Entrar com Discord',
  forgotLink: 'Esqueci a senha',
  haveAccount: 'Já tenho conta',
  noAccount: 'Criar uma conta',
  send: 'ENVIAR',
  save: 'SALVAR',
  resetSent: 'Se esse e-mail tiver conta, enviamos um link válido por 24 horas.',
  resetDone: 'Senha trocada. Entre com a senha nova.',
  needAccount: 'Entre na sua conta para jogar online.',
  // Home: signed-in tabs
  tabPlay: 'JOGAR',
  tabArsenal: 'ARSENAL',
  tabAlbum: 'ÁLBUM',
  tabProfile: 'PERFIL',
  tabSettings: 'CONFIGURAÇÕES',
  customizeShort: 'PERSONALIZAR',
  equippedLine: '{icons} equipados',
  profileLine: '{kills} abates · {matches} partidas',
  modeTitle: 'Modo',
  modeOnline: 'Online',
  modeOnlineDesc: 'Mata-mata, corrida armada ou zumbi em equipe, com até 9 pessoas. Vale XP para a conta.',
  modeBots: 'Contra bots',
  modeBotsDesc: 'Você e 3 a 9 bots, do jeito que você escolher, ou sozinho contra a horda.',
  modeRange: 'Campo de tiro',
  modeRangeDesc: 'Bonecos de treino para testar a mira e as armas.',
  mapFilterTitle: 'Filtrar por mapa',
  mapFilterHint: 'Marque os mapas que quer ver',
  mapHintBots: 'Depois escolha dificuldade e bots',
  // Game modes (shared/modes.ts): gameMode_<id> and gameModeDesc_<id>.
  gameModeTitle: 'Tipo de partida',
  'gameMode_mata-mata': 'Mata-mata',
  'gameModeDesc_mata-mata': 'Todos contra todos com o seu Arsenal, escolhido antes de entrar.',
  'gameMode_corrida-armada': 'Corrida armada',
  'gameModeDesc_corrida-armada': '3 abates sobem de arma, facada tira um abate. Vence quem matar com o Sabre de Luz.',
  'gameMode_zumbi': 'Zumbi',
  'gameModeDesc_zumbi': 'Em equipe contra 12 ondas de zumbis e 3 chefes no Cemitério da Capela. Cada abate dá XP e dinheiro; gaste no Caixão Misterioso e em barricadas que decidem por onde a horda entra.',
  // Zumbi (shared/zombies.ts): zombies (ztype_<kind>), bosses (zboss_<id>), the coffin's items (zitem_<id>),
  // rarities (rar_<id>), the HUD, the coffin, revives and the end-of-match summary.
  ztype_comum: 'Zumbi',
  ztype_corredor: 'Maratonista',
  ztype_inchado: 'Tio do Churrasco',
  ztype_brutamontes: 'Segurança da Balada',
  ztype_cuspidor: 'Tia da Fofoca',
  zboss_coveiro: 'O Coveiro',
  zboss_noiva: 'A Noiva',
  zboss_prefeito: 'O Prefeito',
  zbossIntro_coveiro: 'O COVEIRO SAIU DA COVA!',
  zbossIntro_noiva: 'A NOIVA FOI DEIXADA NO ALTAR…',
  zbossIntro_prefeito: 'O PREFEITO QUER SEU VOTO!',
  zitem_riflePadrao: 'Rifle Padrão',
  zitem_pistolaInicial: 'Pistola do Porteiro',
  zitem_rifleMira: 'Rifle com Ponto Vermelho',
  zitem_rifleSilencioso: 'Rifle Silencioso',
  zitem_pistola: 'Pistola do Porteiro',
  zitem_pistolaBatata: 'Pistola da Batata',
  zitem_liquidificador: 'Liquidificador',
  zitem_grampeador: 'Grampeador do RH',
  zitem_revolver: 'Revólver do Delegado da Quadrilha',
  zitem_furadeira: 'Furadeira do Vizinho de Domingo',
  zitem_garrucha: 'Garrucha do Cangaceiro',
  zitem_pistolao: 'Pistolão do Marombeiro',
  zitem_rifleFirme: 'Rifle Firme',
  zitem_rifleVovo: 'Rifle do Vovô',
  zitem_pistolaLigeira: 'Pistola Ligeira',
  zitem_liquidificadorMotor: 'Liquidificador com Motor',
  zitem_rifleRemendado: 'Rifle Remendado',
  zitem_liquidificadorTurbo: 'Liquidificador Turbo',
  zitem_liquidificadorPipoca: 'Liquidificador Pipoqueiro',
  zitem_rifleCompleto: 'Rifle Completo',
  zitem_liquidificadorSupremo: 'Liquidificador Supremo',
  zitem_sabre: 'Sabre de Luz Paraguaio',
  rar_inicial: 'Inicial',
  rar_comum: 'Comum',
  rar_raro: 'Rara',
  rar_epico: 'Épica',
  rar_lendario: 'Lendária',
  zWave: 'ONDA {n}/{total}',
  zLeft: '{n} zumbis',
  zLeftOne: '1 zumbi',
  zCountdown: 'A HORDA VEM AÍ',
  zCountdownSub: 'em {s}s · ache o caixão!',
  zBreak: 'INTERVALO',
  zBreakSub: 'próxima onda em {s}s',
  zWaiting: 'Esperando jogadores',
  zOver: 'FIM DA PARTIDA',
  zWaveBanner: 'ONDA {n}',
  zLastWave: 'ÚLTIMA ONDA!',
  zBreakBanner: 'Onda {n} vencida! Munição e granadas cheias',
  zBossDown: '{boss} CAIU!',
  zAssist: 'Ajuda',
  zRevive: 'Reanimou',
  zWaveBonus: 'Onda vencida',
  zBossReward: 'Chefe derrotado',
  zBlast: 'Explosão',
  zBoxBuy: 'Caixão Misterioso: arma aleatória por ${cost}',
  zTotemBuy: 'Totem: acender a Vigília Sem Trégua por ${cost} (sem intervalo até o fim, +20% de dinheiro e +10% de XP)',
  zTotemPoor: 'Totem: Vigília Sem Trégua por ${cost} (você tem ${money})',
  zTotemLit: 'A Vigília Sem Trégua está acesa: sem intervalo até o fim da partida',
  zTotemOn: '{name} acendeu a Vigília Sem Trégua! Sem intervalo até o fim',
  zBoxPoor: 'Caixão Misterioso: ${cost} (você tem ${money})',
  zBoxSpinning: 'Girando…',
  zBoxTake: 'Pegar {item} ({rarity})',
  zBoxOther: '{name} está escolhendo a arma',
  zBoxDonateKey: '[{key}] doar',
  zBoxRefuseKey: '[{key}] recusar',
  zBoxTakeDonated: '{take} · doada por {name}',
  zBoxYouDonated: 'Você doou {item}: qualquer outro pode pegar',
  zBoxDonatedNotice: '{name} doou {item} ({rarity}) no caixão: quem quiser, pegue!',
  zBoxGot: 'Você pegou: {item} ({rarity})',
  zBoxTakeDamaged: 'Pegar {item} ({rarity}) · DANIFICADA: {flaw}',
  zBoxGotDamaged: 'Você pegou: {item} ({rarity}) · DANIFICADA',
  zBoxDamagedOffer: 'Saiu DANIFICADA: {flaw}',
  zDamaged: 'Danificada',
  zFlaw_municao: 'menos munição',
  zFlaw_dano: 'menos dano',
  zFlaw_ambos: 'menos munição e dano',
  zFlawAmmo: '−{p}% de pente e −{r}% de reserva',
  zFlawDamage: '−{d}% de dano',
  zgap_portao: 'Portão Principal',
  zgap_oeste: 'Brecha Oeste',
  zgap_leste: 'Brecha Leste',
  zgap_noroeste: 'Brecha Noroeste',
  zgap_nordeste: 'Brecha Nordeste',
  zBarBuild: 'Segure para erguer a barricada: {gap} (${cost})',
  zBarPoor: 'Barricada: ${cost} (você tem ${money})',
  zBarBuilding: 'Erguendo a barricada…',
  zBarRepair: 'Segure para pregar tábuas ({n}/{max})',
  zBarRepairing: 'Pregando tábuas ({n}/{max})…',
  zBarBlocked: 'Passagem ocupada: ninguém pode estar no vão',
  zBarNail: 'Tábua pregada',
  zBarBuilt: '{name} ergueu a barricada: {gap}',
  zBarBroken: 'Arrombaram a barricada: {gap}!',
  zRevivePrompt: 'Segure para reanimar {name}',
  zReviving: 'Reanimando {name}…',
  zBeingRevived: '{name} está te reanimando!',
  zDownTitle: 'CAÍDO!',
  zDownSub: 'Um amigo pode te reanimar · sangra em {s}s',
  zTeammateDown: '{name} caiu! Vá reanimar',
  zRevived: '{name} reanimou {who}',
  zBledOut: '{name} sangrou até morrer',
  zDeadWait: 'Você volta no intervalo (sem as armas do caixão)',
  zJoinWaitTitle: 'Onda em andamento',
  zJoinWait: 'Você entra quando esta onda acabar',
  zSpectating: 'ASSISTINDO',
  zProfaneYou: 'SACRILÉGIO! A horda inteira vem atrás de você',
  zProfaneHint: 'Ninguém sobe no altar: por {s} s, todo zumbi persegue você',
  zProfaned: '{name} profanou o altar e virou o alvo da horda por {s} s',
  zCrowsYou: 'CORVOS! Desça da árvore',
  zCrowsHint: 'Eles bicam enquanto você estiver na árvore e por mais {s} s',
  buffProfaned: 'Profanado',
  buffCrows: 'Corvos',
  buffCrowsUntil: 'na árvore e mais {s} s',
  zSpecHealth: '{hp} de vida',
  zSpecDown: 'Caído: precisa de ajuda!',
  zSpecKeys: '[{prev}] anterior · [{next}] próximo',
  zJump: 'PULE A ONDA!',
  zWon: 'SOBREVIVERAM À HORDA!',
  zLost: 'A HORDA VENCEU',
  zSumSub: 'Onda {wave} de {total} · {time}',
  zSumNext: 'Nova partida em {s}s…',
  zColKills: 'Abates',
  zColHead: 'Na cabeça',
  zColEarned: 'Dinheiro',
  zColDowns: 'Caiu',
  zColRevives: 'Reanimou',
  zColXp: 'XP',
  zColMoney: 'Dinheiro',
  zArsenalTitle: 'Caixão Misterioso',
  zArsenalCarry: 'Você carrega',
  zSolo: 'ENCARAR A HORDA SOZINHO',
  zMapOnly: 'Só no Cemitério da Capela',
  buffChilled: 'Arrepiado',
  buffVigil: 'Vigília Sem Trégua',
  buffBleeding: 'Sangrando',
  zThorns: 'Espinhos! Quem sobe na grade ou na sebe sangra.',
  zGhostsYou: 'A lápide não gostou!',
  zGhostsHint: '👻 Fantasmas atrás de você por {s} s: faca ou granada espantam',
  // Mata-mata: the loadout is locked once the match starts.
  upgradeNextMatch: 'Vale a partir da próxima partida',
  upgradeTurnOnNext: 'Ligue no Arsenal antes da próxima partida',
  // Corrida armada: the ladder (ids from shared/data/corrida_armada.json: ladder_<id>), HUD and rounds.
  ladderTitle: 'Escada da corrida armada',
  ladderHud: 'ARMA {n}/{total}',
  ladderStep: 'Degrau {n}',
  ladderFinalKills: 'abate final',
  ladderNext: 'Próxima arma: {weapon}!',
  ladderDown: 'Esfaqueado! Voltou para {weapon}',
  ladderLostKill: 'Esfaqueado! Perdeu um abate ({n}/{total})',
  ladderFinal: 'SABRE DE LUZ! Um abate com ele vence',
  ladder_rifleCompleto: 'Rifle Completo',
  ladder_smgTurbo: 'Liquidificador Turbo',
  ladder_rifleLuneta: 'Rifle com Luneta',
  ladder_rifleSilenciado: 'Rifle Silenciado',
  ladder_garrucha: 'Garrucha do Cangaceiro',
  ladder_grampeador: 'Grampeador do RH',
  ladder_pistolaRapida: 'Pistola Ligeira',
  ladder_pistolaBatata: 'Pistola da Batata',
  ladder_sabre: 'Sabre de Luz',
  roundWinner: '{name} venceu a corrida armada!',
  roundYouWon: 'VOCÊ VENCEU A CORRIDA ARMADA!',
  roundNext: 'Nova rodada em {s}…',
  roundStart: 'Nova rodada: todos de volta à primeira arma!',
  ladderShort: 'Arma',
  mapHintRange: 'Clique num mapa e o treino começa na hora',
  sessionsOne: '1 sessão',
  sessionsMany: '{n} sessões',
  quickJoinHint: 'Entra direto na sessão mais cheia dos mapas filtrados',
  openSessions: 'Sessões abertas ({n})',
  moreSessions: 'VER MAIS ({n})',
  noSessionsFiltered: 'Nenhuma sessão aberta nos mapas selecionados.',
  pickAMap: 'Marque pelo menos um mapa.',
  versusBots: 'CONTRA {n} BOTS',
  // Home: landing (signed out)
  navGame: 'O jogo',
  navMaps: 'Mapas',
  navModes: 'Modos',
  navAccount: 'Criar conta',
  heroText: 'Tiroteio de bairro direto no navegador. Mira precisa, armas absurdas e uma dancinha da vitória em cima de quem caiu.',
  startPlaying: 'COMEÇAR A JOGAR',
  heroNote: 'Sem conta: treino e bots estão liberados. PC, celular e controle.',
  aboutTitle: 'Como é o jogo',
  aboutSub: 'Levado a sério na mecânica. Nem um pouco a sério no tom.',
  pillarAimKicker: 'MIRA',
  pillarAimTitle: 'Tiro que respeita a mira',
  pillarAimDesc: 'Dispersão, recuo e dano por região do corpo. Na cabeça dói mais. No pássaro, dói de outro jeito.',
  pillarTauntKicker: 'OPRESSÃO',
  pillarTauntTitle: 'Dancinha vale 150',
  pillarTauntDesc: 'Abate rende 100 pontos. Dançar em cima de quem caiu rende 150. A provocação é parte do jogo.',
  pillarArsenalKicker: 'ARSENAL',
  pillarArsenalTitle: 'Armas que evoluem',
  pillarArsenalDesc: 'Cada abate evolui a arma que matou e libera armas novas: da faca de cozinha ao sabre de luz, do rifle padrão ao Dourado Ostentação.',
  mapsTitle: 'Mapas',
  mapsSub: 'Três vizinhanças, cada uma com suas piadas e segredos.',
  mapRuaWhen: 'Dia ensolarado',
  mapRuaGag: 'Subúrbio com piscina vazia, caminhão de sorvete e flamingos. Cuidado com a Amora: a mordida é letal.',
  mapJardimWhen: 'Noite com lanternas',
  mapJardimGag: 'Jardim oriental iluminado por lanternas. Tem carpas nos lagos e uma cereja que dá mais vida por 30 s.',
  mapHalloweenWhen: 'Lua cheia',
  mapHalloweenGag: 'Cemitério, mansão, parque de diversões e esgoto. Uma bruxa dá poções de efeito aleatório e um rato gigante mora lá embaixo.',
  mapCemiterioWhen: 'Noite de neblina',
  mapCemiterioGag: 'O cemitério murado do modo zumbi: a horda sobe das covas lá fora e só entra pelas cinco brechas do muro. Pregue tábuas nas brechas e escolha por onde ela vem.',
  modesTitle: 'Modos de jogo',
  tagAccount: 'COM CONTA',
  tagNoAccount: 'SEM CONTA',
  landOnlineDesc: 'Mata-mata (todos contra todos, com o seu Arsenal), corrida armada ou zumbi (ondas em equipe), com chat e placar com nível e ping.',
  landOnlineFacts: 'Até 10 jogadores|Salas por mapa|Pontua o arsenal',
  landBotsDesc: 'As mesmas regras, contra bots com nomes como Capitão Lag e Recruta 404.',
  landBotsFacts: '3, 5, 7 ou 9 bots|Fácil · Normal · Difícil|2 s de proteção ao nascer',
  landRangeDesc: 'Bonecos de treino no mapa escolhido, alguns patrulhando. Para acertar a mira sem ninguém olhando.',
  landRangeFacts: 'Sem adversários|Qualquer mapa|Renasce em 3 s',
  accountWhy: 'Para jogar online, salvar a evolução das armas e montar seu personagem.',
  startTitle: 'Começar a jogar',
  startGuest: 'Sem cadastro, agora mesmo. Você entra como {name}.',
  passwordHint: 'De 8 a 128 caracteres.',
  nameHint: 'De 3 a 16 letras ou números. Aparece como Nome#1234.',
  levelShort: 'Nv {level}',
  accountLevelUp: '🏅 Conta nível {level}!',
  sessionEnded: 'Sua sessão foi encerrada (saída da conta, troca de senha, exclusão ou suspensão).',
  connectedElsewhere: 'Sua conta entrou no jogo em outro lugar.',
  profileTitle: 'Perfil',
  statsTitle: 'Estatísticas',
  recentTitle: 'Últimas participações',
  noParticipations: 'Nenhuma partida online ainda.',
  statKills: 'Abates',
  statDeaths: 'Mortes',
  statHead: 'Na cabeça',
  statGroin: 'No pássaro',
  statKnife: 'Facadas',
  statBackstab: 'Pelas costas',
  statGrenade: 'Com granada',
  statHumiliations: 'Opressões',
  statTime: 'Tempo jogado',
  statMatches: 'Participações',
  zstatsTitle: 'Modo zumbi',
  zstatMatches: 'Partidas',
  zstatWins: 'Vitórias',
  zstatBestWave: 'Melhor onda',
  zstatWaves: 'Ondas sobrevividas',
  zstatKills: 'Zumbis abatidos',
  zstatDowns: 'Quedas',
  zstatRevives: 'Reanimações',
  zstatCoffin: 'Giros no caixão',
  albumTitle: 'Álbum de figurinhas',
  albumHint: 'Cada meta é um acabamento a mais, até a Dourada. Só vale o que você faz online.',
  albumCount: '{stuck} de {total} figurinhas · {finishes} de {finishesTotal} acabamentos',
  albumDone: 'Completa!',
  albumRepeats: 'Repetidas: ×{n}',
  finishNone: 'Ainda não colada',
  finishComum: 'Comum',
  finishBrilhante: 'Brilhante',
  finishHolografica: 'Holográfica',
  finishDourada: 'Dourada',
  stickerUp: '{icon} Figurinha {finish}: {name}!',
  stickerSecret: '🔓 Figurinha secreta descoberta: {icon} {name}!',
  albumHidden: 'Figurinha secreta',
  albumShowcase: 'Em destaque',
  albumNoShowcase: 'Nenhuma: escolha uma figurinha colada',
  albumTitleLabel: 'Título',
  albumNoTitle: 'Sem título',
  albumFeature: 'Usar como destaque',
  albumUnfeature: 'Tirar do destaque',
  albumTitlesSummary: 'Títulos: {got} de {total}',
  albumTitlesHint: 'Cada página dá um título quando todas as figurinhas dela estão Holográficas ou Douradas. O título e a figurinha em destaque aparecem para os outros no placar e quando você os abate.',
  errStickerLocked: 'Você ainda não tem essa figurinha ou esse título.',
  customize: 'PERSONALIZAR PERSONAGEM',
  changeName: 'Trocar nome',
  nameFreeAt: 'Próxima troca liberada em {date}.',
  nameRule: 'A primeira troca é livre; depois, uma a cada 7 dias.',
  linkDiscord: 'Vincular Discord',
  unlinkDiscord: 'Desvincular Discord',
  discordLinked: 'Discord vinculado.',
  deleteAccount: 'Excluir conta',
  deleteConfirm: 'Excluir a conta? Você tem 30 dias para desistir entrando de novo. Depois disso, nome e e-mail são apagados.',
  cancelDeletion: 'Cancelar exclusão',
  deletionPending: 'Conta marcada para exclusão em {date}. O jogo online fica bloqueado até você cancelar.',
  saved: 'Salvo.',
  errCredentials: 'E-mail ou senha incorretos.',
  errTooMany: 'Muitas tentativas. Espere um minuto e tente de novo.',
  errSuspended: 'Esta conta está suspensa.',
  errPendingDeletion: 'Esta conta está marcada para exclusão. Cancele no Perfil para jogar online.',
  errEmailUsed: 'Esse e-mail já tem conta. Entre ou use "Esqueci a senha".',
  errEmailInvalid: 'E-mail inválido.',
  errPasswordInvalid: 'A senha precisa ter de 8 a 128 caracteres.',
  errNameInvalid: 'Nome inválido: de 3 a 16 letras ou números.',
  errNameTaken: 'Esse nome não tem mais números livres. Tente outro.',
  errNameCooldown: 'Você só pode trocar de nome de novo em {date}.',
  errTokenInvalid: 'Link inválido ou vencido. Peça outro em "Esqueci a senha".',
  errOnlyLogin: 'O Discord é a única forma de entrar nesta conta.',
  errDiscordUnavailable: 'Entrar com Discord não está disponível neste endereço.',
  errDiscordLinked: 'Esse Discord já está vinculado a uma conta.',
  errUnauthorized: 'Entre na sua conta de novo.',
  errOffline: 'Servidor fora do ar. Rode "bun run dev:online" (ou jogue o treino offline).',
  errGeneric: 'Algo deu errado. Tente de novo.',
  onlineSubtitle: 'Sessão: {name} · {mode}',
  // Mapas and Gerenciamento tabs (PF-6: client/ui/maps.ts, client/ui/management.ts).
  tabMaps: 'MAPAS',
  tabManagement: 'GERENCIAMENTO',
  mapsOfficial: 'Oficiais',
  mapsCommunity: 'Comunidade',
  mapsNew: '+ Novo mapa',
  mapsSearch: 'Buscar…',
  mapsSearchBy: 'Buscar por',
  mapsByName: 'Nome',
  mapsByAuthor: 'Autor',
  mapsOrder: 'Ordem',
  mapsOrderPlayed: 'Mais jogados',
  mapsOrderRecent: 'Mais recentes',
  mapsShowHidden: 'Mostrar ocultos',
  mapsEmpty: 'Nenhum mapa encontrado.',
  mapsMore: 'Ver mais',
  mapsPlays: '{n} jogadas',
  mapsPlaysOne: '1 jogada',
  mapsVersion: 'versão {v}',
  mapsBy: 'por {autor}',
  mapsOfficialBy: 'Mapa oficial',
  mapsCommunitySub: 'Mapa da comunidade',
  mapsZombieOnly: 'Só zumbi',
  mapsHiddenTag: 'Oculto',
  mapsHiddenWhy: 'Oculto: {motivo}',
  mapsPlay: 'Jogar',
  mapsBots: 'Contra bots',
  mapsRange: 'Campo de tiro',
  mapsEdit: 'Editar',
  mapsDuplicate: 'Duplicar',
  mapsDelete: 'Excluir',
  mapsHide: 'Ocultar',
  mapsUnhide: 'Desocultar',
  mapsVersions: 'Versões',
  mapsCancel: 'Cancelar',
  mapsClose: 'Fechar',
  mapsDeleteConfirm: 'Excluir "{nome}"? Ele sai das listas e não abre mais partidas (as partidas em andamento terminam nele).',
  mapsHideReason: 'Motivo (opcional)',
  mapsHideConfirm: 'Ocultar "{nome}" das listas? Só o autor e a equipe continuam vendo.',
  mapsVersionsTitle: 'Versões salvas',
  mapsRestore: 'Restaurar',
  mapsCurrent: 'atual',
  mapsRestored: 'Versão {v} restaurada: as partidas novas usam ela.',
  mapsDuplicated: 'Cópia de "{nome}" criada em Comunidade.',
  mapsDeleted: 'Mapa excluído.',
  mapsHidden: 'Mapa ocultado.',
  mapsUnhidden: 'O mapa voltou às listas.',
  mapsLoading: 'Carregando…',
  mgTitle: 'Gerenciamento',
  mgHint: 'Busque uma conta pelo nome ou pela tag (Nome#1234).',
  mgSearch: 'Nome ou Nome#1234',
  mgFind: 'Buscar',
  mgOpen: 'Abrir',
  mgEmpty: 'Nenhuma conta encontrada.',
  mgBanned: 'Banida',
  mgMuted: 'Silenciada',
  mgSuspended: 'Suspensa',
  mgPendingDeletion: 'Em exclusão',
  mgRole_admin: 'Admin',
  mgRole_moderador: 'Moderador',
  mgPlayer: 'Jogador',
  mgReadOnly: 'Você não pode mexer nesta conta: um moderador não age sobre um admin.',
  mgSanctions: 'Sanções',
  mgNoPunish: 'Você não pode punir esta conta.',
  mgBan: 'Banir',
  mgMute: 'Silenciar',
  mgReason: 'Motivo',
  mgDuration: 'Duração',
  mgDur_1h: '1 hora',
  mgDur_12h: '12 horas',
  mgDur_1d: '1 dia',
  mgDur_7d: '7 dias',
  mgDur_30d: '30 dias',
  mgDur_permanente: 'Permanente',
  mgApply: 'Aplicar',
  mgUnban: 'Retirar banimento',
  mgUnmute: 'Retirar silêncio',
  mgHistory: 'Histórico',
  mgNoSanctions: 'Sem sanções.',
  mgSanction_banimento: 'Banimento',
  mgSanction_silencio: 'Silêncio',
  mgUntil: 'até {data}',
  mgForever: 'sem fim',
  mgRevoked: 'retirada em {data}',
  mgBy: 'por {tag}',
  mgNeedReason: 'Escreva o motivo.',
  mgName: 'Nome',
  mgNameHint: 'Troca na hora, sem a espera de 7 dias; a espera do jogador recomeça.',
  mgLook: 'Aparência',
  mgEditLook: 'Editar aparência',
  mgProgress: 'Progresso',
  mgAccountXp: 'XP da conta (nível {n})',
  mgWeaponXp: 'XP das armas',
  mgSaveProgress: 'Salvar progresso',
  mgBadNumber: 'Use números inteiros de 0 a 1.000.000.000.',
  mgRoles: 'Papéis',
  mgPromote: 'Promover a {papel}',
  mgDemote: 'Tirar {papel}',
  mgRolesNone: 'Você não pode mudar os papéis desta conta.',
  mgDone: 'Feito.',
  errNoPermission: 'Você não tem permissão para isso.',
  errNotFound: 'Não encontrado.',
  errBadInput: 'Dados inválidos.',
  errLastAdmin: 'O último admin não pode ser removido.',
  errProtectedMap: 'Os quatro mapas oficiais originais não podem ser apagados nem ocultados.',
  // Pause menu (client/ui/menu.ts, client/ui/pauseMenu.ts): the rail (where we are, the banner, the exit), the
  // mode's tab and the settings' tab in the panel, and the exit's confirmation. Same texts on the start card.
  pmLineSession: 'Sessão: {name} · {n}/{max} jogadores',
  pmLineBots: 'Contra {n} bots · {skill}',
  // {wave}: pmLineWave, or before the first wave the HUD's countdown title (zCountdown).
  pmLineWave: 'Onda {n}/{total}',
  pmLineWaveTeam: '{wave} · {players} jogadores',
  pmLineWaveAlone: '{wave} · 1 jogador',
  pmLineWaveSolo: '{wave} · sozinho',
  pmLineRange: 'Treino offline com os bonecos',
  pmPreview: 'Prévia: {file}',
  pmLiveOnline: 'Online: o jogo continua e você pode levar tiro.',
  pmLiveHorde: 'Online: a horda não espera. Sua equipe continua lutando.',
  pmPausedBots: 'Jogo pausado: os bots esperam você.',
  pmPaused: 'Jogo pausado.',
  pmExitSession: 'Sair da sessão',
  pmExitMatch: 'Sair da partida',
  pmExitRace: 'Sair da corrida',
  pmExitRange: 'Sair do treino',
  pmConfirmSession: 'Você sai da sessão {name} e volta para a tela inicial. Os pontos que suas armas já ganharam ficam na conta.',
  pmConfirmBots: 'A partida contra os bots acaba e você volta para a tela inicial.',
  pmConfirmRace: 'Você sai da corrida e perde o degrau em que está. Volta para a tela inicial.',
  pmConfirmRaceBots: 'A corrida contra os bots acaba e você volta para a tela inicial.',
  pmConfirmZombieTeam: 'Sua equipe continua sem você. O dinheiro desta partida não é guardado.',
  pmConfirmZombieAlone: 'A partida recomeça para o próximo que entrar. O dinheiro desta partida não é guardado.',
  pmConfirmZombieSolo: 'A partida acaba e o dinheiro não fica.',
  pmConfirmRange: 'Você sai do campo de tiro e volta para a tela inicial.',
  pmConfirmEditor: 'O jogo para e você volta ao editor, no ponto em que estava.',
  pmStay: 'FICAR',
  pmLeave: 'SAIR',
  pmStayHint: 'fica na partida',
  pmClose: 'Fechar',
  pmBack: 'Voltar',
  pmHintResume: 'Voltar ao jogo',
  pmHintBack: 'Voltar',
  pmHintPick: 'Escolher',
  pmBadgeReadOnly: '🔒 Só consulta',
  pmBadgeEditable: 'Editável no treino',
  pmArsenalSubReadOnly: 'Seu equipamento · só consulta',
  pmArsenalSubEditable: 'Troque armas e melhorias',
  pmArsenalHintReadOnly: 'O que você levou para esta partida.',
  pmArsenalHintEditable: 'O campo de tiro deixa trocar tudo, valendo na hora.',
  pmArsenalFootReadOnly: 'Travado durante a partida. Troque armas e melhorias no Arsenal da tela inicial: as mudanças valem a partir da próxima partida.',
  pmArsenalFootEditable: 'No campo de tiro o Arsenal é editável e as mudanças valem na hora.',
  pmArsenalFootGuest: 'Crie uma conta para suas armas evoluírem',
  pmUpgradesUnlocked: 'Melhorias liberadas',
  pmNoUpgrades: 'Nenhuma melhoria liberada ainda',
  pmMoreUpgrades: '🔒 Mais {n} melhorias a liberar. Próxima: {upgrade}, faltam {xp} pts de {prog}.',
  pmMoreUpgrade: '🔒 Mais 1 melhoria a liberar: {upgrade}, faltam {xp} pts de {prog}.',
  pmNextMatch: 'Vale na próxima partida',
  pmWeaponsUnlocked: 'Armas liberadas',
  pmTabLadder: 'Escada',
  pmTabLadderSub: 'Degrau {n} de {total} · {k}/{need} abates',
  pmLadderHint: 'Todos usam as mesmas armas, com os mesmos atributos.',
  pmLadderYou: 'Você · {k}/{need}',
  pmLadderNow: 'Agora · degrau {n}',
  pmLadderNext: 'Próxima · degrau {n}',
  pmLadderToGo: 'faltam {n} abates para subir',
  pmLadderToGoOne: 'falta 1 abate para subir',
  pmLadderToWin: 'faltam {n} abates para vencer',
  pmLadderToWinOne: 'falta 1 abate para vencer',
  pmLadderGun: '{mag} balas · {rpm} rpm',
  pmLadderSilenced: 'tiro abafado',
  pmLadderFinal: 'Abate final',
  pmLadderFinalOne: 'Um abate com o {weapon} vence a rodada',
  pmLadderFinalMany: '{n} abates com o {weapon} vencem a rodada',
  pmRuleClimb: '{n} abates com a arma da vez ou com a faca sobem um degrau.',
  pmRuleStab: 'Morrer por facada tira um abate. Sem abates no degrau, volta uma arma.',
  pmRuleFinalOne: 'No último degrau, um abate com o {weapon} vence a rodada.',
  pmRuleFinalMany: 'No último degrau, {n} abates com o {weapon} vencem a rodada.',
  pmLeader: 'Na frente',
  pmLeaderOther: '{name} · degrau {n} ({weapon})',
  pmLeaderYou: 'Você está na frente',
  pmTabCoffin: 'Caixão',
  pmTabCoffinSub: 'O que você carrega e as chances',
  pmCoffinHintOnline: '${cost} por arma, sorteada no servidor. A raridade multiplica o dano contra zumbis.',
  pmCoffinHintSolo: '${cost} por arma. A raridade multiplica o dano contra zumbis.',
  pmCoffinFoot: 'A arma nova substitui a do mesmo tipo (rifle, secundária ou faca). Danificada não tem conserto: só outra rodada.',
  pmCoffinOdds: 'Chances · ${cost}',
  pmCoffinMul: '×{m} de dano',
  pmCoffinBroken: '{n}% vem danificada',
  pmConfigSub: 'Mira, vídeo, áudio e teclas',
  pmConfigHint: 'Tudo vale na hora.',
  pmSubAim: 'Mira',
  pmSubVideo: 'Vídeo',
  pmSubAudio: 'Áudio',
  pmSubKeys: 'Teclas',
  pmSubPad: 'Controle',
  pmSubTouch: 'Toque',
  pmDescSens: 'Mouse, sem mirar',
  pmDescAds: 'Multiplica a sensibilidade enquanto mira',
  pmDescPadSens: 'Analógico direito',
  pmDescAssist: 'A mira desacelera sobre um inimigo, sem puxar de longe',
  pmDescInvert: 'Mover para cima olha para baixo',
  pmDescFov: 'Maior vê mais dos lados',
  pmDescQuality: 'Automática ajusta sozinha para manter o FPS',
  pmDescDetail: 'Leve simplifica árvores, folhagem e enfeites (vale a partir da próxima partida)',
  pmDescFullscreen: 'Em tela cheia, Esc abre e fecha o menu na hora',
  pmDescVolume: 'Volume geral do jogo',
  pmDescSpatial: 'Automático: 3D no PC, estéreo no celular',
  pmOn: 'Ligado',
  pmOff: 'Desligado',
  keyGroupMove: 'Movimento',
  keyGroupCombat: 'Combate',
  keyGroupOther: 'Outros',
  pmKeyPress: 'Pressione…',
  pmEscFixed: 'abre o menu (fixa)',
  pmPadNote: 'Layout fixo do controle (estilo CoD). As teclas do teclado são remapeáveis.',
  gpuWarning:
    'Seu navegador está desenhando o jogo sem placa de vídeo (renderizador: {gpu}), por isso fica em ~10 FPS. Ative “Usar aceleração gráfica quando disponível” em chrome://settings/system (no Edge: edge://settings/system) e reinicie o navegador.',
  // Galpão (client/ui/galpao): the 3D home's menu, stations, signs, Arsenal board and launch.
  gpQuick: 'ENTRADA RÁPIDA',
  gpQuickLine: '{mode} · Online · {maps}',
  gpNoMapMarked: 'nenhum mapa marcado',
  gpBack: '‹ GALPÃO',
  gpLaunching: 'ENTRANDO NA PARTIDA',
  gpLaunchOnline: '{map} · {mode} · {n}/{max} jogadores',
  gpLaunchBots: 'Contra {n} bots · {map}',
  gpLaunchHorde: 'Sozinho contra a horda · {map}',
  gpLaunchRange: 'Treino offline · {map}',
  gpSt_play: 'Jogar',
  gpSt_maps: 'Mapas',
  gpSt_arsenal: 'Arsenal',
  gpSt_album: 'Álbum',
  gpSt_profile: 'Perfil',
  gpSt_settings: 'Configurações',
  gpSt_admin: 'Gerenciamento',
  gpStSub_play: 'Online, contra bots ou campo de tiro',
  gpStSub_maps: 'Oficiais e da comunidade: jogue, duplique ou crie',
  gpStSub_arsenal: 'Armas, melhorias e equipamento',
  gpStSub_album: 'Figurinhas, títulos e destaque',
  gpStSub_profile: 'Conta, estatísticas e personagem',
  gpStSub_settings: 'Mira, vídeo, áudio e teclas',
  gpStSub_admin: 'Moderação · só para a equipe',
  gpHint_play: 'Escolha o modo, o tipo de partida e o mapa. O botão laranja começa.',
  gpHint_maps: 'Jogue um mapa, duplique um para editar ou crie um do zero.',
  gpHint_arsenal: 'Arraste para navegar, roda do mouse para zoom. Clique numa arma para ver os detalhes. Verde: equipada · vermelha: bloqueada.',
  gpHint_arsenalTouch: 'Arraste para navegar, pinça para zoom. Toque numa arma para ver os detalhes. Verde: equipada · vermelha: bloqueada.',
  gpHint_album: 'Clique numa figurinha para ver como colar. As abas viram as páginas.',
  gpHint_profile: 'Sua ficha: estatísticas, últimas partidas e as opções da conta.',
  gpHint_settings: 'Escolha uma seção no alto do quadro. As mudanças valem na hora.',
  gpHint_admin: 'Busque a conta, confira a situação e escolha uma ação. Nada muda sem você confirmar.',
  gpSign_play: '01 · OPERAÇÕES',
  gpSign_maps: '02 · MAPAS',
  gpSign_arsenal: '03 · ARSENAL',
  gpSign_profile: '05 · VESTIÁRIO',
  gpSign_settings: '06 · OFICINA',
  gpSign_admin: '07 · SEGURANÇA',
  gpBoard_primaria: 'PRIMÁRIA',
  gpBoard_secundaria: 'SECUNDÁRIA',
  gpBoard_faca: 'FACA',
  gpBoard_granada: 'GRANADA',
  gpAdminScreen: 'GERENCIAMENTO',
  gpAdminScreenSub: 'ACESSO RESTRITO · EQUIPE',
  gpDanger: 'PERIGO',
  gpHighVoltage: 'ALTA TENSÃO',
  gpExit: 'SAÍDA',
  gpAlbumCover1: 'OFFENSIVE COMBAT · ÁLBUM OFICIAL',
  gpAlbumCover2: 'FIGURI',
  gpAlbumCover3: 'NHAS',
  gpAlbumCover4: '{n} FIGURINHAS',
  gpTagLevel: 'NV{level}',
  gpTagLocked: 'BLOQ.',
  gpTagOn: 'ON',
  gpTagOff: 'OFF',
  gpLockedChip: 'BLOQUEADA',
  gpSharesProg: 'Usa os pontos e as melhorias de {prog}',
  gpAutoOn: 'Liga sozinha ao liberar',
  gpUpgradesOf: 'MELHORIAS DE {prog}',
  gpPlayHintOnline: 'Escolha o tipo de partida e os mapas. A lista mostra as sessões abertas agora.',
  gpPlayHintBots: 'Partida offline contra bots, com o seu Arsenal e as melhorias da conta.',
  gpPlayHintRange: 'Clique num mapa (ou no botão laranja) para abrir o campo de tiro com os bonecos.',
  gpCtaLine: '{mode} · {map}',
  gpRangeTargets: 'Bonecos parados',
} as const;

const en: Record<keyof typeof ptBR, string> = {
  title: 'OFFENSIVE COMBAT',
  subtitle: 'Shooting prototype · Phase 1',
  play: 'PLAY',
  resume: 'BACK TO THE GAME',
  aimOnNextKey: 'Aim comes back with your next key or click',
  loading: 'Loading',
  settings: 'Settings',
  sensitivity: 'Sensitivity',
  adsSensitivity: 'ADS sensitivity',
  fov: 'Field of view',
  volume: 'Volume',
  invertY: 'Invert Y axis',
  health: 'HEALTH',
  reload: 'RELOAD',
  noAmmo: 'NO AMMO',
  reloading: 'RELOADING…',
  points: 'Points',
  kills: 'Kills',
  accuracy: 'Accuracy',
  you: 'You',
  kill: 'Kill',
  headshot: 'Headshot',
  longShot: 'Long shot',
  respawnIn: 'Respawning in {s}…',
  debugHint: 'F3 debug · F4 hitboxes and colliders (characters → characters + assets → off)',
  debugViewChars: 'F4: character hitboxes',
  debugViewAll: 'F4: characters + map colliders',
  debugViewOff: 'F4: visual debug off',
  keyMove: 'Move',
  keyJump: 'Jump',
  keyCrouch: 'Crouch (while sprinting: slide)',
  keySprint: 'Sprint',
  keyFire: 'Fire',
  keyAds: 'Aim',
  keyReload: 'Reload',
  keyPause: 'Menu',
  mouseLeft: 'Left mouse',
  mouseRight: 'Right mouse',
  keyMelee: 'Knife',
  keyTaunt: 'Humiliate (near a body)',
  keyDonate: 'Donate the coffin weapon (zombies)',
  keyRefuse: 'Turn down the coffin weapon (zombies)',
  keyGrenade: 'Grenade (hold to cook)',
  keyForward: 'Move forward',
  keyBack: 'Move back',
  keyLeft: 'Strafe left',
  keyRight: 'Strafe right',
  keyScoreboard: 'Scoreboard',
  keyPrimary: 'Primary',
  keyAlternate: 'Alternate',
  keyPress: 'Press a key… (Esc cancels)',
  keyClear: 'Remove the key',
  keyUnbound: 'No key',
  keyMoved: '{key} was on "{action}", which lost its {slot} key.',
  keyNoCtrl: "Ctrl can't be used: Ctrl+W closes the browser tab.",
  keyFixed: '{key} is reserved for debugging.',
  keyWheelHold: "The mouse wheel can't be held: use it for jump, fire, reload, knife, grenade, humiliate or switching weapons.",
  keysReset: 'Restore default keys',
  grenadeName: 'Grenade',
  knife: 'Knifed',
  knifeName: 'Knife',
  mineLimit: 'At most {n} mines on the map',
  cherryTaken: '🍒 Dragon Cherry: +{n} max health for {s} s',
  cherryOver: 'The cherry wore off',
  koiXp: '🐟 Fish down: +{n} XP',
  goldenKoiXp: '✨ Golden carp: +{n} XP',
  goldenKoi: '✨ Golden carp! Sharp aim for {s} s',
  goldenKoiOver: "The golden carp's sharp aim wore off",
  galleryAim: '🎯 Every target down! Sharp aim for {s} s',
  humanityTaken: '🕯️ Humanity gained: +{n} max health until you die',
  biscuitTaken: '🦴 Scooby Snack! Full health. Scooby-Dooby-Doo!',
  promptPotion: 'Drink Potion',
  potion_pato: '🦆 Duck grenades until you die!',
  potion_veloz: '💨 Haste potion: faster for {s} s',
  potion_lerdo: '🐌 Sluggish potion: slower for {s} s',
  potion_critico: '💀 Critical potion: every shot is a critical for {s} s',
  potion_bebado: "🍺 Drunk potion: crooked aim for {s} s",
  potionOver: 'The potion wore off',
  galleryAimOver: "The shooting gallery's sharp aim wore off",
  buffKoi: 'Carp aim',
  buffGallery: 'Sharp aim',
  buffCherry: 'Extra health',
  buffHumanity: 'Humanity',
  buffDuck: 'Duck grenades',
  buffVeloz: 'Haste',
  buffLerdo: 'Sluggish',
  buffCritico: 'Critical shots',
  buffBebado: 'Drunk',
  buffUntilDeath: 'until death',
  buffUntilMatchEnd: 'until the match ends',
  arsenal: 'Arsenal',
  level: 'Level',
  locked: 'Locked',
  xpToNext: '{xp} more points to level {level}',
  maxLevel: 'Max level! {xp} points',
  unlockShort: '{xp} pts to go',
  arma_rifle: 'Standard Rifle',
  armaDesc_rifle: 'The usual. Iron sights and faith. Good up close, good at range, great at nothing.',
  arma_pistola: "The Doorman's Pistol",
  armaDesc_pistola: "Twelve rounds and all of the building manager's authority. Semi-auto: one click, one shot. Quick out of the holster.",
  arma_smg: 'Blender SMG',
  armaDesc_smg: 'Goes brrrr and blends everything. Spits lead up close, cries at range. Lighter: you run faster with it.',
  arma_grampeador: 'HR Stapler',
  armaDesc_grampeador: 'Chk-chk-chk: three staples per click, straight to the memo. Good up close and mid-range, but it jams on the paper between bursts.',
  arma_revolver: "Square Dance Sheriff's Revolver",
  armaDesc_revolver: "From the square-dance shotgun wedding: the sheriff makes the groom say yes with it. Six rounds that hit hard, but the cylinder turns slowly and reloading takes forever.",
  arma_furadeira: "Neighbor's Sunday Drill",
  armaDesc_furadeira: "8 a.m. on a Sunday: brrrrrrr. Drills through everything in a blink and wakes the whole street, but the bit wobbles and won't reach past the gate.",
  arma_garrucha: "Cangaceiro's Double-Barrel",
  armaDesc_garrucha: "Two barrels, a leather hat and zero patience. Point-blank it settles things in one shot; at range it's a drizzle of pellets that only tickles. Two shots and it snaps open to reload.",
  arma_pistolao: "Gym Bro's Hand Cannon",
  armaDesc_pistolao: "Skipped leg day for this. Hits like a rifle and one headshot settles it, but the kick throws your aim at the ceiling, it's heavy and seven rounds go fast.",
  arma_faca: 'Kitchen Knife',
  armaDesc_faca: 'Borrowed from the kitchen and never returned. One hit, one kill.',
  arma_granada: 'Frag Grenade',
  armaDesc_granada: 'Goes off on first contact. Cook it too long and it goes off in your hand.',
  arma_rifleFita: 'Duct-Taped Rifle',
  armaDesc_rifleFita: 'Half silver tape, half courage. Quick to reload, but the tape is loose and it kicks harder.',
  arma_rifleTia: "Auntie's WhatsApp Rifle",
  armaDesc_rifleTia: 'Pink, with a flower sticker. Good morning! Fires faster and aims in a flash, but each bullet hits a bit softer.',
  arma_rifleNatal: 'Christmas Lights Rifle',
  armaDesc_rifleNatal: 'Wrapped in fairy lights. Much gentler kick, but fairy lights are in no hurry: it fires slower.',
  arma_rifleChama: 'Flame Decal Rifle',
  armaDesc_rifleChama: 'Flame decals give +10 speed, everybody knows. Fires faster and you run faster, but the bullets spread.',
  arma_rifleVovo: "Grandpa's Rifle",
  armaDesc_rifleVovo: 'Varnished wood, from when rifles were built to last. Hits hard, but slow to fire and to aim.',
  arma_rifleOuro: 'Bling Gold Rifle',
  armaDesc_rifleOuro: 'Solid gold and a 40-round mag. Matches nothing, and that is the point. Heavy: you walk and reload slower.',
  arma_colher: "Grandma's Wooden Spoon",
  armaDesc_colher: 'Anyone who has been hit with one knows: it is lethal. A bit more reach, slightly slower swings.',
  arma_frango: 'Rubber Chicken',
  armaDesc_frango: 'Squeeze it and it screams. A much longer lunge, but everyone hears the scream from afar.',
  arma_baguete: 'Stale Baguette',
  armaDesc_baguete: "Yesterday's. Crunchy outside, deadly inside. More reach, slower swings.",
  arma_peixe: 'Frozen Fish',
  armaDesc_peixe: 'Straight out of the freezer. A long lunge, but the icy slap takes a while.',
  arma_macarrao: 'Pool Noodle',
  armaDesc_macarrao: '60 centimeters of foam. Looks harmless. It is not. Long reach, but slow, with a short lunge.',
  arma_sabre: 'Knock-off Lightsaber',
  armaDesc_sabre: 'Bought at a street market. The longest reach of all and it goes vwoom (everyone hears it). Weak batteries: more time between swings.',
  prog_rifle: 'rifle',
  prog_pistola: 'pistol',
  prog_smg: 'SMG',
  prog_faca: 'knife',
  prog_granada: 'grenade',
  upg_rifle_pontoVermelho: 'Flea Market Red Dot',
  upgDesc_rifle_pontoVermelho: 'Bought from a street stall, but the dot does light up. Steadier aim and a bit of zoom.',
  upg_rifle_empunhadura: 'Broomstick Foregrip',
  upgDesc_rifle_empunhadura: 'A broomstick zip-tied under the barrel. Tames the kick and tightens the spread.',
  upg_rifle_luneta: "Grandpa's Scope (3x)",
  upgDesc_rifle_luneta: "The brass scope grandpa used to spy on the neighbors. 3x zoom and long-range precision, but aiming is slow and the gun gets heavy. Replaces the red dot.",
  upg_rifle_pente: 'Duct-Taped Double Mag',
  upgDesc_rifle_pente: 'Two mags taped together: ten more rounds and faster reloads.',
  upg_rifle_silenciador: 'Soda Bottle Silencer',
  upgDesc_rifle_silenciador: 'A 2-liter bottle on the barrel. Only those nearby hear the shot and nobody sees a tracer. In exchange, less damage and range.',
  upg_rifle_holoLupa: 'Holo with Magnifier (1.5x)',
  upgDesc_rifle_holoLupa: 'The smiley holo with a flip magnifier behind it. 1.5x zoom and a steadier aim; a touch slower to aim.',
  upg_rifle_luneta2x: '2x Scope',
  upgDesc_rifle_luneta2x: 'A short brass scope. 2x zoom and more range; aims slower and weighs a little.',
  upg_rifle_luneta4x: '4x Scope',
  upgDesc_rifle_luneta4x: 'The long scope from the shop window. 4x zoom and a lot of range; aiming takes a while and the rifle gets heavy.',
  upg_pistola_gatilho: 'Arcade Trigger',
  upgDesc_pistola_gatilho: 'Ripped out of an arcade cabinet: you can click a lot faster.',
  upg_pistola_pontoVermelho: 'Mini Red Dot',
  upgDesc_pistola_pontoVermelho: 'Tiny, but honest. Much more precise when aiming.',
  upg_pistola_coldre: 'Velcro Holster',
  upgDesc_pistola_coldre: 'Out of the holster in half the time, and the mag swaps faster too.',
  upg_pistola_batata: 'Potato Silencer',
  upgDesc_pistola_batata: 'A potato on the muzzle. Works in movies, works here: muffled shots, no tracer and less kick. But a little less damage.',
  upg_smg_motor: 'Turbo Blender Motor',
  upgDesc_smg_motor: 'Blender speed 5: more rounds per second.',
  upg_smg_holo: "Auntie's Smiley Holo Sight",
  upgDesc_smg_holo: 'A smiley face floating in the sight. Good morning! More precise aimed and from the hip.',
  upg_smg_tambor: 'Popcorn Drum Mag',
  upgDesc_smg_tambor: 'Eighteen more rounds in a popcorn-maker drum. In exchange, reloading and switching take longer and you walk a bit slower.',
  upg_smg_coronha: 'Garden Hose Stock',
  upgDesc_smg_coronha: 'A garden hose coiled against the shoulder. Less recoil and less spread.',
  upg_faca_afiador: 'Street Fair Sharpener',
  upgDesc_faca_afiador: 'The guy at the street fair sharpened it for free. Faster follow-up swings and a bit more reach.',
  upg_faca_tenis: 'Spring Sneakers',
  upgDesc_faca_tenis: 'Sneakers with springs in the soles: the lunge goes farther and faster.',
  upg_faca_maoLeve: 'Light Hand',
  upgDesc_faca_maoLeve: 'A quick swing, no fuss: it ends sooner and your gun is ready to fire earlier.',
  passiva_discreta: 'Discreet',
  passivaDesc_discreta: 'The swing is only heard up close.',
  passiva_coloDeVo: "Grandma's Lap",
  passivaDesc_coloDeVo: 'Each kill with it gives back {vida} health.',
  passiva_fugaEscandalosa: 'Screaming Getaway',
  passivaDesc_fugaEscandalosa: 'After a kill with it, you run {pct}% faster for {s} s.',
  passiva_lanche: 'Snack Break',
  passivaDesc_lanche: 'Each kill with it fills the magazine of the gun in your hand.',
  passiva_tapaGelado: 'Frozen Slap',
  passivaDesc_tapaGelado: 'A stab in the back is worth +{pts} pts instead of +{base}.',
  passiva_boia: 'Pool Float',
  passivaDesc_boia: 'While it is equipped, you take no fall damage.',
  passiva_vuuum: 'Vwoom',
  passivaDesc_vuuum: 'The swing hits everyone in reach and in front of you, not just one.',
  knifePassive: 'Passive: {name}',
  knifePassiveWhere: 'Works in free-for-all, on the training range and against bots.',
  passiveFx_coloDeVo: "🥄 Grandma's lap: +{vida} health",
  passiveFx_fugaEscandalosa: '🐔 Screaming getaway!',
  passiveFx_lanche: '🥖 Snack break: magazine full',
  upg_granada_mina: 'Land Mine',
  upgDesc_granada_mina: 'G plants a mine on the ground instead of throwing. Arms in 1 s and blows up when an enemy steps close. Gone when you respawn.',
  upg_granada_dupla: 'Double Dose',
  upgDesc_granada_dupla: 'One G, two grenades: throws one and right after it another, for a single charge.',
  upg_granada_cinto: "Auntie's Grenade Belt",
  upgDesc_granada_cinto: 'One more grenade per life. Auntie always carries a spare.',
  upg_granada_polvora: 'Festival Gunpowder',
  upgDesc_granada_polvora: 'Fireworks gunpowder: the blast reaches 20% farther.',
  fx_dano: 'Damage {v}',
  fx_alcance: 'Range {v}',
  fx_cadencia: 'Fire rate {v}',
  fx_pente: 'Magazine {v}',
  fx_recarga: 'Reload {v}',
  fx_dispersao: 'Spread {v}',
  fx_mirando: 'Aimed spread {v}',
  fx_recuo: 'Recoil {v}',
  fx_adsTempo: 'Aim time {v}',
  fx_zoom: 'Zoom {v}x',
  fx_movimento: 'Mobility {v}',
  fx_troca: 'Draw time {v}',
  fx_silenciador: 'Muffled shots',
  fx_golpe: 'Hit reach {v} m',
  fx_investida: 'Lunge {v} m',
  fx_intervalo: 'Time between swings {v}',
  fx_impulso: 'Lunge speed {v}',
  fx_duracao: 'Swing duration {v}',
  fx_granadas: 'Grenades {v}',
  fx_recargaGranada: 'Grenade recharge {v}',
  fx_raio: 'Blast radius {v}',
  fx_lancamento: 'Throw {v}',
  fx_tipo_mina: 'G plants a mine',
  fx_tipo_dupla: 'G throws two',
  treeRow_primaria: 'Primary',
  treeRow_secundaria: 'Secondary',
  treeRow_faca: 'Knife',
  treeRow_granada: 'Grenade',
  treeEquip: 'Equip',
  treeEquipped: 'Equipped',
  treeWeaponLocked: '{xp} {prog} pts to go',
  treeWeaponLockedLong: 'Locked: unlocks at {total} {prog} points. {xp} to go.',
  weaponUnlocked: '{weapon} unlocked: equip it in the Arsenal',
  arsenalSaveFailed: 'Could not save the Arsenal',
  upgradeOn: 'On',
  upgradeOff: 'Off',
  upgradeReplacedBy: 'Replaced by {upgrade}',
  upgradeOptional: 'Optional: has a trade-off',
  upgradeUnlocked: '{weapon} level {level}: {upgrade}!',
  upgradeTurnOn: 'Turn it on in the Arsenal',
  statDamage: 'Damage',
  statRate: 'Fire rate',
  statAccuracy: 'Accuracy',
  statRange: 'Range',
  statMobility: 'Mobility',
  statMag: 'Magazine {mag} / reserve {reserve}',
  statSwingReach: 'Swing reach',
  statLunge: 'Lunge',
  statSwingSpeed: 'Speed',
  statStealth: 'Stealth',
  arsenalCanvasHint: 'Drag to move around and use the mouse wheel to zoom. Click a weapon to see its details.',
  arsenalCanvasHintTouch: 'Drag to move around and pinch with two fingers to zoom. Tap a weapon to see its details.',
  cvLegendLocked: 'Locked',
  cvRow_primaria: 'Primary',
  cvRow_secundaria: 'Secondary',
  cvRow_faca: 'Melee',
  cvRow_granada: 'Throwable',
  cvSlot_primaria: 'Primary',
  cvSlot_secundaria: 'Secondary',
  cvSlot_faca: 'Melee',
  cvSlot_granada: 'Throwable',
  cvFrameEquipped: 'Equipped: {weapon}',
  cvUpgRow_mira: 'Sights',
  cvUpgRow_modo: 'Mode',
  cvUpgRow_resto: 'Upgrades',
  cvAlwaysEquipped: 'Always equipped',
  cvEquipSecondary: 'Take as secondary',
  cvYourSecondary: 'Your secondary',
  cvProgress: 'Progress',
  cvUpgrades: 'Upgrades',
  cvOnCount: '{n} of {total} on',
  cvOptional: 'Optional',
  cvWeaponLocked: 'Weapon locked',
  cvUnlockWeaponFirst: 'Unlock the weapon first',
  cvToggleOn: 'On · tap to turn off',
  cvToggleOff: 'Off · tap to turn on',
  cvPickUpgrade: 'Click an upgrade in the tree to see what it changes. Each one has a button that turns it on or off right on the canvas.',
  cvFitAll: 'Show all',
  cvFitTitle: 'Show all (0)',
  cvZoomIn: 'Zoom in (+)',
  cvZoomOut: 'Zoom out (−)',
  cvClose: 'Close (Esc)',
  keyWeapon1: 'Primary weapon',
  keyWeapon2: 'Secondary weapon',
  keySwapWeapon: 'Switch weapon',
  touchSwap: 'Switch weapon',
  dogBite: 'Bite',
  backstab: 'Backstab',
  groin: 'Right in the birdie',
  groinBanner: 'RIGHT IN THE BIRDIE!',
  humiliation: 'Humiliation',
  humiliatedBanner: 'HUMILIATED!',
  danceName: 'Victory Dance',
  promptTaunt: 'Humiliate {name}',
  dancing: 'Humiliating {name}…',
  quality: 'Graphics quality',
  qualityAuto: 'Automatic',
  objectDetail: 'Object detail',
  detailNormal: 'Normal',
  detailLight: 'Light',
  spatialAudio: 'Sound',
  spatialAuto: 'Automatic',
  spatialHeadphones: 'Headphones (3D)',
  spatialSpeakers: 'Speakers (stereo)',
  qualityLow: 'Low',
  qualityMedium: 'Medium',
  qualityHigh: 'High',
  touchFire: 'Fire',
  touchAds: 'Aim',
  touchJump: 'Jump',
  touchCrouch: 'Crouch',
  touchReload: 'Reload',
  touchMelee: 'Knife',
  touchGrenade: 'Grenade',
  touchPause: 'Pause',
  touchBoard: 'Scoreboard',
  touchFullscreen: 'Fullscreen',
  touchSensitivity: 'Touch sensitivity',
  touchScale: 'Button size',
  touchOpacity: 'Button opacity',
  aimAssist: 'Aim assist',
  adsHold: 'Hold to aim (off: tap toggles)',
  padSensitivity: 'Controller sensitivity',
  padLook: 'Look',
  padLeftStick: 'Left stick',
  padRightStick: 'Right stick',
  fullscreenOnPlay: 'Fullscreen when playing',
  editLayout: 'Arrange buttons',
  editLayoutDone: 'Done',
  editLayoutReset: 'Default positions',
  editLayoutHint: 'Drag the buttons wherever you like.',
  rotatePhone: 'Turn your phone sideways to play',
  fullscreen: 'Fullscreen',
  iosFullscreen: 'For fullscreen on iPhone: tap Share, then "Add to Home Screen".',
  tapHint: 'Tap',
  touchControlsHelp: 'Drag on the left to move (to the edge to sprint) · drag on the right to look · buttons to fire, aim, jump, crouch, reload, knife and grenade (hold to cook).',
  yourName: 'Your name',
  sexLabel: 'Sex',
  sexMale: '♂ Male',
  sexFemale: '♀ Female',
  playOnline: 'PLAY ONLINE',
  playOffline: 'Shooting range (static dummies)',
  playBots: 'VS BOTS',
  botSkill: 'Difficulty',
  mapLabel: 'Map',
  botCount: 'Bots',
  skillEasy: 'Easy',
  skillNormal: 'Normal',
  skillHard: 'Hard',
  botsSubtitle: 'Against {n} bots · {mode}',
  sessions: 'Sessions',
  createSession: 'CREATE',
  sessionNamePlaceholder: 'New session name',
  back: 'Back',
  noSessions: 'No open sessions. Create the first one!',
  join: 'JOIN',
  full: 'FULL',
  joining: 'Joining…',
  connecting: 'Connecting to the server…',
  connectedAs: 'Connected as {name}.',
  disconnected: 'Lost connection to the server.',
  serverOffline: 'Server is down. Run "bun run server" (or play offline training).',
  needName: 'Pick a name first.',
  exitToHome: 'Back to home',
  backToEditor: 'Back to the editor (Stop)',
  scoreboard: 'Scoreboard',
  player: 'Player',
  deaths: 'Deaths',
  humiliationsShort: 'Humil.',
  killedBy: '{name} took you out',
  killedByWith: '{name} took you out with {weapon}',
  playerJoined: '{name} joined',
  playerLeft: '{name} left',
  keyChat: 'Room chat',
  chatPlaceholder: 'Message the room…',
  chatSend: 'Send',
  chatClose: 'Close chat',
  chatHint: 'Enter sends · Esc closes',
  chatMuted: 'Your chat was muted by the moderators.',
  chatSlow: 'Easy! Wait a little before sending another.',
  touchChat: 'Chat',
  lostConnection: 'No connection to the server',
  accountGuest: 'No account: training and bots are open. To play online, sign in or create an account.',
  signIn: 'SIGN IN',
  signUp: 'SIGN UP',
  profile: 'PROFILE',
  signOut: 'Sign out',
  email: 'E-mail',
  password: 'Password',
  gameName: 'In-game name',
  signInTitle: 'Sign in',
  signUpTitle: 'Create account',
  forgotTitle: 'Forgot password',
  resetTitle: 'New password',
  chooseNameTitle: 'Choose your in-game name',
  withDiscord: 'Sign in with Discord',
  forgotLink: 'Forgot password',
  haveAccount: 'I have an account',
  noAccount: 'Create an account',
  send: 'SEND',
  save: 'SAVE',
  resetSent: 'If that e-mail has an account, we sent a link valid for 24 hours.',
  resetDone: 'Password changed. Sign in with the new one.',
  needAccount: 'Sign in to play online.',
  tabPlay: 'PLAY',
  tabArsenal: 'ARSENAL',
  tabAlbum: 'ALBUM',
  tabProfile: 'PROFILE',
  tabSettings: 'SETTINGS',
  customizeShort: 'CUSTOMIZE',
  equippedLine: '{icons} equipped',
  profileLine: '{kills} kills · {matches} matches',
  modeTitle: 'Mode',
  modeOnline: 'Online',
  modeOnlineDesc: 'Deathmatch, gun game or team zombies, with up to 9 people. Earns account XP.',
  modeBots: 'Vs bots',
  modeBotsDesc: 'You and 3 to 9 bots, your way, or alone against the horde.',
  modeRange: 'Shooting range',
  modeRangeDesc: 'Training dummies to test your aim and weapons.',
  mapFilterTitle: 'Filter by map',
  mapFilterHint: 'Tick the maps you want to see',
  mapHintBots: 'Then pick difficulty and bots',
  gameModeTitle: 'Match type',
  'gameMode_mata-mata': 'Deathmatch',
  'gameModeDesc_mata-mata': 'Everyone against everyone with your Arsenal, picked before you join.',
  'gameMode_corrida-armada': 'Gun game',
  'gameModeDesc_corrida-armada': '3 kills move you up a weapon, a stab takes a kill away. A lightsaber kill wins.',
  'gameMode_zumbi': 'Zombies',
  'gameModeDesc_zumbi': 'Team up against 12 waves of zombies and 3 bosses in the Chapel Cemetery. Every kill gives XP and money; spend it at the Mystery Coffin and on barricades that decide where the horde gets in.',
  ztype_comum: 'Zombie',
  ztype_corredor: 'Jogger',
  ztype_inchado: 'BBQ Uncle',
  ztype_brutamontes: 'Club Bouncer',
  ztype_cuspidor: 'Gossip Aunt',
  zboss_coveiro: 'The Gravedigger',
  zboss_noiva: 'The Bride',
  zboss_prefeito: 'The Mayor',
  zbossIntro_coveiro: 'THE GRAVEDIGGER CLIMBED OUT!',
  zbossIntro_noiva: 'THE BRIDE WAS LEFT AT THE ALTAR…',
  zbossIntro_prefeito: 'THE MAYOR WANTS YOUR VOTE!',
  zitem_riflePadrao: 'Standard Rifle',
  zitem_pistolaInicial: "Doorman's Pistol",
  zitem_rifleMira: 'Red Dot Rifle',
  zitem_rifleSilencioso: 'Hush Rifle',
  zitem_pistola: "Doorman's Pistol",
  zitem_pistolaBatata: 'Potato Pistol',
  zitem_liquidificador: 'Blender',
  zitem_grampeador: 'HR Stapler',
  zitem_revolver: "Square Dance Sheriff's Revolver",
  zitem_furadeira: "Neighbor's Sunday Drill",
  zitem_garrucha: "Cangaceiro's Double-Barrel",
  zitem_pistolao: "Gym Bro's Hand Cannon",
  zitem_rifleFirme: 'Steady Rifle',
  zitem_rifleVovo: "Grandpa's Rifle",
  zitem_pistolaLigeira: 'Quick Pistol',
  zitem_liquidificadorMotor: 'Motor Blender',
  zitem_rifleRemendado: 'Taped-Up Rifle',
  zitem_liquidificadorTurbo: 'Turbo Blender',
  zitem_liquidificadorPipoca: 'Popcorn Blender',
  zitem_rifleCompleto: 'Full Rifle',
  zitem_liquidificadorSupremo: 'Supreme Blender',
  zitem_sabre: 'Knockoff Lightsaber',
  rar_inicial: 'Starter',
  rar_comum: 'Common',
  rar_raro: 'Rare',
  rar_epico: 'Epic',
  rar_lendario: 'Legendary',
  zWave: 'WAVE {n}/{total}',
  zLeft: '{n} zombies',
  zLeftOne: '1 zombie',
  zCountdown: 'THE HORDE IS COMING',
  zCountdownSub: 'in {s}s · find the coffin!',
  zBreak: 'BREAK',
  zBreakSub: 'next wave in {s}s',
  zWaiting: 'Waiting for players',
  zOver: 'MATCH OVER',
  zWaveBanner: 'WAVE {n}',
  zLastWave: 'LAST WAVE!',
  zBreakBanner: 'Wave {n} cleared! Ammo and grenades refilled',
  zBossDown: '{boss} IS DOWN!',
  zAssist: 'Assist',
  zRevive: 'Revive',
  zWaveBonus: 'Wave cleared',
  zBossReward: 'Boss defeated',
  zBlast: 'Blast',
  zBoxBuy: 'Mystery Coffin: random weapon for ${cost}',
  zTotemBuy: 'Totem: light the Relentless Vigil for ${cost} (no breaks till the end, +20% money and +10% XP)',
  zTotemPoor: 'Totem: Relentless Vigil for ${cost} (you have ${money})',
  zTotemLit: 'The Relentless Vigil is lit: no breaks till the match ends',
  zTotemOn: '{name} lit the Relentless Vigil! No breaks till the end',
  zBoxPoor: 'Mystery Coffin: ${cost} (you have ${money})',
  zBoxSpinning: 'Spinning…',
  zBoxTake: 'Take {item} ({rarity})',
  zBoxOther: '{name} is choosing a weapon',
  zBoxDonateKey: '[{key}] donate',
  zBoxRefuseKey: '[{key}] turn down',
  zBoxTakeDonated: '{take} · donated by {name}',
  zBoxYouDonated: 'You donated {item}: anyone else can take it',
  zBoxDonatedNotice: '{name} left {item} ({rarity}) in the coffin: grab it!',
  zBoxGot: 'You got: {item} ({rarity})',
  zBoxTakeDamaged: 'Take {item} ({rarity}) · DAMAGED: {flaw}',
  zBoxGotDamaged: 'You got: {item} ({rarity}) · DAMAGED',
  zBoxDamagedOffer: 'It came out DAMAGED: {flaw}',
  zDamaged: 'Damaged',
  zFlaw_municao: 'less ammo',
  zFlaw_dano: 'less damage',
  zFlaw_ambos: 'less ammo and damage',
  zFlawAmmo: '−{p}% magazine and −{r}% reserve',
  zFlawDamage: '−{d}% damage',
  zgap_portao: 'Main Gate',
  zgap_oeste: 'West Gap',
  zgap_leste: 'East Gap',
  zgap_noroeste: 'Northwest Gap',
  zgap_nordeste: 'Northeast Gap',
  zBarBuild: 'Hold to build the barricade: {gap} (${cost})',
  zBarPoor: 'Barricade: ${cost} (you have ${money})',
  zBarBuilding: 'Building the barricade…',
  zBarRepair: 'Hold to nail boards ({n}/{max})',
  zBarRepairing: 'Nailing boards ({n}/{max})…',
  zBarBlocked: 'Gap in use: nobody can stand in it',
  zBarNail: 'Board nailed',
  zBarBuilt: '{name} built the barricade: {gap}',
  zBarBroken: 'The barricade broke: {gap}!',
  zRevivePrompt: 'Hold to revive {name}',
  zReviving: 'Reviving {name}…',
  zBeingRevived: '{name} is reviving you!',
  zDownTitle: 'DOWN!',
  zDownSub: 'A friend can revive you · bleeding out in {s}s',
  zTeammateDown: '{name} is down! Go revive them',
  zRevived: '{name} revived {who}',
  zBledOut: '{name} bled out',
  zDeadWait: "You're back at the break (without the coffin's weapons)",
  zJoinWaitTitle: 'Wave in progress',
  zJoinWait: 'You join when this wave ends',
  zSpectating: 'WATCHING',
  zProfaneYou: 'SACRILEGE! The whole horde is coming for you',
  zProfaneHint: 'Nobody climbs the altar: for {s} s, every zombie hunts you',
  zProfaned: '{name} profaned the altar and is the horde\'s target for {s} s',
  zCrowsYou: 'CROWS! Get down from the tree',
  zCrowsHint: 'They peck while you stay in the tree and {s} s after',
  buffProfaned: 'Profaned',
  buffCrows: 'Crows',
  buffCrowsUntil: 'up the tree and {s} s after',
  zSpecHealth: '{hp} health',
  zSpecDown: 'Down: needs help!',
  zSpecKeys: '[{prev}] previous · [{next}] next',
  zJump: 'JUMP THE WAVE!',
  zWon: 'YOU SURVIVED THE HORDE!',
  zLost: 'THE HORDE WON',
  zSumSub: 'Wave {wave} of {total} · {time}',
  zSumNext: 'New match in {s}s…',
  zColKills: 'Kills',
  zColHead: 'Headshots',
  zColEarned: 'Money',
  zColDowns: 'Downs',
  zColRevives: 'Revives',
  zColXp: 'XP',
  zColMoney: 'Money',
  zArsenalTitle: 'Mystery Coffin',
  zArsenalCarry: 'You carry',
  zSolo: 'FACE THE HORDE ALONE',
  zMapOnly: 'Chapel Cemetery only',
  buffChilled: 'Chilled',
  buffVigil: 'Relentless Vigil',
  buffBleeding: 'Bleeding',
  zThorns: 'Thorns! Climbing the bars or the hedge makes you bleed.',
  zGhostsYou: 'The grave took offense!',
  zGhostsHint: '👻 Ghosts are after you for {s} s: a knife or a grenade scares them',
  upgradeNextMatch: 'Takes effect from your next match',
  upgradeTurnOnNext: 'Turn it on in the Arsenal before your next match',
  ladderTitle: 'Gun game ladder',
  ladderHud: 'WEAPON {n}/{total}',
  ladderStep: 'Step {n}',
  ladderFinalKills: 'final kill',
  ladderNext: 'Next weapon: {weapon}!',
  ladderDown: 'Stabbed! Back to {weapon}',
  ladderLostKill: 'Stabbed! Lost a kill ({n}/{total})',
  ladderFinal: 'LIGHTSABER! One kill with it wins',
  ladder_rifleCompleto: 'Full Rifle',
  ladder_smgTurbo: 'Turbo Blender',
  ladder_rifleLuneta: 'Scoped Rifle',
  ladder_rifleSilenciado: 'Silenced Rifle',
  ladder_garrucha: "Cangaceiro's Double-Barrel",
  ladder_grampeador: 'HR Stapler',
  ladder_pistolaRapida: 'Quick Pistol',
  ladder_pistolaBatata: 'Potato Pistol',
  ladder_sabre: 'Lightsaber',
  roundWinner: '{name} won the gun game!',
  roundYouWon: 'YOU WON THE GUN GAME!',
  roundNext: 'New round in {s}…',
  roundStart: 'New round: everyone back to the first weapon!',
  ladderShort: 'Weapon',
  mapHintRange: 'Click a map and training starts right away',
  sessionsOne: '1 session',
  sessionsMany: '{n} sessions',
  quickJoinHint: 'Jumps into the fullest session of the filtered maps',
  openSessions: 'Open sessions ({n})',
  moreSessions: 'SHOW MORE ({n})',
  noSessionsFiltered: 'No open sessions on the selected maps.',
  pickAMap: 'Tick at least one map.',
  versusBots: 'VS {n} BOTS',
  navGame: 'The game',
  navMaps: 'Maps',
  navModes: 'Modes',
  navAccount: 'Sign up',
  heroText: 'Neighborhood shootouts right in the browser. Sharp aim, absurd weapons and a victory dance over whoever fell.',
  startPlaying: 'START PLAYING',
  heroNote: 'No account: training and bots are open. PC, phone and controller.',
  aboutTitle: 'What the game is like',
  aboutSub: 'Serious about the mechanics. Not serious at all about the tone.',
  pillarAimKicker: 'AIM',
  pillarAimTitle: 'Shooting that respects aim',
  pillarAimDesc: 'Spread, recoil and damage per body region. Headshots hurt more. The birdie hurts differently.',
  pillarTauntKicker: 'TAUNT',
  pillarTauntTitle: 'A dance is worth 150',
  pillarTauntDesc: 'A kill is worth 100 points. Dancing over whoever fell is worth 150. Taunting is part of the game.',
  pillarArsenalKicker: 'ARSENAL',
  pillarArsenalTitle: 'Weapons that evolve',
  pillarArsenalDesc: 'Each kill levels up the weapon that made it and unlocks new ones: from the kitchen knife to the lightsaber, from the standard rifle to Bling Gold.',
  mapsTitle: 'Maps',
  mapsSub: 'Three neighborhoods, each with its own jokes and secrets.',
  mapRuaWhen: 'Sunny day',
  mapRuaGag: 'Suburb with an empty pool, an ice cream truck and flamingos. Watch out for Amora: her bite is lethal.',
  mapJardimWhen: 'Lantern-lit night',
  mapJardimGag: 'Oriental garden lit by lanterns. Koi in the ponds and a cherry that gives extra health for 30 s.',
  mapHalloweenWhen: 'Full moon',
  mapHalloweenGag: 'Cemetery, mansion, amusement park and sewer. A witch hands out random potions and a giant rat lives down below.',
  mapCemiterioWhen: 'Foggy night',
  mapCemiterioGag: "The zombie mode's walled cemetery: the horde rises from the graves outside and only gets in through the five gaps in the wall. Nail boards over the gaps and pick where it comes from.",
  modesTitle: 'Game modes',
  tagAccount: 'ACCOUNT',
  tagNoAccount: 'NO ACCOUNT',
  landOnlineDesc: 'Deathmatch (everyone against everyone, with your Arsenal), gun game or zombies (team waves), with chat and a scoreboard with level and ping.',
  landOnlineFacts: 'Up to 10 players|Rooms per map|Levels the arsenal',
  landBotsDesc: 'Same rules, against bots with names like Capitão Lag and Recruta 404.',
  landBotsFacts: '3, 5, 7 or 9 bots|Easy · Normal · Hard|2 s spawn protection',
  landRangeDesc: 'Training dummies on the chosen map, some on patrol. To fix your aim with nobody watching.',
  landRangeFacts: 'No opponents|Any map|Respawn in 3 s',
  accountWhy: 'To play online, keep your weapons’ progress and build your character.',
  startTitle: 'Start playing',
  startGuest: 'No sign-up, right now. You play as {name}.',
  passwordHint: '8 to 128 characters.',
  nameHint: '3 to 16 letters or numbers. Shown as Name#1234.',
  levelShort: 'Lv {level}',
  accountLevelUp: '🏅 Account level {level}!',
  sessionEnded: 'Your session ended (sign-out, password change, deletion or suspension).',
  connectedElsewhere: 'Your account joined the game somewhere else.',
  profileTitle: 'Profile',
  statsTitle: 'Stats',
  recentTitle: 'Recent sessions',
  noParticipations: 'No online matches yet.',
  statKills: 'Kills',
  statDeaths: 'Deaths',
  statHead: 'Headshots',
  statGroin: 'Below the belt',
  statKnife: 'Knife kills',
  statBackstab: 'Backstabs',
  statGrenade: 'Grenade kills',
  statHumiliations: 'Humiliations',
  statTime: 'Time played',
  statMatches: 'Sessions',
  zstatsTitle: 'Zombie mode',
  zstatMatches: 'Matches',
  zstatWins: 'Wins',
  zstatBestWave: 'Best wave',
  zstatWaves: 'Waves survived',
  zstatKills: 'Zombies killed',
  zstatDowns: 'Downs',
  zstatRevives: 'Revives',
  zstatCoffin: 'Coffin spins',
  albumTitle: 'Sticker album',
  albumHint: 'Every target is one more finish, up to Gold. Only what you do online counts.',
  albumCount: '{stuck} of {total} stickers · {finishes} of {finishesTotal} finishes',
  albumDone: 'Complete!',
  albumRepeats: 'Repeats: ×{n}',
  finishNone: 'Not stuck in yet',
  finishComum: 'Common',
  finishBrilhante: 'Shiny',
  finishHolografica: 'Holographic',
  finishDourada: 'Gold',
  stickerUp: '{icon} {finish} sticker: {name}!',
  stickerSecret: '🔓 Secret sticker found: {icon} {name}!',
  albumHidden: 'Secret sticker',
  albumShowcase: 'Showcased',
  albumNoShowcase: 'None: pick a sticker you have',
  albumTitleLabel: 'Title',
  albumNoTitle: 'No title',
  albumFeature: 'Showcase it',
  albumUnfeature: 'Remove from showcase',
  albumTitlesSummary: 'Titles: {got} of {total}',
  albumTitlesHint: 'Each page gives a title once all its stickers are Holographic or Gold. Your title and showcased sticker show on the scoreboard and to the players you kill.',
  errStickerLocked: "You don't have that sticker or title yet.",
  customize: 'CUSTOMIZE CHARACTER',
  changeName: 'Change name',
  nameFreeAt: 'Next change available on {date}.',
  nameRule: 'The first change is free; then one every 7 days.',
  linkDiscord: 'Link Discord',
  unlinkDiscord: 'Unlink Discord',
  discordLinked: 'Discord linked.',
  deleteAccount: 'Delete account',
  deleteConfirm: 'Delete the account? You have 30 days to change your mind by signing in again. After that, name and e-mail are erased.',
  cancelDeletion: 'Cancel deletion',
  deletionPending: 'Account scheduled for deletion on {date}. Online play is blocked until you cancel.',
  saved: 'Saved.',
  errCredentials: 'Wrong e-mail or password.',
  errTooMany: 'Too many attempts. Wait a minute and try again.',
  errSuspended: 'This account is suspended.',
  errPendingDeletion: 'This account is scheduled for deletion. Cancel it in Profile to play online.',
  errEmailUsed: 'That e-mail already has an account. Sign in or use "Forgot password".',
  errEmailInvalid: 'Invalid e-mail.',
  errPasswordInvalid: 'The password needs 8 to 128 characters.',
  errNameInvalid: 'Invalid name: 3 to 16 letters or numbers.',
  errNameTaken: 'That name has no free numbers left. Try another.',
  errNameCooldown: 'You can change your name again on {date}.',
  errTokenInvalid: 'Invalid or expired link. Ask for another in "Forgot password".',
  errOnlyLogin: 'Discord is the only way into this account.',
  errDiscordUnavailable: 'Discord sign-in is not available at this address.',
  errDiscordLinked: 'That Discord is already linked to an account.',
  errUnauthorized: 'Please sign in again.',
  errOffline: 'Server is down. Run "bun run dev:online" (or play offline training).',
  errGeneric: 'Something went wrong. Try again.',
  onlineSubtitle: 'Session: {name} · {mode}',
  // Mapas and Gerenciamento tabs (PF-6: client/ui/maps.ts, client/ui/management.ts).
  tabMaps: 'MAPS',
  tabManagement: 'MANAGEMENT',
  mapsOfficial: 'Official',
  mapsCommunity: 'Community',
  mapsNew: '+ New map',
  mapsSearch: 'Search…',
  mapsSearchBy: 'Search by',
  mapsByName: 'Name',
  mapsByAuthor: 'Author',
  mapsOrder: 'Order',
  mapsOrderPlayed: 'Most played',
  mapsOrderRecent: 'Most recent',
  mapsShowHidden: 'Show hidden',
  mapsEmpty: 'No maps found.',
  mapsMore: 'Show more',
  mapsPlays: '{n} plays',
  mapsPlaysOne: '1 play',
  mapsVersion: 'version {v}',
  mapsBy: 'by {autor}',
  mapsOfficialBy: 'Official map',
  mapsCommunitySub: 'Community map',
  mapsZombieOnly: 'Zombie only',
  mapsHiddenTag: 'Hidden',
  mapsHiddenWhy: 'Hidden: {motivo}',
  mapsPlay: 'Play',
  mapsBots: 'Vs bots',
  mapsRange: 'Training range',
  mapsEdit: 'Edit',
  mapsDuplicate: 'Duplicate',
  mapsDelete: 'Delete',
  mapsHide: 'Hide',
  mapsUnhide: 'Unhide',
  mapsVersions: 'Versions',
  mapsCancel: 'Cancel',
  mapsClose: 'Close',
  mapsDeleteConfirm: 'Delete "{nome}"? It leaves the lists and opens no more matches (matches being played finish on it).',
  mapsHideReason: 'Reason (optional)',
  mapsHideConfirm: 'Hide "{nome}" from the lists? Only its author and the staff still see it.',
  mapsVersionsTitle: 'Saved versions',
  mapsRestore: 'Restore',
  mapsCurrent: 'current',
  mapsRestored: 'Version {v} restored: new matches use it.',
  mapsDuplicated: 'Copy of "{nome}" made in Community.',
  mapsDeleted: 'Map deleted.',
  mapsHidden: 'Map hidden.',
  mapsUnhidden: 'The map is back on the lists.',
  mapsLoading: 'Loading…',
  mgTitle: 'Management',
  mgHint: 'Find an account by its name or tag (Name#1234).',
  mgSearch: 'Name or Name#1234',
  mgFind: 'Search',
  mgOpen: 'Open',
  mgEmpty: 'No accounts found.',
  mgBanned: 'Banned',
  mgMuted: 'Muted',
  mgSuspended: 'Suspended',
  mgPendingDeletion: 'Being deleted',
  mgRole_admin: 'Admin',
  mgRole_moderador: 'Moderator',
  mgPlayer: 'Player',
  mgReadOnly: 'You can\'t change this account: a moderator doesn\'t act on an admin.',
  mgSanctions: 'Sanctions',
  mgNoPunish: 'You can\'t punish this account.',
  mgBan: 'Ban',
  mgMute: 'Mute',
  mgReason: 'Reason',
  mgDuration: 'Duration',
  mgDur_1h: '1 hour',
  mgDur_12h: '12 hours',
  mgDur_1d: '1 day',
  mgDur_7d: '7 days',
  mgDur_30d: '30 days',
  mgDur_permanente: 'Permanent',
  mgApply: 'Apply',
  mgUnban: 'Lift the ban',
  mgUnmute: 'Lift the mute',
  mgHistory: 'History',
  mgNoSanctions: 'No sanctions.',
  mgSanction_banimento: 'Ban',
  mgSanction_silencio: 'Mute',
  mgUntil: 'until {data}',
  mgForever: 'no end',
  mgRevoked: 'lifted on {data}',
  mgBy: 'by {tag}',
  mgNeedReason: 'Write the reason.',
  mgName: 'Name',
  mgNameHint: 'Changed at once, without the 7-day wait; the player\'s own wait starts again.',
  mgLook: 'Look',
  mgEditLook: 'Edit the look',
  mgProgress: 'Progress',
  mgAccountXp: 'Account XP (level {n})',
  mgWeaponXp: 'Weapon XP',
  mgSaveProgress: 'Save progress',
  mgBadNumber: 'Use whole numbers from 0 to 1,000,000,000.',
  mgRoles: 'Roles',
  mgPromote: 'Make {papel}',
  mgDemote: 'Remove {papel}',
  mgRolesNone: 'You can\'t change this account\'s roles.',
  mgDone: 'Done.',
  errNoPermission: 'You\'re not allowed to do that.',
  errNotFound: 'Not found.',
  errBadInput: 'Invalid data.',
  errLastAdmin: 'The last admin can\'t be removed.',
  errProtectedMap: 'The four original official maps can\'t be deleted or hidden.',
  pmLineSession: 'Session: {name} · {n}/{max} players',
  pmLineBots: 'Against {n} bots · {skill}',
  pmLineWave: 'Wave {n}/{total}',
  pmLineWaveTeam: '{wave} · {players} players',
  pmLineWaveAlone: '{wave} · 1 player',
  pmLineWaveSolo: '{wave} · alone',
  pmLineRange: 'Offline practice with the dummies',
  pmPreview: 'Preview: {file}',
  pmLiveOnline: 'Online: the game goes on and you can get shot.',
  pmLiveHorde: "Online: the horde doesn't wait. Your team keeps fighting.",
  pmPausedBots: 'Game paused: the bots are waiting for you.',
  pmPaused: 'Game paused.',
  pmExitSession: 'Leave the session',
  pmExitMatch: 'Leave the match',
  pmExitRace: 'Leave the race',
  pmExitRange: 'Leave practice',
  pmConfirmSession: "You leave the session {name} and go back to the home screen. The points your weapons already earned stay on your account.",
  pmConfirmBots: 'The match against the bots ends and you go back to the home screen.',
  pmConfirmRace: 'You leave the race and lose the step you are on. Back to the home screen.',
  pmConfirmRaceBots: 'The race against the bots ends and you go back to the home screen.',
  pmConfirmZombieTeam: "Your team goes on without you. This match's money isn't kept.",
  pmConfirmZombieAlone: "The match starts over for the next one who joins. This match's money isn't kept.",
  pmConfirmZombieSolo: "The match ends and the money isn't kept.",
  pmConfirmRange: 'You leave the shooting range and go back to the home screen.',
  pmConfirmEditor: 'The game stops and you go back to the editor, where you were.',
  pmStay: 'STAY',
  pmLeave: 'LEAVE',
  pmStayHint: 'stays in the match',
  pmClose: 'Close',
  pmBack: 'Back',
  pmHintResume: 'Back to the game',
  pmHintBack: 'Back',
  pmHintPick: 'Select',
  pmBadgeReadOnly: '🔒 View only',
  pmBadgeEditable: 'Editable in practice',
  pmArsenalSubReadOnly: 'Your loadout · view only',
  pmArsenalSubEditable: 'Swap weapons and upgrades',
  pmArsenalHintReadOnly: 'What you brought to this match.',
  pmArsenalHintEditable: 'The shooting range lets you change everything, right away.',
  pmArsenalFootReadOnly: 'Locked during the match. Change weapons and upgrades in the home screen’s Arsenal: changes apply from the next match.',
  pmArsenalFootEditable: 'On the shooting range the Arsenal is editable and changes apply right away.',
  pmArsenalFootGuest: 'Create an account so your weapons level up',
  pmUpgradesUnlocked: 'Unlocked upgrades',
  pmNoUpgrades: 'No upgrades unlocked yet',
  pmMoreUpgrades: '🔒 {n} more upgrades to unlock. Next: {upgrade}, {xp} more {prog} points.',
  pmMoreUpgrade: '🔒 1 more upgrade to unlock: {upgrade}, {xp} more {prog} points.',
  pmNextMatch: 'Applies next match',
  pmWeaponsUnlocked: 'Unlocked weapons',
  pmTabLadder: 'Ladder',
  pmTabLadderSub: 'Step {n} of {total} · {k}/{need} kills',
  pmLadderHint: 'Everyone uses the same weapons, with the same stats.',
  pmLadderYou: 'You · {k}/{need}',
  pmLadderNow: 'Now · step {n}',
  pmLadderNext: 'Next · step {n}',
  pmLadderToGo: '{n} more kills to move up',
  pmLadderToGoOne: '1 more kill to move up',
  pmLadderToWin: '{n} more kills to win',
  pmLadderToWinOne: '1 more kill to win',
  pmLadderGun: '{mag} rounds · {rpm} rpm',
  pmLadderSilenced: 'muffled shots',
  pmLadderFinal: 'Final kill',
  pmLadderFinalOne: 'One kill with the {weapon} wins the round',
  pmLadderFinalMany: '{n} kills with the {weapon} win the round',
  pmRuleClimb: '{n} kills with the current weapon or the knife move you up a step.',
  pmRuleStab: 'Dying to a stab takes a kill away. With no kills on the step, you go back a weapon.',
  pmRuleFinalOne: 'On the last step, one kill with the {weapon} wins the round.',
  pmRuleFinalMany: 'On the last step, {n} kills with the {weapon} win the round.',
  pmLeader: 'In the lead',
  pmLeaderOther: '{name} · step {n} ({weapon})',
  pmLeaderYou: 'You are in the lead',
  pmTabCoffin: 'Coffin',
  pmTabCoffinSub: 'What you carry and the odds',
  pmCoffinHintOnline: '${cost} per weapon, drawn on the server. Rarity multiplies the damage against zombies.',
  pmCoffinHintSolo: '${cost} per weapon. Rarity multiplies the damage against zombies.',
  pmCoffinFoot: 'The new weapon replaces the one of the same kind (rifle, secondary or knife). A damaged one can’t be fixed: only another round.',
  pmCoffinOdds: 'Odds · ${cost}',
  pmCoffinMul: '×{m} damage',
  pmCoffinBroken: '{n}% come damaged',
  pmConfigSub: 'Aim, video, audio and keys',
  pmConfigHint: 'Everything applies right away.',
  pmSubAim: 'Aim',
  pmSubVideo: 'Video',
  pmSubAudio: 'Audio',
  pmSubKeys: 'Keys',
  pmSubPad: 'Controller',
  pmSubTouch: 'Touch',
  pmDescSens: 'Mouse, not aiming',
  pmDescAds: 'Multiplies the sensitivity while aiming',
  pmDescPadSens: 'Right stick',
  pmDescAssist: "The crosshair slows down over an enemy, it doesn't pull from afar",
  pmDescInvert: 'Moving up looks down',
  pmDescFov: 'Wider sees more to the sides',
  pmDescQuality: 'Automatic adjusts itself to keep the FPS',
  pmDescDetail: 'Light simplifies trees, foliage and ornaments (from the next match on)',
  pmDescFullscreen: 'In fullscreen, Esc opens and closes the menu instantly',
  pmDescVolume: "The game's overall volume",
  pmDescSpatial: 'Automatic: 3D on a computer, stereo on a phone',
  pmOn: 'On',
  pmOff: 'Off',
  keyGroupMove: 'Movement',
  keyGroupCombat: 'Combat',
  keyGroupOther: 'Other',
  pmKeyPress: 'Press…',
  pmEscFixed: 'opens the menu (fixed)',
  pmPadNote: 'Fixed controller layout (CoD style). Keyboard keys can be remapped.',
  gpuWarning:
    'Your browser is rendering the game without a graphics card (renderer: {gpu}), which caps it around 10 FPS. Enable “Use graphics acceleration when available” in chrome://settings/system (Edge: edge://settings/system) and restart the browser.',
  // Galpão (client/ui/galpao)
  gpQuick: 'QUICK JOIN',
  gpQuickLine: '{mode} · Online · {maps}',
  gpNoMapMarked: 'no map ticked',
  gpBack: '‹ WAREHOUSE',
  gpLaunching: 'JOINING THE MATCH',
  gpLaunchOnline: '{map} · {mode} · {n}/{max} players',
  gpLaunchBots: 'Against {n} bots · {map}',
  gpLaunchHorde: 'Alone against the horde · {map}',
  gpLaunchRange: 'Offline training · {map}',
  gpSt_play: 'Play',
  gpSt_maps: 'Maps',
  gpSt_arsenal: 'Arsenal',
  gpSt_album: 'Album',
  gpSt_profile: 'Profile',
  gpSt_settings: 'Settings',
  gpSt_admin: 'Management',
  gpStSub_play: 'Online, against bots or the shooting range',
  gpStSub_maps: 'Official and community: play, duplicate or create',
  gpStSub_arsenal: 'Weapons, upgrades and loadout',
  gpStSub_album: 'Stickers, titles and showcase',
  gpStSub_profile: 'Account, stats and character',
  gpStSub_settings: 'Aim, video, audio and keys',
  gpStSub_admin: 'Moderation · staff only',
  gpHint_play: 'Pick the mode, the match type and the map. The orange button starts.',
  gpHint_maps: 'Play a map, duplicate one to edit it or create one from scratch.',
  gpHint_arsenal: 'Drag to move around, mouse wheel to zoom. Click a weapon for its details. Green: equipped · red: locked.',
  gpHint_arsenalTouch: 'Drag to move around, pinch to zoom. Tap a weapon for its details. Green: equipped · red: locked.',
  gpHint_album: 'Click a sticker to see how to earn it. The tabs turn the pages.',
  gpHint_profile: 'Your file: stats, latest matches and the account options.',
  gpHint_settings: 'Pick a section at the top of the panel. Changes apply right away.',
  gpHint_admin: 'Find the account, check its status and pick an action. Nothing changes until you confirm.',
  gpSign_play: '01 · OPERATIONS',
  gpSign_maps: '02 · MAPS',
  gpSign_arsenal: '03 · ARSENAL',
  gpSign_profile: '05 · LOCKER ROOM',
  gpSign_settings: '06 · WORKSHOP',
  gpSign_admin: '07 · SECURITY',
  gpBoard_primaria: 'PRIMARY',
  gpBoard_secundaria: 'SECONDARY',
  gpBoard_faca: 'KNIFE',
  gpBoard_granada: 'GRENADE',
  gpAdminScreen: 'MANAGEMENT',
  gpAdminScreenSub: 'RESTRICTED · STAFF',
  gpDanger: 'DANGER',
  gpHighVoltage: 'HIGH VOLTAGE',
  gpExit: 'EXIT',
  gpAlbumCover1: 'OFFENSIVE COMBAT · OFFICIAL ALBUM',
  gpAlbumCover2: 'STICK',
  gpAlbumCover3: 'ERS',
  gpAlbumCover4: '{n} STICKERS',
  gpTagLevel: 'LV{level}',
  gpTagLocked: 'LOCKED',
  gpTagOn: 'ON',
  gpTagOff: 'OFF',
  gpLockedChip: 'LOCKED',
  gpSharesProg: 'Uses the {prog} points and upgrades',
  gpAutoOn: 'Turns on by itself when unlocked',
  gpUpgradesOf: '{prog} UPGRADES',
  gpPlayHintOnline: 'Pick the match type and the maps. The list shows the sessions open now.',
  gpPlayHintBots: 'Offline match against bots, with your Arsenal and the account upgrades.',
  gpPlayHintRange: 'Click a map (or the orange button) to open the shooting range with the dummies.',
  gpCtaLine: '{mode} · {map}',
  gpRangeTargets: 'Still dummies',
};

export const TIPS = {
  'pt-BR': [
    'Dica: atirar no inimigo costuma funcionar melhor que atirar na parede.',
    'Dica: o boneco não revida. Ainda.',
    'Dica: cair de 7 metros dói. Pergunte ao seu joelho.',
    'Dica: mirar na cabeça dá o dobro de dano e o triplo de arrogância.',
    'Dica: correr e atirar ao mesmo tempo não é permitido. Sindicato dos braços.',
    'Dica: o caminhão de sorvete não vende sorvete. Mas toca música.',
    'Dica: os flamingos não têm culpa de nada.',
  ],
  en: [
    'Tip: shooting the enemy usually works better than shooting the wall.',
    "Tip: the dummy doesn't shoot back. Yet.",
    'Tip: falling 7 meters hurts. Ask your knees.',
    'Tip: headshots deal double damage and triple arrogance.',
    'Tip: no shooting while sprinting. Arm union rules.',
    "Tip: the ice cream truck doesn't sell ice cream. It does play music.",
    'Tip: the flamingos are innocent.',
  ],
};

/** One-tap chat lines (phones: no keyboard needed mid-fight). */
export const QUICK_CHAT = {
  'pt-BR': ['GG', 'Boa!', 'Kkkkk', 'Cuidado!', 'Bora x1?', 'Valeu!'],
  en: ['GG', 'Nice!', 'LOL', 'Watch out!', '1v1 me?', 'Thanks!'],
};

export const DEATH_MESSAGES = {
  'pt-BR': {
    fall: ['Você venceu a gravidade. Brincadeira, ela venceu.', 'Da próxima vez, tente cair de pé.', 'A calçada mandou lembranças.'],
    void: ['Você saiu do mapa. O mapa não sentiu sua falta.', 'Explorador corajoso. Explorador morto.'],
    explosion: ['Você cozinhou demais. A granada, e você.', 'Dica: a granada vai na direção do inimigo.'],
    dog: ['A Amora não gostou da visita.', 'Mordido pela Amora. Fofa, mas brava.', 'Quintal errado. Au.'],
    zombie: ['Virou almoço de zumbi.', 'O vizinho mordeu. E não era carinho.', 'Ninguém veio te reanimar. Que vizinhança.'],
    thorns: ['A grade tinha espinhos. Estava escrito em lugar nenhum.', 'Pular o muro: 0. Espinhos: 1.', 'Sangrou até o fim. A sebe agradece.'],
    sacrilege: ['Subiu no altar. O altar não gostou.', 'Sacrilégio: a capela cobra caro.', 'O totem é para acender, não para pisar.'],
    crows: ['Os corvos acharam você primeiro.', 'Árvore não é esconderijo. Os corvos avisaram.', 'Bicado até o fim.'],
  },
  en: {
    fall: ['You beat gravity. Just kidding, it beat you.', 'Next time, try landing on your feet.', 'The sidewalk says hi.'],
    void: ["You left the map. The map didn't miss you.", 'Brave explorer. Dead explorer.'],
    explosion: ['You overcooked it. The grenade, and yourself.', 'Tip: the grenade goes toward the enemy.'],
    dog: ['Amora did not like your visit.', 'Bitten by Amora. Fluffy, but grumpy.', 'Wrong yard. Woof.'],
    zombie: ['You became zombie lunch.', 'The neighbor bit you. Not a love bite.', 'Nobody came to revive you. What a neighborhood.'],
    thorns: ['The fence had thorns. It said so nowhere.', 'Climbing the wall: 0. Thorns: 1.', 'Bled out. The hedge thanks you.'],
    sacrilege: ['You climbed the altar. The altar minded.', 'Sacrilege: the chapel charges dearly.', 'The totem is for lighting, not for standing on.'],
    crows: ['The crows found you first.', 'A tree is no hiding place. The crows said so.', 'Pecked to the end.'],
  },
};

export type Lang = 'pt-BR' | 'en';
export type StringKey = keyof typeof ptBR;

// Bun (the tests) has a navigator without a language.
let lang: Lang = (globalThis.navigator as { language?: string } | undefined)?.language?.toLowerCase().startsWith('pt') ? 'pt-BR' : 'en';
const dicts: Record<Lang, Record<StringKey, string>> = { 'pt-BR': ptBR, en };

export function getLang(): Lang {
  return lang;
}

export function setLang(l: Lang) {
  lang = l;
}

export function t(key: StringKey, params: Record<string, string | number> = {}): string {
  return dicts[lang][key].replace(/\{(\w+)\}/g, (_, k) => String(params[k] ?? ''));
}

export function pick<T>(list: T[]): T {
  return list[(Math.random() * list.length) | 0];
}
