// Every user-facing string lives here (section 5: pt-BR and en at minimum).
const ptBR = {
  title: 'OFFENSIVE COMBAT',
  subtitle: 'Protótipo de tiro · Fase 1',
  play: 'JOGAR',
  resume: 'VOLTAR AO JOGO',
  clickToResume: 'Clique para voltar ao jogo',
  aimOnNextKey: 'A mira volta com a próxima tecla ou clique',
  fullscreenDesktop: 'Tela cheia ao jogar (Esc abre e fecha o menu na hora)',
  loading: 'Carregando',
  controls: 'Controles',
  settings: 'Configurações',
  sensitivity: 'Sensibilidade',
  adsSensitivity: 'Sensibilidade na mira',
  fov: 'Campo de visão',
  volume: 'Volume',
  invertY: 'Inverter eixo Y',
  health: 'VIDA',
  reload: 'RECARREGUE',
  noAmmo: 'SEM MUNIÇÃO',
  reloading: 'RECARREGANDO…',
  points: 'Pontos',
  kills: 'Abates',
  accuracy: 'Precisão',
  you: 'Você',
  kill: 'Abate',
  headshot: 'Tiro na cabeça',
  longShot: 'Longa distância',
  respawnIn: 'Renascendo em {s}…',
  debugHint: 'F3 depuração · F4 hitboxes e colisores (personagem → personagem + assets → nenhum)',
  debugViewChars: 'F4: hitboxes dos personagens',
  debugViewAll: 'F4: personagens + colisores do mapa',
  debugViewOff: 'F4: depuração visual desligada',
  keyMove: 'Mover',
  keyJump: 'Pular',
  keyCrouch: 'Agachar (correndo: derrapar)',
  keySprint: 'Correr',
  keyFire: 'Atirar',
  keyAds: 'Mirar',
  keyReload: 'Recarregar',
  keyPause: 'Menu',
  mouseLeft: 'Botão esq.',
  mouseRight: 'Botão dir.',
  keyMelee: 'Facada',
  keyTaunt: 'Oprimir (perto do corpo)',
  keyGrenade: 'Granada (segure para cozinhar)',
  keyForward: 'Andar para frente',
  keyBack: 'Andar para trás',
  keyLeft: 'Andar à esquerda',
  keyRight: 'Andar à direita',
  keyScoreboard: 'Placar',
  keyAction: 'Ação',
  keyPrimary: 'Principal',
  keyAlternate: 'Alternativa',
  keyPress: 'Pressione uma tecla… (Esc cancela)',
  keyClear: 'Tirar a tecla',
  keyUnbound: 'Sem tecla',
  keyMoved: '{key} estava em "{action}", que ficou sem tecla {slot}.',
  keyNoCtrl: 'O Ctrl não pode ser usado: Ctrl+W fecha a aba do navegador.',
  keyFixed: '{key} é reservada para a depuração.',
  keyWheelHold: 'A roda do mouse não fica pressionada: use-a em pular, atirar, recarregar, facada, granada ou oprimir.',
  keysReset: 'Restaurar teclas padrão',
  grenadeName: 'Granada',
  knife: 'Facada',
  knifeName: 'Faca',
  weaponRifle: 'Rifle',
  weaponKnife: 'Faca',
  weaponGrenade: 'Granada',
  levelUp: '{weapon} nível {level}',
  mineLimit: 'Máximo de {n} minas no mapa',
  cherryTaken: '🍒 Cereja do Dragão: +{n} de vida máxima por {s} s',
  cherryOver: 'O efeito da cereja acabou',
  koiXp: '🐟 Peixe abatido: +{n} XP',
  goldenKoiXp: '✨ Carpa dourada: +{n} XP',
  goldenKoi: '✨ Carpa dourada! Mira afiada por {s} s',
  goldenKoiOver: 'A mira afiada da carpa acabou',
  galleryAim: '🎯 Todos os alvos! Mira afiada por {s} s',
  humanityTaken: '🕯️ Humanidade obtida: +{n} de vida máxima até morrer',
  biscuitTaken: '🦴 Biscoito Scooby! Vida cheia. Scooby-Dooby-Doo!',
  promptPotion: 'Beber Poção',
  potion_pato: '🦆 Granadas de pato até morrer!',
  potion_veloz: '💨 Poção da pressa: mais rápido por {s} s',
  potion_lerdo: '🐌 Poção da lerdeza: mais lento por {s} s',
  potion_critico: '💀 Poção do crítico: todo tiro é crítico por {s} s',
  potion_bebado: '🍺 Poção do bêbado: mira torta por {s} s',
  potionOver: 'O efeito da poção acabou',
  galleryAimOver: 'A mira afiada do tiro ao alvo acabou',
  buffKoi: 'Mira da carpa',
  buffGallery: 'Mira afiada',
  buffCherry: 'Vida extra',
  buffHumanity: 'Humanidade',
  buffDuck: 'Granadas de pato',
  buffVeloz: 'Pressa',
  buffLerdo: 'Lerdeza',
  buffCritico: 'Tiro crítico',
  buffBebado: 'Bêbado',
  buffUntilDeath: 'até morrer',
  arsenal: 'Arsenal',
  arsenalHint: 'Cada abate evolui só a arma que matou. Clique num nível liberado para equipar.',
  level: 'Nível',
  equipped: 'Equipado',
  equip: 'Equipar',
  locked: 'Bloqueado',
  xpToNext: '{xp} / {next} pontos para o nível {level}',
  maxLevel: 'Nível máximo! {xp} pontos',
  unlockAt: 'Libera com {xp} pontos',
  dogBite: 'Mordida',
  backstab: 'Pelas costas',
  groin: 'No pássaro',
  groinBanner: 'NO PÁSSARO!',
  humiliation: 'Opressão',
  humiliatedBanner: 'OPRIMIDO!',
  danceName: 'Dancinha da Vitória',
  promptTaunt: 'Oprimir {name}',
  dancing: 'Oprimindo {name}…',
  quality: 'Qualidade gráfica',
  qualityAuto: 'Automática',
  spatialAudio: 'Som',
  spatialAuto: 'Automático',
  spatialHeadphones: 'Fone (3D)',
  spatialSpeakers: 'Caixa de som (estéreo)',
  qualityLow: 'Baixa',
  qualityMedium: 'Média',
  qualityHigh: 'Alta',
  touchFire: 'Atirar',
  touchAds: 'Mirar',
  touchJump: 'Pular',
  touchCrouch: 'Agachar',
  touchReload: 'Recarregar',
  touchMelee: 'Faca',
  touchGrenade: 'Granada',
  touchPause: 'Pausar',
  touchBoard: 'Placar',
  touchFullscreen: 'Tela cheia',
  tapToResume: 'Toque em VOLTAR AO JOGO',
  touchSensitivity: 'Sensibilidade do toque',
  touchScale: 'Tamanho dos botões',
  touchOpacity: 'Opacidade dos botões',
  aimAssist: 'Assistência de mira',
  adsHold: 'Segurar para mirar (desligado: tocar alterna)',
  padSensitivity: 'Sensibilidade do controle',
  padToResume: 'Aperte {a} ou {start} para voltar ao jogo',
  padLook: 'Mirar',
  padLeftStick: 'Analógico esquerdo',
  padRightStick: 'Analógico direito',
  fullscreenOnPlay: 'Tela cheia ao jogar',
  editLayout: 'Ajustar botões',
  editLayoutDone: 'Pronto',
  editLayoutReset: 'Posições padrão',
  editLayoutHint: 'Arraste os botões para onde preferir.',
  rotatePhone: 'Gire o celular para jogar',
  fullscreen: 'Tela cheia',
  iosFullscreen: 'Para tela cheia no iPhone: toque em Compartilhar e depois em "Adicionar à Tela de Início".',
  tapHint: 'Toque',
  touchControlsHelp: 'Arraste à esquerda para andar (até a borda corre) · arraste à direita para mirar · botões para atirar, mirar, pular, agachar, recarregar, faca e granada (segure para preparar).',
  yourName: 'Seu nome',
  sexLabel: 'Sexo',
  sexMale: '♂ Masculino',
  sexFemale: '♀ Feminino',
  playOnline: 'JOGAR ONLINE',
  playOffline: 'Campo de tiro (bonecos parados)',
  playBots: 'CONTRA BOTS',
  botSkill: 'Dificuldade',
  mapLabel: 'Mapa',
  botCount: 'Bots',
  skillEasy: 'Fácil',
  skillNormal: 'Normal',
  skillHard: 'Difícil',
  botsSubtitle: 'Contra {n} bots · mata-mata livre',
  sessions: 'Sessões',
  createSession: 'CRIAR',
  sessionNamePlaceholder: 'Nome da nova sessão',
  back: 'Voltar',
  noSessions: 'Nenhuma sessão aberta. Crie a primeira!',
  join: 'ENTRAR',
  full: 'LOTADA',
  joining: 'Entrando…',
  connecting: 'Conectando ao servidor…',
  connectedAs: 'Conectado como {name}.',
  disconnected: 'Conexão com o servidor perdida.',
  serverOffline: 'Servidor fora do ar. Rode "bun run server" (ou jogue o treino offline).',
  needName: 'Escolha um nome primeiro.',
  exitToHome: 'Sair para o início',
  scoreboard: 'Placar',
  player: 'Jogador',
  deaths: 'Mortes',
  humiliationsShort: 'Opress.',
  killedBy: '{name} te eliminou',
  killedByWith: '{name} te eliminou com {weapon}',
  playerJoined: '{name} entrou',
  playerLeft: '{name} saiu',
  keyChat: 'Chat da sala',
  chatPlaceholder: 'Mensagem para a sala…',
  chatSend: 'Enviar',
  chatClose: 'Fechar o chat',
  chatHint: 'Enter envia · Esc fecha',
  chatMuted: 'Seu chat está silenciado pela moderação.',
  chatSlow: 'Calma! Espere um pouco para mandar outra.',
  touchChat: 'Chat',
  lostConnection: 'Sem conexão com o servidor',
  accountGuest: 'Sem conta: treino e bots estão liberados. Para jogar online, entre ou crie uma conta.',
  signIn: 'ENTRAR',
  signUp: 'CRIAR CONTA',
  profile: 'PERFIL',
  signOut: 'Sair da conta',
  email: 'E-mail',
  password: 'Senha',
  gameName: 'Nome no jogo',
  signInTitle: 'Entrar',
  signUpTitle: 'Criar conta',
  forgotTitle: 'Esqueci a senha',
  resetTitle: 'Nova senha',
  chooseNameTitle: 'Escolha seu nome no jogo',
  withDiscord: 'Entrar com Discord',
  forgotLink: 'Esqueci a senha',
  haveAccount: 'Já tenho conta',
  noAccount: 'Criar uma conta',
  send: 'ENVIAR',
  save: 'SALVAR',
  resetSent: 'Se esse e-mail tiver conta, enviamos um link válido por 24 horas.',
  resetDone: 'Senha trocada. Entre com a senha nova.',
  needAccount: 'Entre na sua conta para jogar online.',
  passwordHint: 'De 8 a 128 caracteres.',
  nameHint: 'De 3 a 16 letras ou números. Aparece como Nome#1234.',
  levelShort: 'Nv {level}',
  accountLevelUp: '🏅 Conta nível {level}!',
  sessionEnded: 'Sua sessão foi encerrada (saída da conta, troca de senha, exclusão ou suspensão).',
  connectedElsewhere: 'Sua conta entrou no jogo em outro lugar.',
  profileTitle: 'Perfil',
  statsTitle: 'Estatísticas',
  recentTitle: 'Últimas participações',
  noParticipations: 'Nenhuma partida online ainda.',
  statKills: 'Abates',
  statDeaths: 'Mortes',
  statHead: 'Na cabeça',
  statGroin: 'No pássaro',
  statKnife: 'Facadas',
  statBackstab: 'Pelas costas',
  statGrenade: 'Com granada',
  statHumiliations: 'Opressões',
  statTime: 'Tempo jogado',
  statMatches: 'Participações',
  customize: 'PERSONALIZAR PERSONAGEM',
  changeName: 'Trocar nome',
  nameFreeAt: 'Próxima troca liberada em {date}.',
  nameRule: 'A primeira troca é livre; depois, uma a cada 7 dias.',
  linkDiscord: 'Vincular Discord',
  unlinkDiscord: 'Desvincular Discord',
  discordLinked: 'Discord vinculado.',
  deleteAccount: 'Excluir conta',
  deleteConfirm: 'Excluir a conta? Você tem 30 dias para desistir entrando de novo. Depois disso, nome e e-mail são apagados.',
  cancelDeletion: 'Cancelar exclusão',
  deletionPending: 'Conta marcada para exclusão em {date}. O jogo online fica bloqueado até você cancelar.',
  saved: 'Salvo.',
  errCredentials: 'E-mail ou senha incorretos.',
  errTooMany: 'Muitas tentativas. Espere um minuto e tente de novo.',
  errSuspended: 'Esta conta está suspensa.',
  errPendingDeletion: 'Esta conta está marcada para exclusão. Cancele no Perfil para jogar online.',
  errEmailUsed: 'Esse e-mail já tem conta. Entre ou use "Esqueci a senha".',
  errEmailInvalid: 'E-mail inválido.',
  errPasswordInvalid: 'A senha precisa ter de 8 a 128 caracteres.',
  errNameInvalid: 'Nome inválido: de 3 a 16 letras ou números.',
  errNameTaken: 'Esse nome não tem mais números livres. Tente outro.',
  errNameCooldown: 'Você só pode trocar de nome de novo em {date}.',
  errTokenInvalid: 'Link inválido ou vencido. Peça outro em "Esqueci a senha".',
  errOnlyLogin: 'O Discord é a única forma de entrar nesta conta.',
  errDiscordUnavailable: 'Entrar com Discord não está disponível neste endereço.',
  errDiscordLinked: 'Esse Discord já está vinculado a uma conta.',
  errUnauthorized: 'Entre na sua conta de novo.',
  errOffline: 'Servidor fora do ar. Rode "bun run dev:online" (ou jogue o treino offline).',
  errGeneric: 'Algo deu errado. Tente de novo.',
  onlineSubtitle: 'Sessão: {name} · mata-mata livre',
  gpuWarning:
    'Seu navegador está desenhando o jogo sem placa de vídeo (renderizador: {gpu}), por isso fica em ~10 FPS. Ative “Usar aceleração gráfica quando disponível” em chrome://settings/system (no Edge: edge://settings/system) e reinicie o navegador.',
} as const;

const en: Record<keyof typeof ptBR, string> = {
  title: 'OFFENSIVE COMBAT',
  subtitle: 'Shooting prototype · Phase 1',
  play: 'PLAY',
  resume: 'BACK TO THE GAME',
  clickToResume: 'Click to return to the game',
  aimOnNextKey: 'Aim comes back with your next key or click',
  fullscreenDesktop: 'Fullscreen when playing (Esc opens and closes the menu instantly)',
  loading: 'Loading',
  controls: 'Controls',
  settings: 'Settings',
  sensitivity: 'Sensitivity',
  adsSensitivity: 'ADS sensitivity',
  fov: 'Field of view',
  volume: 'Volume',
  invertY: 'Invert Y axis',
  health: 'HEALTH',
  reload: 'RELOAD',
  noAmmo: 'NO AMMO',
  reloading: 'RELOADING…',
  points: 'Points',
  kills: 'Kills',
  accuracy: 'Accuracy',
  you: 'You',
  kill: 'Kill',
  headshot: 'Headshot',
  longShot: 'Long shot',
  respawnIn: 'Respawning in {s}…',
  debugHint: 'F3 debug · F4 hitboxes and colliders (characters → characters + assets → off)',
  debugViewChars: 'F4: character hitboxes',
  debugViewAll: 'F4: characters + map colliders',
  debugViewOff: 'F4: visual debug off',
  keyMove: 'Move',
  keyJump: 'Jump',
  keyCrouch: 'Crouch (while sprinting: slide)',
  keySprint: 'Sprint',
  keyFire: 'Fire',
  keyAds: 'Aim',
  keyReload: 'Reload',
  keyPause: 'Menu',
  mouseLeft: 'Left mouse',
  mouseRight: 'Right mouse',
  keyMelee: 'Knife',
  keyTaunt: 'Humiliate (near a body)',
  keyGrenade: 'Grenade (hold to cook)',
  keyForward: 'Move forward',
  keyBack: 'Move back',
  keyLeft: 'Strafe left',
  keyRight: 'Strafe right',
  keyScoreboard: 'Scoreboard',
  keyAction: 'Action',
  keyPrimary: 'Primary',
  keyAlternate: 'Alternate',
  keyPress: 'Press a key… (Esc cancels)',
  keyClear: 'Remove the key',
  keyUnbound: 'No key',
  keyMoved: '{key} was on "{action}", which lost its {slot} key.',
  keyNoCtrl: "Ctrl can't be used: Ctrl+W closes the browser tab.",
  keyFixed: '{key} is reserved for debugging.',
  keyWheelHold: "The mouse wheel can't be held: use it for jump, fire, reload, knife, grenade or humiliate.",
  keysReset: 'Restore default keys',
  grenadeName: 'Grenade',
  knife: 'Knifed',
  knifeName: 'Knife',
  weaponRifle: 'Rifle',
  weaponKnife: 'Knife',
  weaponGrenade: 'Grenade',
  levelUp: '{weapon} level {level}',
  mineLimit: 'At most {n} mines on the map',
  cherryTaken: '🍒 Dragon Cherry: +{n} max health for {s} s',
  cherryOver: 'The cherry wore off',
  koiXp: '🐟 Fish down: +{n} XP',
  goldenKoiXp: '✨ Golden carp: +{n} XP',
  goldenKoi: '✨ Golden carp! Sharp aim for {s} s',
  goldenKoiOver: "The golden carp's sharp aim wore off",
  galleryAim: '🎯 Every target down! Sharp aim for {s} s',
  humanityTaken: '🕯️ Humanity gained: +{n} max health until you die',
  biscuitTaken: '🦴 Scooby Snack! Full health. Scooby-Dooby-Doo!',
  promptPotion: 'Drink Potion',
  potion_pato: '🦆 Duck grenades until you die!',
  potion_veloz: '💨 Haste potion: faster for {s} s',
  potion_lerdo: '🐌 Sluggish potion: slower for {s} s',
  potion_critico: '💀 Critical potion: every shot is a critical for {s} s',
  potion_bebado: "🍺 Drunk potion: crooked aim for {s} s",
  potionOver: 'The potion wore off',
  galleryAimOver: "The shooting gallery's sharp aim wore off",
  buffKoi: 'Carp aim',
  buffGallery: 'Sharp aim',
  buffCherry: 'Extra health',
  buffHumanity: 'Humanity',
  buffDuck: 'Duck grenades',
  buffVeloz: 'Haste',
  buffLerdo: 'Sluggish',
  buffCritico: 'Critical shots',
  buffBebado: 'Drunk',
  buffUntilDeath: 'until death',
  arsenal: 'Arsenal',
  arsenalHint: 'Each kill levels up only the weapon that made it. Click an unlocked level to equip it.',
  level: 'Level',
  equipped: 'Equipped',
  equip: 'Equip',
  locked: 'Locked',
  xpToNext: '{xp} / {next} points to level {level}',
  maxLevel: 'Max level! {xp} points',
  unlockAt: 'Unlocks at {xp} points',
  dogBite: 'Bite',
  backstab: 'Backstab',
  groin: 'Right in the birdie',
  groinBanner: 'RIGHT IN THE BIRDIE!',
  humiliation: 'Humiliation',
  humiliatedBanner: 'HUMILIATED!',
  danceName: 'Victory Dance',
  promptTaunt: 'Humiliate {name}',
  dancing: 'Humiliating {name}…',
  quality: 'Graphics quality',
  qualityAuto: 'Automatic',
  spatialAudio: 'Sound',
  spatialAuto: 'Automatic',
  spatialHeadphones: 'Headphones (3D)',
  spatialSpeakers: 'Speakers (stereo)',
  qualityLow: 'Low',
  qualityMedium: 'Medium',
  qualityHigh: 'High',
  touchFire: 'Fire',
  touchAds: 'Aim',
  touchJump: 'Jump',
  touchCrouch: 'Crouch',
  touchReload: 'Reload',
  touchMelee: 'Knife',
  touchGrenade: 'Grenade',
  touchPause: 'Pause',
  touchBoard: 'Scoreboard',
  touchFullscreen: 'Fullscreen',
  tapToResume: 'Tap RESUME to return to the game',
  touchSensitivity: 'Touch sensitivity',
  touchScale: 'Button size',
  touchOpacity: 'Button opacity',
  aimAssist: 'Aim assist',
  adsHold: 'Hold to aim (off: tap toggles)',
  padSensitivity: 'Controller sensitivity',
  padToResume: 'Press {a} or {start} to return to the game',
  padLook: 'Look',
  padLeftStick: 'Left stick',
  padRightStick: 'Right stick',
  fullscreenOnPlay: 'Fullscreen when playing',
  editLayout: 'Arrange buttons',
  editLayoutDone: 'Done',
  editLayoutReset: 'Default positions',
  editLayoutHint: 'Drag the buttons wherever you like.',
  rotatePhone: 'Turn your phone sideways to play',
  fullscreen: 'Fullscreen',
  iosFullscreen: 'For fullscreen on iPhone: tap Share, then "Add to Home Screen".',
  tapHint: 'Tap',
  touchControlsHelp: 'Drag on the left to move (to the edge to sprint) · drag on the right to look · buttons to fire, aim, jump, crouch, reload, knife and grenade (hold to cook).',
  yourName: 'Your name',
  sexLabel: 'Sex',
  sexMale: '♂ Male',
  sexFemale: '♀ Female',
  playOnline: 'PLAY ONLINE',
  playOffline: 'Shooting range (static dummies)',
  playBots: 'VS BOTS',
  botSkill: 'Difficulty',
  mapLabel: 'Map',
  botCount: 'Bots',
  skillEasy: 'Easy',
  skillNormal: 'Normal',
  skillHard: 'Hard',
  botsSubtitle: 'Against {n} bots · free-for-all',
  sessions: 'Sessions',
  createSession: 'CREATE',
  sessionNamePlaceholder: 'New session name',
  back: 'Back',
  noSessions: 'No open sessions. Create the first one!',
  join: 'JOIN',
  full: 'FULL',
  joining: 'Joining…',
  connecting: 'Connecting to the server…',
  connectedAs: 'Connected as {name}.',
  disconnected: 'Lost connection to the server.',
  serverOffline: 'Server is down. Run "bun run server" (or play offline training).',
  needName: 'Pick a name first.',
  exitToHome: 'Back to home',
  scoreboard: 'Scoreboard',
  player: 'Player',
  deaths: 'Deaths',
  humiliationsShort: 'Humil.',
  killedBy: '{name} took you out',
  killedByWith: '{name} took you out with {weapon}',
  playerJoined: '{name} joined',
  playerLeft: '{name} left',
  keyChat: 'Room chat',
  chatPlaceholder: 'Message the room…',
  chatSend: 'Send',
  chatClose: 'Close chat',
  chatHint: 'Enter sends · Esc closes',
  chatMuted: 'Your chat was muted by the moderators.',
  chatSlow: 'Easy! Wait a little before sending another.',
  touchChat: 'Chat',
  lostConnection: 'No connection to the server',
  accountGuest: 'No account: training and bots are open. To play online, sign in or create an account.',
  signIn: 'SIGN IN',
  signUp: 'SIGN UP',
  profile: 'PROFILE',
  signOut: 'Sign out',
  email: 'E-mail',
  password: 'Password',
  gameName: 'In-game name',
  signInTitle: 'Sign in',
  signUpTitle: 'Create account',
  forgotTitle: 'Forgot password',
  resetTitle: 'New password',
  chooseNameTitle: 'Choose your in-game name',
  withDiscord: 'Sign in with Discord',
  forgotLink: 'Forgot password',
  haveAccount: 'I have an account',
  noAccount: 'Create an account',
  send: 'SEND',
  save: 'SAVE',
  resetSent: 'If that e-mail has an account, we sent a link valid for 24 hours.',
  resetDone: 'Password changed. Sign in with the new one.',
  needAccount: 'Sign in to play online.',
  passwordHint: '8 to 128 characters.',
  nameHint: '3 to 16 letters or numbers. Shown as Name#1234.',
  levelShort: 'Lv {level}',
  accountLevelUp: '🏅 Account level {level}!',
  sessionEnded: 'Your session ended (sign-out, password change, deletion or suspension).',
  connectedElsewhere: 'Your account joined the game somewhere else.',
  profileTitle: 'Profile',
  statsTitle: 'Stats',
  recentTitle: 'Recent sessions',
  noParticipations: 'No online matches yet.',
  statKills: 'Kills',
  statDeaths: 'Deaths',
  statHead: 'Headshots',
  statGroin: 'Below the belt',
  statKnife: 'Knife kills',
  statBackstab: 'Backstabs',
  statGrenade: 'Grenade kills',
  statHumiliations: 'Humiliations',
  statTime: 'Time played',
  statMatches: 'Sessions',
  customize: 'CUSTOMIZE CHARACTER',
  changeName: 'Change name',
  nameFreeAt: 'Next change available on {date}.',
  nameRule: 'The first change is free; then one every 7 days.',
  linkDiscord: 'Link Discord',
  unlinkDiscord: 'Unlink Discord',
  discordLinked: 'Discord linked.',
  deleteAccount: 'Delete account',
  deleteConfirm: 'Delete the account? You have 30 days to change your mind by signing in again. After that, name and e-mail are erased.',
  cancelDeletion: 'Cancel deletion',
  deletionPending: 'Account scheduled for deletion on {date}. Online play is blocked until you cancel.',
  saved: 'Saved.',
  errCredentials: 'Wrong e-mail or password.',
  errTooMany: 'Too many attempts. Wait a minute and try again.',
  errSuspended: 'This account is suspended.',
  errPendingDeletion: 'This account is scheduled for deletion. Cancel it in Profile to play online.',
  errEmailUsed: 'That e-mail already has an account. Sign in or use "Forgot password".',
  errEmailInvalid: 'Invalid e-mail.',
  errPasswordInvalid: 'The password needs 8 to 128 characters.',
  errNameInvalid: 'Invalid name: 3 to 16 letters or numbers.',
  errNameTaken: 'That name has no free numbers left. Try another.',
  errNameCooldown: 'You can change your name again on {date}.',
  errTokenInvalid: 'Invalid or expired link. Ask for another in "Forgot password".',
  errOnlyLogin: 'Discord is the only way into this account.',
  errDiscordUnavailable: 'Discord sign-in is not available at this address.',
  errDiscordLinked: 'That Discord is already linked to an account.',
  errUnauthorized: 'Please sign in again.',
  errOffline: 'Server is down. Run "bun run dev:online" (or play offline training).',
  errGeneric: 'Something went wrong. Try again.',
  onlineSubtitle: 'Session: {name} · free-for-all',
  gpuWarning:
    'Your browser is rendering the game without a graphics card (renderer: {gpu}), which caps it around 10 FPS. Enable “Use graphics acceleration when available” in chrome://settings/system (Edge: edge://settings/system) and restart the browser.',
};

export const TIPS = {
  'pt-BR': [
    'Dica: atirar no inimigo costuma funcionar melhor que atirar na parede.',
    'Dica: o boneco não revida. Ainda.',
    'Dica: cair de 7 metros dói. Pergunte ao seu joelho.',
    'Dica: mirar na cabeça dá o dobro de dano e o triplo de arrogância.',
    'Dica: correr e atirar ao mesmo tempo não é permitido. Sindicato dos braços.',
    'Dica: o caminhão de sorvete não vende sorvete. Mas toca música.',
    'Dica: os flamingos não têm culpa de nada.',
  ],
  en: [
    'Tip: shooting the enemy usually works better than shooting the wall.',
    "Tip: the dummy doesn't shoot back. Yet.",
    'Tip: falling 7 meters hurts. Ask your knees.',
    'Tip: headshots deal double damage and triple arrogance.',
    'Tip: no shooting while sprinting. Arm union rules.',
    "Tip: the ice cream truck doesn't sell ice cream. It does play music.",
    'Tip: the flamingos are innocent.',
  ],
};

/** One-tap chat lines (phones: no keyboard needed mid-fight). */
export const QUICK_CHAT = {
  'pt-BR': ['GG', 'Boa!', 'Kkkkk', 'Cuidado!', 'Bora x1?', 'Valeu!'],
  en: ['GG', 'Nice!', 'LOL', 'Watch out!', '1v1 me?', 'Thanks!'],
};

export const DEATH_MESSAGES = {
  'pt-BR': {
    fall: ['Você venceu a gravidade. Brincadeira, ela venceu.', 'Da próxima vez, tente cair de pé.', 'A calçada mandou lembranças.'],
    void: ['Você saiu do mapa. O mapa não sentiu sua falta.', 'Explorador corajoso. Explorador morto.'],
    explosion: ['Você cozinhou demais. A granada, e você.', 'Dica: a granada vai na direção do inimigo.'],
    dog: ['A Amora não gostou da visita.', 'Mordido pela Amora. Fofa, mas brava.', 'Quintal errado. Au.'],
  },
  en: {
    fall: ['You beat gravity. Just kidding, it beat you.', 'Next time, try landing on your feet.', 'The sidewalk says hi.'],
    void: ["You left the map. The map didn't miss you.", 'Brave explorer. Dead explorer.'],
    explosion: ['You overcooked it. The grenade, and yourself.', 'Tip: the grenade goes toward the enemy.'],
    dog: ['Amora did not like your visit.', 'Bitten by Amora. Fluffy, but grumpy.', 'Wrong yard. Woof.'],
  },
};

export type Lang = 'pt-BR' | 'en';
export type StringKey = keyof typeof ptBR;

let lang: Lang = navigator.language?.toLowerCase().startsWith('pt') ? 'pt-BR' : 'en';
const dicts: Record<Lang, Record<StringKey, string>> = { 'pt-BR': ptBR, en };

export function getLang(): Lang {
  return lang;
}

export function setLang(l: Lang) {
  lang = l;
}

export function t(key: StringKey, params: Record<string, string | number> = {}): string {
  return dicts[lang][key].replace(/\{(\w+)\}/g, (_, k) => String(params[k] ?? ''));
}

export function pick<T>(list: T[]): T {
  return list[(Math.random() * list.length) | 0];
}
