// German (informal "du"): the game's texts. The keys, pt-BR and en are in client/ui/strings.ts;
// the typecheck flags a key missing here. Translated adapting the humor the way the English does (PF-30).
import type { DeathLines, StringKey } from './strings';

export const de: Record<StringKey, string> = {
  title: 'OFFENSIVE COMBAT',
  subtitle: 'Shooter-Prototyp · Phase 1',
  play: 'SPIELEN',
  resume: 'ZURÜCK INS SPIEL',
  aimOnNextKey: 'Mit der nächsten Taste oder einem Klick kannst du wieder zielen',
  loading: 'Lädt',
  settings: 'Einstellungen',
  sensitivity: 'Empfindlichkeit',
  adsSensitivity: 'Empfindlichkeit beim Zielen',
  fov: 'Sichtfeld',
  volume: 'Lautstärke',
  invertY: 'Y-Achse invertieren',
  health: 'LEBEN',
  reload: 'NACHLADEN',
  noAmmo: 'KEINE MUNITION',
  reloading: 'LÄDT NACH…',
  points: 'Punkte',
  kills: 'Abschüsse',
  accuracy: 'Genauigkeit',
  you: 'Du',
  kill: 'Abschuss',
  headshot: 'Kopfschuss',
  longShot: 'Weitschuss',
  respawnIn: 'Respawn in {s}…',
  debugHint: 'F3 Debug · F4 Hitboxen und Collider (Figuren → Figuren + Assets → aus)',
  debugViewChars: 'F4: Hitboxen der Figuren',
  debugViewAll: 'F4: Figuren + Collider der Karte',
  debugViewOff: 'F4: visuelles Debugging aus',
  keyMove: 'Bewegen',
  keyJump: 'Springen',
  keyCrouch: 'Ducken (beim Sprinten: Rutschen)',
  keySprint: 'Sprinten',
  keyFire: 'Schießen',
  keyAds: 'Zielen',
  keyReload: 'Nachladen',
  keyPause: 'Menü',
  mouseLeft: 'Linksklick',
  mouseRight: 'Rechtsklick',
  keyMelee: 'Messerstich',
  keyTaunt: 'Demütigen (nahe einer Leiche)',
  keyDonate: 'Sargwaffe spenden (Zombies)',
  keyRefuse: 'Sargwaffe ablehnen (Zombies)',
  keyGrenade: 'Granate (halten zum Kochen)',
  keyForward: 'Vorwärts',
  keyBack: 'Rückwärts',
  keyLeft: 'Nach links',
  keyRight: 'Nach rechts',
  keyScoreboard: 'Punktetafel',
  keyPrimary: 'Primär',
  keyAlternate: 'Alternativ',
  keyPress: 'Drück eine Taste… (Esc bricht ab)',
  keyClear: 'Taste entfernen',
  keyUnbound: 'Keine Taste',
  keyMoved: '{key} lag auf „{action}“, dort fehlt jetzt eine Taste ({slot}).',
  keyNoCtrl: 'Strg lässt sich nicht belegen: Strg+W schließt den Browser-Tab.',
  keyFixed: '{key} ist fürs Debugging reserviert.',
  keyWheelHold: 'Das Mausrad lässt sich nicht gedrückt halten: Nimm es für Springen, Schießen, Nachladen, Messerstich, Granate, Demütigen oder Waffenwechsel.',
  keysReset: 'Standardtasten wiederherstellen',
  grenadeName: 'Granate',
  knife: 'Messerstich',
  knifeName: 'Messer',
  mineLimit: 'Maximal {n} Minen auf der Karte',
  cherryTaken: '🍒 Drachenkirsche: +{n} max. Leben für {s} s',
  cherryOver: 'Die Kirsche wirkt nicht mehr',
  koiXp: '🐟 Fisch erlegt: +{n} XP',
  goldenKoiXp: '✨ Goldener Koi: +{n} XP',
  goldenKoi: '✨ Goldener Koi! Adlerauge für {s} s',
  goldenKoiOver: 'Das Adlerauge vom Goldenen Koi ist verflogen',
  galleryAim: '🎯 Alle Ziele erwischt! Adlerauge für {s} s',
  humanityTaken: '🕯️ Menschlichkeit erhalten: +{n} max. Leben, bis du stirbst',
  biscuitTaken: '🦴 Scooby-Keks! Volles Leben. Scooby-Dooby-Doo!',
  promptPotion: 'Trank trinken',
  potion_pato: '🦆 Entengranaten, bis du stirbst!',
  potion_veloz: '💨 Eiltrank: {s} s lang schneller',
  potion_lerdo: '🐌 Schneckentrank: {s} s lang langsamer',
  potion_critico: '💀 Krit-Trank: {s} s lang ist jeder Schuss kritisch',
  potion_bebado: '🍺 Promilletrank: {s} s lang zielst du schief',
  potionOver: 'Der Trank wirkt nicht mehr',
  galleryAimOver: 'Das Adlerauge von der Schießbude ist verflogen',
  buffKoi: 'Koi-Blick',
  buffGallery: 'Adlerauge',
  buffCherry: 'Mehr Leben',
  buffHumanity: 'Menschlichkeit',
  buffDuck: 'Entengranaten',
  buffVeloz: 'Eile',
  buffLerdo: 'Schneckentempo',
  buffCritico: 'Krit-Schüsse',
  buffBebado: 'Beschwipst',
  buffUntilDeath: 'bis zum Tod',
  buffUntilMatchEnd: 'bis zum Matchende',
  arsenal: 'Arsenal',
  level: 'Level',
  locked: 'Gesperrt',
  xpToNext: 'Noch {xp} Punkte bis Level {level}',
  maxLevel: 'Höchstes Level! {xp} Punkte',
  unlockShort: 'noch {xp} Pkt.',
  // Weapons and their upgrades (ids from shared/data/progression.json): arma_<weapon>, upg_<weapon>_<id>, and
  // the description of each (armaDesc_, upgDesc_). client/tests/arsenalText.test.ts checks none is missing.
  arma_rifle: 'Standardgewehr',
  armaDesc_rifle: 'Das Übliche. Kimme, Korn und Gottvertrauen. Gut auf kurze Distanz, gut auf lange, glänzt auf keiner.',
  arma_pistola: 'Pistole des Pförtners',
  armaDesc_pistola: 'Zwölf Schuss und die volle Autorität der Hausverwaltung. Halbautomatisch: ein Klick, ein Schuss. Schnell aus dem Holster.',
  arma_smg: 'Mixer-MP',
  armaDesc_smg: 'Macht brrrrr und püriert alles. Spuckt aus der Nähe Blei und heult auf Distanz. Leichter: Damit rennst du schneller.',
  arma_grampeador: 'HR-Tacker',
  armaDesc_grampeador: 'Klack-klack-klack: drei Klammern pro Klick, direkt ins Memo. Gut auf kurze und mittlere Distanz, aber zwischen zwei Salven verschluckt er sich am Papier.',
  arma_revolver: 'Revolver des Linedance-Sheriffs',
  armaDesc_revolver: 'Von der Zwangshochzeit beim Scheunenfest: Damit bringt der Sheriff den Bräutigam zum Jawort. Sechs Kugeln, die hart reinhauen, aber die Trommel dreht sich langsam und Nachladen zieht sich wie eine Telenovela.',
  arma_furadeira: 'Sonntagsbohrer vom Nachbarn',
  armaDesc_furadeira: 'Sonntag, 8 Uhr früh, so viel zur Sonntagsruhe: brrrrrrr. Bohrt im Nu durch alles und weckt die ganze Straße, aber der Bohrer eiert und schafft es nicht mal bis zum Gartentor.',
  arma_garrucha: 'Doppelläufer des Cangaceiro',
  armaDesc_garrucha: 'Zwei Läufe, Lederhut und null Geduld. Aus nächster Nähe ist die Sache mit einem Schuss erledigt; auf Distanz ist es ein Schrotnieselregen, der nur kitzelt. Zwei Schuss, dann klappt er zum Nachladen auf.',
  arma_pistolao: 'Handkanone des Pumpers',
  armaDesc_pistolao: 'Hat dafür jeden Beintag geschwänzt. Haut rein wie ein Gewehr, ein Kopfschuss reicht, aber der Rückstoß reißt dein Zielen an die Decke, sie ist schwer und die sieben Kugeln sind schnell weg.',
  arma_faca: 'Küchenmesser',
  armaDesc_faca: 'Aus der Küche geliehen und nie zurückgebracht. Ein Stich, ein Abschuss.',
  arma_granada: 'Splittergranate',
  armaDesc_granada: 'Explodiert beim ersten Kontakt. Kochst du sie zu lange, geht sie in deiner Hand hoch.',
  // The old rifles and knives (they use the rifle's and the knife's points and upgrades).
  arma_rifleFita: 'Panzertape-Gewehr',
  armaDesc_rifleFita: 'Halb Panzertape, halb Mut. Lädt schnell nach, aber das Tape löst sich und der Rückstoß springt stärker.',
  arma_rifleTia: 'Gewehr der WhatsApp-Tante',
  armaDesc_rifleTia: 'Rosa, mit Blümchen-Aufkleber. Guten Morgen, ihr Lieben! Schießt schneller und zielt im Nu, aber jede Kugel haut etwas weniger rein.',
  arma_rifleNatal: 'Lichterketten-Gewehr',
  armaDesc_rifleNatal: 'Mit Lichterkette umwickelt. Viel sanfterer Rückstoß, aber Lichterketten haben keine Eile: schießt langsamer.',
  arma_rifleChama: 'Getuntes Flammen-Gewehr',
  armaDesc_rifleChama: 'Flammen-Aufkleber bringen +10 PS, weiß doch jeder. Schießt schneller und du rennst schneller, aber die Kugeln streuen.',
  arma_rifleVovo: 'Opas Gewehr',
  armaDesc_rifleVovo: 'Lackiertes Holz, aus der Zeit, als Gewehre noch was aushielten. Haut hart rein, ist aber langsam beim Schießen und beim Zielen.',
  arma_rifleOuro: 'Protz-Goldgewehr',
  armaDesc_rifleOuro: "Komplett aus Gold, mit 40er-Magazin. Passt zu nichts, und genau darum geht's. Schwer: Du läufst und lädst langsamer nach.",
  arma_colher: 'Omas Kochlöffel',
  armaDesc_colher: 'Wer schon mal einen abgekriegt hat, weiß: Der ist tödlich. Etwas mehr Reichweite, etwas langsamere Hiebe.',
  arma_frango: 'Gummihuhn',
  armaDesc_frango: 'Drück drauf und es kreischt. Viel längerer Vorstoß, aber jeder hört das Kreischen schon von Weitem.',
  arma_baguete: 'Altbackenes Baguette',
  armaDesc_baguete: 'Steinhart seit gestern. Außen knusprig, innen tödlich. Mehr Reichweite, langsamere Hiebe.',
  arma_peixe: 'Tiefkühlfisch',
  armaDesc_peixe: 'Direkt aus der Tiefkühltruhe. Langer Vorstoß, aber die eiskalte Backpfeife lässt auf sich warten.',
  arma_macarrao: 'Schwimmnudel',
  armaDesc_macarrao: '60 Zentimeter Schaumstoff. Sieht harmlos aus. Ist es nicht. Große Reichweite, aber langsam und mit kurzem Vorstoß.',
  arma_sabre: 'Billig-Lichtschwert',
  armaDesc_sabre: 'Vom Ramschmarkt. Die größte Reichweite von allen, und es macht wuuum (das hört jeder). Schwache Batterien: mehr Zeit zwischen den Hieben.',
  // A progression's short name ("faltam 600 pts de faca").
  prog_rifle: 'Gewehr',
  prog_pistola: 'Pistole',
  prog_smg: 'MP',
  prog_faca: 'Messer',
  prog_granada: 'Granate',
  upg_rifle_pontoVermelho: 'Flohmarkt-Rotpunkt',
  upgDesc_rifle_pontoVermelho: 'Vom Straßenhändler, aber der Punkt leuchtet tatsächlich. Ruhigeres Zielen und etwas Zoom.',
  upg_rifle_empunhadura: 'Besenstiel-Vordergriff',
  upgDesc_rifle_empunhadura: 'Ein Besenstiel, mit Kabelbindern unter den Lauf geschnallt. Bändigt den Rückstoß und bündelt die Streuung.',
  upg_rifle_luneta: 'Opas Zielfernrohr (3x)',
  upgDesc_rifle_luneta: 'Das Messing-Zielfernrohr, mit dem Opa die Nachbarn ausspioniert hat. 3x-Zoom und Präzision auf Distanz, aber das Zielen dauert und die Waffe wird schwer. Ersetzt den Rotpunkt.',
  upg_rifle_pente: 'Doppelmagazin mit Panzertape',
  upgDesc_rifle_pente: 'Zwei Magazine mit Tape zusammengeklebt: zehn Schuss mehr und schnelleres Nachladen.',
  upg_rifle_silenciador: 'Pfandflaschen-Schalldämpfer',
  upgDesc_rifle_silenciador: 'Eine 2-Liter-Flasche auf dem Lauf. Nur wer in der Nähe ist, hört den Schuss, und niemand sieht die Leuchtspur. Dafür weniger Schaden und Reichweite.',
  upg_rifle_holoLupa: 'Holo mit Lupe (1,5x)',
  upgDesc_rifle_holoLupa: 'Das Smiley-Holo mit einer Klapplupe dahinter. 1,5x-Zoom und ruhigeres Zielen; das Zielen dauert einen Tick länger.',
  upg_rifle_luneta2x: '2x-Zielfernrohr',
  upgDesc_rifle_luneta2x: 'Ein kurzes Messing-Zielfernrohr. 2x-Zoom und mehr Reichweite; zielt langsamer und wiegt etwas.',
  upg_rifle_luneta4x: '4x-Zielfernrohr',
  upgDesc_rifle_luneta4x: 'Das lange Zielfernrohr aus dem Schaufenster. 4x-Zoom und viel Reichweite; das Zielen dauert und das Gewehr wird schwer.',
  upg_pistola_gatilho: 'Arcade-Abzug',
  upgDesc_pistola_gatilho: 'Aus einem Spielautomaten gerissen: Du kannst viel schneller klicken.',
  upg_pistola_pontoVermelho: 'Mini-Rotpunkt',
  upgDesc_pistola_pontoVermelho: 'Winzig, aber ehrlich. Beim Zielen viel präziser.',
  upg_pistola_coldre: 'Klett-Holster',
  upgDesc_pistola_coldre: 'In der halben Zeit aus dem Holster, und das Magazin wechselt auch schneller.',
  upg_pistola_batata: 'Kartoffel-Schalldämpfer',
  upgDesc_pistola_batata: 'Eine Kartoffel auf der Mündung. Klappt im Film, klappt auch hier: gedämpfte Schüsse, keine Leuchtspur und weniger Rückstoß. Dafür etwas weniger Schaden.',
  upg_smg_motor: 'Turbo-Mixermotor',
  upgDesc_smg_motor: 'Mixerstufe 5: mehr Schuss pro Sekunde.',
  upg_smg_holo: 'Smiley-Holo der WhatsApp-Tante',
  upgDesc_smg_holo: 'Ein Smiley schwebt im Visier. Guten Morgen, ihr Lieben! Präziser beim Zielen und aus der Hüfte.',
  upg_smg_tambor: 'Popcorn-Trommelmagazin',
  upgDesc_smg_tambor: '18 Schuss mehr in einer Popcornmaschinen-Trommel. Dafür dauern Nachladen und Waffenwechsel länger und du läufst etwas langsamer.',
  upg_smg_coronha: 'Gartenschlauch-Schaft',
  upgDesc_smg_coronha: 'Ein Gartenschlauch, an der Schulter aufgerollt. Weniger Rückstoß und weniger Streuung.',
  upg_faca_afiador: 'Schleifer vom Wochenmarkt',
  upgDesc_faca_afiador: "Der Typ vom Wochenmarkt hat's umsonst geschliffen. Schnellere Folgestiche und etwas mehr Reichweite.",
  upg_faca_tenis: 'Sprungfeder-Sneaker',
  upgDesc_faca_tenis: 'Sneaker mit Federn in der Sohle: Der Vorstoß geht weiter und schneller.',
  upg_faca_maoLeve: 'Flinke Hand',
  upgDesc_faca_maoLeve: 'Schneller Hieb ohne Getue: Er ist früher vorbei und die Waffe ist eher wieder schussbereit.',
  // Each knife's passive (shared/data/weapons/<faca>.json "passiva"), in the Arsenal and when it kicks in.
  passiva_discreta: 'Diskret',
  passivaDesc_discreta: 'Den Hieb hört man nur aus der Nähe.',
  passiva_coloDeVo: 'Omas Schoß',
  passivaDesc_coloDeVo: 'Jeder Abschuss damit gibt dir {vida} Leben zurück.',
  passiva_fugaEscandalosa: 'Kreischende Flucht',
  passivaDesc_fugaEscandalosa: 'Nach einem Abschuss damit rennst du {s} s lang {pct}% schneller.',
  passiva_lanche: 'Brotzeit',
  passivaDesc_lanche: 'Jeder Abschuss damit füllt das Magazin der Waffe in deiner Hand.',
  passiva_tapaGelado: 'Eiskalte Backpfeife',
  passivaDesc_tapaGelado: 'Ein Stich in den Rücken bringt +{pts} Pkt. statt +{base}.',
  passiva_boia: 'Schwimmreifen',
  passivaDesc_boia: 'Solange sie ausgerüstet ist, nimmst du keinen Fallschaden.',
  passiva_vuuum: 'Wuuum',
  passivaDesc_vuuum: 'Der Hieb trifft alle in Reichweite vor dir, nicht nur einen.',
  knifePassive: 'Passive: {name}',
  knifePassiveWhere: 'Gilt bei Jeder gegen jeden, im Training und gegen Bots.',
  passiveFx_coloDeVo: '🥄 Omas Schoß: +{vida} Leben',
  passiveFx_fugaEscandalosa: '🐔 Kreischende Flucht!',
  passiveFx_lanche: '🥖 Brotzeit: Magazin voll',
  upg_granada_mina: 'Landmine',
  upgDesc_granada_mina: 'G legt eine Mine auf den Boden, statt zu werfen. Nach 1 s scharf, explodiert, wenn ein Gegner in die Nähe tritt. Verschwindet bei deinem Respawn.',
  upg_granada_dupla: 'Doppelpack',
  upgDesc_granada_dupla: 'Ein G, zwei Granaten: wirft eine und gleich danach die nächste, für nur eine Ladung.',
  upg_granada_cinto: 'Granatengürtel der Tante',
  upgDesc_granada_cinto: 'Eine Granate mehr pro Leben. Die Tante hat immer eine in Reserve.',
  upg_granada_polvora: 'Silvester-Schießpulver',
  upgDesc_granada_polvora: 'Pulver aus Silvesterböllern: Die Explosion reicht 20% weiter.',
  // What an upgrade changes, as chips in the Arsenal ({v}: "+15%", "+10", "2,6").
  fx_dano: 'Schaden {v}',
  fx_alcance: 'Reichweite {v}',
  fx_cadencia: 'Feuerrate {v}',
  fx_pente: 'Magazin {v}',
  fx_recarga: 'Nachladen {v}',
  fx_dispersao: 'Streuung {v}',
  fx_mirando: 'Streuung beim Zielen {v}',
  fx_recuo: 'Rückstoß {v}',
  fx_adsTempo: 'Zielzeit {v}',
  fx_zoom: 'Zoom {v}x',
  fx_movimento: 'Mobilität {v}',
  fx_troca: 'Wechselzeit {v}',
  fx_silenciador: 'Gedämpfte Schüsse',
  fx_golpe: 'Hiebreichweite {v} m',
  fx_investida: 'Vorstoß {v} m',
  fx_intervalo: 'Zeit zwischen Hieben {v}',
  fx_impulso: 'Vorstoßtempo {v}',
  fx_duracao: 'Hiebdauer {v}',
  fx_granadas: 'Granaten {v}',
  fx_recargaGranada: 'Granaten-Aufladung {v}',
  fx_raio: 'Explosionsradius {v}',
  fx_lancamento: 'Wurf {v}',
  fx_tipo_mina: 'G legt eine Mine',
  fx_tipo_dupla: 'G wirft zwei',
  // The Arsenal tree (client/ui/arsenal.ts): one row per slot.
  treeRow_primaria: 'Primär',
  treeRow_secundaria: 'Sekundär',
  treeRow_faca: 'Messer',
  treeRow_granada: 'Granate',
  treeEquip: 'Ausrüsten',
  treeEquipped: 'Ausgerüstet',
  treeWeaponLocked: 'noch {xp} {prog}-Pkt.',
  treeWeaponLockedLong: 'Gesperrt: frei ab {total} {prog}-Punkten. Noch {xp}.',
  weaponUnlocked: '{weapon} freigeschaltet: jetzt im Arsenal ausrüsten',
  arsenalSaveFailed: 'Arsenal konnte nicht gespeichert werden',
  upgradeOn: 'An',
  upgradeOff: 'Aus',
  upgradeReplacedBy: 'Ersetzt durch {upgrade}',
  upgradeOptional: 'Optional: mit Nachteil',
  upgradeUnlocked: '{weapon} Level {level}: {upgrade}!',
  upgradeTurnOn: 'Im Arsenal einschalten',
  statDamage: 'Schaden',
  statRate: 'Feuerrate',
  statAccuracy: 'Genauigkeit',
  statRange: 'Reichweite',
  statMobility: 'Mobilität',
  statMag: 'Magazin {mag} / Reserve {reserve}',
  statSwingReach: 'Hiebreichweite',
  statLunge: 'Vorstoß',
  statSwingSpeed: 'Tempo',
  statStealth: 'Tarnung',
  // The Arsenal canvas of the home (client/ui/arsenalCanvas.ts): a frame per slot, the panel, the zoom bar.
  arsenalCanvasHint: 'Zieh zum Verschieben und zoome mit dem Mausrad. Klick auf eine Waffe, um ihre Details zu sehen.',
  arsenalCanvasHintTouch: 'Zieh zum Verschieben und zoome mit zwei Fingern. Tippe auf eine Waffe, um ihre Details zu sehen.',
  cvLegendLocked: 'Gesperrt',
  cvRow_primaria: 'Primär',
  cvRow_secundaria: 'Sekundär',
  cvRow_faca: 'Nahkampf',
  cvRow_granada: 'Wurfwaffe',
  cvSlot_primaria: 'Primär',
  cvSlot_secundaria: 'Sekundär',
  cvSlot_faca: 'Nahkampf',
  cvSlot_granada: 'Wurfwaffe',
  cvFrameEquipped: 'Ausgerüstet: {weapon}',
  cvUpgRow_mira: 'Visiere',
  cvUpgRow_modo: 'Modus',
  cvUpgRow_resto: 'Upgrades',
  cvAlwaysEquipped: 'Immer ausgerüstet',
  cvEquipSecondary: 'Als Sekundärwaffe mitnehmen',
  cvYourSecondary: 'Deine Sekundärwaffe',
  cvProgress: 'Fortschritt',
  cvUpgrades: 'Upgrades',
  cvOnCount: '{n} von {total} an',
  cvOptional: 'Optional',
  cvWeaponLocked: 'Waffe gesperrt',
  cvUnlockWeaponFirst: 'Schalte zuerst die Waffe frei',
  cvToggleOn: 'An · tippen zum Ausschalten',
  cvToggleOff: 'Aus · tippen zum Einschalten',
  cvPickUpgrade: 'Klick auf ein Upgrade im Baum, um zu sehen, was es ändert. Jedes hat einen Knopf, mit dem du es direkt hier an- oder ausschaltest.',
  cvFitAll: 'Alles zeigen',
  cvFitTitle: 'Alles zeigen (0)',
  cvZoomIn: 'Reinzoomen (+)',
  cvZoomOut: 'Rauszoomen (−)',
  cvClose: 'Schließen (Esc)',
  keyWeapon1: 'Primärwaffe',
  keyWeapon2: 'Sekundärwaffe',
  keySwapWeapon: 'Waffe wechseln',
  touchSwap: 'Waffe wechseln',
  dogBite: 'Biss',
  backstab: 'Hinterrücks',
  groin: 'In die Kronjuwelen',
  groinBanner: 'IN DIE KRONJUWELEN!',
  humiliation: 'Demütigung',
  humiliatedBanner: 'GEDEMÜTIGT!',
  danceName: 'Siegestänzchen',
  promptTaunt: '{name} demütigen',
  dancing: 'Demütige {name}…',
  quality: 'Grafikqualität',
  qualityAuto: 'Automatisch',
  spatialAudio: 'Ton',
  spatialAuto: 'Automatisch',
  spatialHeadphones: 'Kopfhörer (3D)',
  spatialSpeakers: 'Lautsprecher (Stereo)',
  qualityLow: 'Niedrig',
  qualityMedium: 'Mittel',
  qualityHigh: 'Hoch',
  touchFire: 'Schießen',
  touchAds: 'Zielen',
  touchJump: 'Springen',
  touchCrouch: 'Ducken',
  touchReload: 'Nachladen',
  touchMelee: 'Messer',
  touchGrenade: 'Granate',
  touchPause: 'Pause',
  touchBoard: 'Punktetafel',
  touchFullscreen: 'Vollbild',
  touchSensitivity: 'Touch-Empfindlichkeit',
  touchScale: 'Knopfgröße',
  touchOpacity: 'Knopf-Deckkraft',
  aimAssist: 'Zielhilfe',
  adsHold: 'Halten zum Zielen (aus: Tippen schaltet um)',
  padSensitivity: 'Controller-Empfindlichkeit',
  padLook: 'Umsehen',
  padLeftStick: 'Linker Stick',
  padRightStick: 'Rechter Stick',
  fullscreenOnPlay: 'Vollbild beim Spielen',
  editLayout: 'Knöpfe anordnen',
  editLayoutDone: 'Fertig',
  editLayoutReset: 'Standardpositionen',
  editLayoutHint: 'Zieh die Knöpfe, wohin du willst.',
  rotatePhone: 'Dreh dein Handy quer zum Spielen',
  fullscreen: 'Vollbild',
  iosFullscreen: 'Vollbild auf dem iPhone: Tippe auf „Teilen“ und dann auf „Zum Home-Bildschirm“.',
  tapHint: 'Tippen',
  touchControlsHelp: 'Links ziehen zum Laufen (bis zum Rand zum Sprinten) · rechts ziehen zum Umsehen · Knöpfe zum Schießen, Zielen, Springen, Ducken, Nachladen, für Messer und Granate (halten zum Kochen).',
  yourName: 'Dein Name',
  sexLabel: 'Geschlecht',
  sexMale: '♂ Männlich',
  sexFemale: '♀ Weiblich',
  playOnline: 'ONLINE SPIELEN',
  playOffline: 'Schießstand (stehende Zielpuppen)',
  playBots: 'GEGEN BOTS',
  botSkill: 'Schwierigkeit',
  mapLabel: 'Karte',
  botCount: 'Bots',
  skillEasy: 'Leicht',
  skillNormal: 'Normal',
  skillHard: 'Schwer',
  botsSubtitle: 'Gegen {n} Bots · {mode}',
  sessions: 'Sessions',
  createSession: 'ERSTELLEN',
  sessionNamePlaceholder: 'Name der neuen Session',
  back: 'Zurück',
  noSessions: 'Keine offenen Sessions. Erstell die erste!',
  join: 'BEITRETEN',
  full: 'VOLL',
  joining: 'Trete bei…',
  connecting: 'Verbinde mit dem Server…',
  connectedAs: 'Verbunden als {name}.',
  disconnected: 'Verbindung zum Server verloren.',
  serverOffline: 'Server ist offline. Starte „bun run server“ (oder spiel das Offline-Training).',
  needName: 'Wähl zuerst einen Namen.',
  exitToHome: 'Zurück zum Start',
  backToEditor: 'Zurück zum Editor (Stop)',
  scoreboard: 'Punktetafel',
  player: 'Spieler',
  deaths: 'Tode',
  humiliationsShort: 'Demüt.',
  killedBy: '{name} hat dich erledigt',
  killedByWith: '{name} hat dich mit {weapon} erledigt',
  playerJoined: '{name} ist beigetreten',
  playerLeft: '{name} ist gegangen',
  keyChat: 'Session-Chat',
  chatPlaceholder: 'Nachricht an die Session…',
  chatSend: 'Senden',
  chatClose: 'Schließen',
  chatHint: 'Enter sendet · Esc schließt',
  chatMuted: 'Dein Chat wurde von der Moderation stummgeschaltet.',
  chatSlow: 'Immer mit der Ruhe! Warte kurz vor der nächsten Nachricht.',
  touchChat: 'Chat',
  lostConnection: 'Keine Verbindung zum Server',
  accountGuest: 'Ohne Konto: Training und Bots sind frei. Um online zu spielen, melde dich an oder erstelle ein Konto.',
  signIn: 'ANMELDEN',
  signUp: 'KONTO ERSTELLEN',
  profile: 'PROFIL',
  signOut: 'Abmelden',
  email: 'E-Mail',
  password: 'Passwort',
  gameName: 'Spielername',
  signInTitle: 'Anmelden',
  signUpTitle: 'Konto erstellen',
  forgotTitle: 'Passwort vergessen',
  resetTitle: 'Neues Passwort',
  chooseNameTitle: 'Wähl deinen Spielernamen',
  withDiscord: 'Mit Discord anmelden',
  forgotLink: 'Passwort vergessen',
  haveAccount: 'Ich habe schon ein Konto',
  noAccount: 'Ein Konto erstellen',
  send: 'SENDEN',
  save: 'SPEICHERN',
  resetSent: 'Falls es zu dieser E-Mail ein Konto gibt, haben wir dir einen Link geschickt, der 24 Stunden gilt.',
  resetDone: 'Passwort geändert. Melde dich mit dem neuen an.',
  needAccount: 'Melde dich an, um online zu spielen.',
  // Home: signed-in tabs
  tabPlay: 'SPIELEN',
  tabArsenal: 'ARSENAL',
  tabAlbum: 'ALBUM',
  tabProfile: 'PROFIL',
  tabSettings: 'EINSTELLUNGEN',
  customizeShort: 'ANPASSEN',
  equippedLine: '{icons} ausgerüstet',
  profileLine: '{kills} Abschüsse · {matches} Matches',
  modeTitle: 'Modus',
  modeOnline: 'Online',
  modeOnlineDesc: 'Jeder gegen jeden, Waffenrennen oder Zombies im Team, mit bis zu 9 Leuten. Bringt Konto-XP.',
  modeBots: 'Gegen Bots',
  modeBotsDesc: 'Du und 3 bis 9 Bots, ganz wie du willst, oder allein gegen die Horde.',
  modeRange: 'Schießstand',
  modeRangeDesc: 'Zielpuppen, an denen du Zielen und Waffen testen kannst.',
  mapFilterTitle: 'Nach Karte filtern',
  mapFilterHint: 'Hak die Karten an, die du sehen willst',
  mapHintBots: 'Danach Schwierigkeit und Bots wählen',
  // Game modes (shared/modes.ts): gameMode_<id> and gameModeDesc_<id>.
  gameModeTitle: 'Matchtyp',
  'gameMode_mata-mata': 'Jeder gegen jeden',
  'gameModeDesc_mata-mata': 'Alle gegen alle, mit deinem Arsenal, das du vor dem Beitritt wählst.',
  'gameMode_corrida-armada': 'Waffenrennen',
  'gameModeDesc_corrida-armada': '3 Abschüsse bringen dich eine Waffe weiter; wer abgestochen wird, verliert einen. Ein Abschuss mit dem Lichtschwert gewinnt.',
  gameMode_zumbi: 'Zombies',
  gameModeDesc_zumbi: 'Im Team gegen 12 Zombiewellen und 3 Bosse auf dem Kapellenfriedhof. Jeder Abschuss bringt XP und Geld; gib es am Mysteriösen Sarg und für Barrikaden aus, die entscheiden, wo die Horde reinkommt.',
  // Zumbi (shared/zombies.ts): zombies (ztype_<kind>), bosses (zboss_<id>), the coffin's items (zitem_<id>),
  // rarities (rar_<id>), the HUD, the coffin, revives and the end-of-match summary.
  ztype_comum: 'Zombie',
  ztype_corredor: 'Marathonläufer',
  ztype_inchado: 'Grillonkel',
  ztype_brutamontes: 'Türsteher',
  ztype_cuspidor: 'Klatschtante',
  zboss_coveiro: 'Der Totengräber',
  zboss_noiva: 'Die Braut',
  zboss_prefeito: 'Der Bürgermeister',
  zbossIntro_coveiro: 'DER TOTENGRÄBER BUDDELT SICH RAUS!',
  zbossIntro_noiva: 'DIE BRAUT WURDE AM ALTAR SITZEN GELASSEN…',
  zbossIntro_prefeito: 'DER BÜRGERMEISTER WILL DEINE STIMME!',
  zitem_riflePadrao: 'Standardgewehr',
  zitem_pistolaInicial: 'Pistole des Pförtners',
  zitem_rifleMira: 'Rotpunkt-Gewehr',
  zitem_rifleSilencioso: 'Flüstergewehr',
  zitem_pistola: 'Pistole des Pförtners',
  zitem_pistolaBatata: 'Kartoffelpistole',
  zitem_liquidificador: 'Mixer',
  zitem_grampeador: 'HR-Tacker',
  zitem_revolver: 'Revolver des Linedance-Sheriffs',
  zitem_furadeira: 'Sonntagsbohrer vom Nachbarn',
  zitem_garrucha: 'Doppelläufer des Cangaceiro',
  zitem_pistolao: 'Handkanone des Pumpers',
  zitem_rifleFirme: 'Stabiles Gewehr',
  zitem_rifleVovo: 'Opas Gewehr',
  zitem_pistolaLigeira: 'Flinke Pistole',
  zitem_liquidificadorMotor: 'Motor-Mixer',
  zitem_rifleRemendado: 'Geflicktes Gewehr',
  zitem_liquidificadorTurbo: 'Turbo-Mixer',
  zitem_liquidificadorPipoca: 'Popcorn-Mixer',
  zitem_rifleCompleto: 'Voll ausgestattetes Gewehr',
  zitem_liquidificadorSupremo: 'Mega-Mixer',
  zitem_sabre: 'Billig-Lichtschwert',
  rar_inicial: 'Basis',
  rar_comum: 'Gewöhnlich',
  rar_raro: 'Selten',
  rar_epico: 'Episch',
  rar_lendario: 'Legendär',
  zWave: 'WELLE {n}/{total}',
  zLeft: '{n} Zombies',
  zLeftOne: '1 Zombie',
  zCountdown: 'DIE HORDE KOMMT',
  zCountdownSub: 'in {s}s · finde den Sarg!',
  zBreak: 'PAUSE',
  zBreakSub: 'nächste Welle in {s}s',
  zWaiting: 'Warte auf Spieler',
  zOver: 'MATCH VORBEI',
  zWaveBanner: 'WELLE {n}',
  zLastWave: 'LETZTE WELLE!',
  zBreakBanner: 'Welle {n} geschafft! Munition und Granaten aufgefüllt',
  zBossDown: '{boss} IST ERLEDIGT!',
  zAssist: 'Assist',
  zRevive: 'Wiederbelebt',
  zWaveBonus: 'Welle geschafft',
  zBossReward: 'Boss besiegt',
  zBlast: 'Explosion',
  zBoxBuy: 'Mysteriöser Sarg: Zufallswaffe für ${cost}',
  zTotemBuy: 'Totem: Entzünde die Pausenlose Totenwache für ${cost} (keine Pausen bis zum Ende, +20% Geld und +10% XP)',
  zTotemPoor: 'Totem: Pausenlose Totenwache für ${cost} (du hast ${money})',
  zTotemLit: 'Die Pausenlose Totenwache brennt: keine Pausen bis zum Matchende',
  zTotemOn: '{name} hat die Pausenlose Totenwache entzündet! Keine Pausen bis zum Ende',
  zBoxPoor: 'Mysteriöser Sarg: ${cost} (du hast ${money})',
  zBoxSpinning: 'Dreht sich…',
  zBoxTake: '{item} nehmen ({rarity})',
  zBoxOther: '{name} wählt gerade eine Waffe',
  zBoxDonateKey: '[{key}] spenden',
  zBoxRefuseKey: '[{key}] ablehnen',
  zBoxTakeDonated: '{take} · gespendet von {name}',
  zBoxYouDonated: 'Du hast {item} gespendet: Jeder andere darf zugreifen',
  zBoxDonatedNotice: '{name} hat {item} ({rarity}) in den Sarg gelegt: Wer will, greift zu!',
  zBoxGot: 'Du hast {item} ({rarity}) bekommen',
  zBoxTakeDamaged: '{item} ({rarity}) nehmen · BESCHÄDIGT: {flaw}',
  zBoxGotDamaged: 'Du hast {item} ({rarity}) bekommen · BESCHÄDIGT',
  zBoxDamagedOffer: 'Kam BESCHÄDIGT raus: {flaw}',
  zDamaged: 'Beschädigt',
  zFlaw_municao: 'weniger Munition',
  zFlaw_dano: 'weniger Schaden',
  zFlaw_ambos: 'weniger Munition und Schaden',
  zFlawAmmo: '−{p}% Magazin und −{r}% Reserve',
  zFlawDamage: '−{d}% Schaden',
  zgap_portao: 'Haupttor',
  zgap_oeste: 'Westlücke',
  zgap_leste: 'Ostlücke',
  zgap_noroeste: 'Nordwestlücke',
  zgap_nordeste: 'Nordostlücke',
  zBarBuild: 'Gedrückt halten, um die Barrikade zu bauen: {gap} (${cost})',
  zBarPoor: 'Barrikade: ${cost} (du hast ${money})',
  zBarBuilding: 'Barrikade wird gebaut…',
  zBarRepair: 'Gedrückt halten, um Bretter anzunageln ({n}/{max})',
  zBarRepairing: 'Bretter werden angenagelt ({n}/{max})…',
  zBarBlocked: 'Durchgang besetzt: Niemand darf in der Lücke stehen',
  zBarNail: 'Brett angenagelt',
  zBarBuilt: '{name} hat die Barrikade gebaut: {gap}',
  zBarBroken: 'Barrikade durchbrochen: {gap}!',
  zRevivePrompt: 'Gedrückt halten, um {name} wiederzubeleben',
  zReviving: 'Belebe {name} wieder…',
  zBeingRevived: '{name} belebt dich wieder!',
  zDownTitle: 'AM BODEN!',
  zDownSub: 'Ein Freund kann dich wiederbeleben · du verblutest in {s}s',
  zTeammateDown: '{name} ist am Boden! Los, wiederbeleben',
  zRevived: '{name} hat {who} wiederbelebt',
  zBledOut: '{name} ist verblutet',
  zDeadWait: 'Du kommst in der Pause zurück (ohne die Waffen aus dem Sarg)',
  zJoinWaitTitle: 'Welle läuft',
  zJoinWait: 'Du steigst ein, sobald diese Welle vorbei ist',
  zSpectating: 'ZUSCHAUER',
  zProfaneYou: 'SAKRILEG! Die ganze Horde ist hinter dir her',
  zProfaneHint: 'Niemand steigt auf den Altar: {s} s lang jagt dich jeder Zombie',
  zProfaned: '{name} hat den Altar entweiht und ist {s} s lang das Ziel der Horde',
  zCrowsYou: 'KRÄHEN! Runter vom Baum',
  zCrowsHint: 'Sie picken, solange du auf dem Baum bist, und noch {s} s danach',
  buffProfaned: 'Entweiht',
  buffCrows: 'Krähen',
  buffCrowsUntil: 'auf dem Baum und {s} s danach',
  zSpecHealth: '{hp} Leben',
  zSpecDown: 'Am Boden: braucht Hilfe!',
  zSpecKeys: '[{prev}] vorheriger · [{next}] nächster',
  zJump: 'SPRING ÜBER DIE DRUCKWELLE!',
  zWon: 'IHR HABT DIE HORDE ÜBERLEBT!',
  zLost: 'DIE HORDE HAT GEWONNEN',
  zSumSub: 'Welle {wave} von {total} · {time}',
  zSumNext: 'Neues Match in {s}s…',
  zColKills: 'Abschüsse',
  zColHead: 'Kopfschüsse',
  zColEarned: 'Geld',
  zColDowns: 'Am Boden',
  zColRevives: 'Wiederbelebt',
  zColXp: 'XP',
  zColMoney: 'Geld',
  zArsenalTitle: 'Mysteriöser Sarg',
  zArsenalCarry: 'Du trägst',
  zSolo: 'ALLEIN GEGEN DIE HORDE',
  zMapOnly: 'Nur auf dem Kapellenfriedhof',
  buffChilled: 'Gänsehaut',
  buffVigil: 'Endlose Mahnwache',
  buffBleeding: 'Blutung',
  zThorns: 'Dornen! Wer aufs Gitter oder in die Hecke klettert, blutet.',
  zGhostsYou: 'Der Grabstein ist beleidigt!',
  zGhostsHint: '👻 Gespenster sind {s} s lang hinter dir her: Messer oder Granate verscheuchen sie',
  // Mata-mata: the loadout is locked once the match starts.
  upgradeNextMatch: 'Gilt ab dem nächsten Match',
  upgradeTurnOnNext: 'Aktivier es vor dem nächsten Match im Arsenal',
  // Corrida armada: the ladder (ids from shared/data/corrida_armada.json: ladder_<id>), HUD and rounds.
  ladderTitle: 'Waffenrennen-Leiter',
  ladderHud: 'WAFFE {n}/{total}',
  ladderStep: 'Stufe {n}',
  ladderFinalKills: 'letzter Abschuss',
  ladderNext: 'Nächste Waffe: {weapon}!',
  ladderDown: 'Abgestochen! Zurück zu {weapon}',
  ladderLostKill: 'Abgestochen! Ein Abschuss weniger ({n}/{total})',
  ladderFinal: 'LICHTSCHWERT! Ein Abschuss damit gewinnt',
  ladder_rifleCompleto: 'Voll ausgestattetes Gewehr',
  ladder_smgTurbo: 'Turbo-Mixer',
  ladder_rifleLuneta: 'Zielfernrohr-Gewehr',
  ladder_rifleSilenciado: 'Schallgedämpftes Gewehr',
  ladder_garrucha: 'Doppelläufer des Cangaceiro',
  ladder_grampeador: 'HR-Tacker',
  ladder_pistolaRapida: 'Flinke Pistole',
  ladder_pistolaBatata: 'Kartoffelpistole',
  ladder_sabre: 'Lichtschwert',
  roundWinner: '{name} hat das Waffenrennen gewonnen!',
  roundYouWon: 'DU HAST DAS WAFFENRENNEN GEWONNEN!',
  roundNext: 'Neue Runde in {s}…',
  roundStart: 'Neue Runde: alle zurück zur ersten Waffe!',
  ladderShort: 'Waffe',
  mapHintRange: 'Klick auf eine Karte und das Training startet sofort',
  sessionsOne: '1 Session',
  sessionsMany: '{n} Sessions',
  quickJoinHint: 'Springt direkt in die vollste Session der gefilterten Karten',
  openSessions: 'Offene Sessions ({n})',
  moreSessions: 'MEHR ANZEIGEN ({n})',
  noSessionsFiltered: 'Keine offene Session auf den gewählten Karten.',
  pickAMap: 'Wähle mindestens eine Karte aus.',
  versusBots: 'GEGEN {n} BOTS',
  // Home: landing (signed out)
  navGame: 'Das Spiel',
  navMaps: 'Karten',
  navModes: 'Modi',
  navAccount: 'Konto erstellen',
  heroText: 'Schießereien in der Nachbarschaft, direkt im Browser. Präzises Zielen, absurde Waffen und ein Siegestänzchen über dem Besiegten.',
  startPlaying: 'JETZT SPIELEN',
  heroNote: 'Ohne Konto: Training und Bots sind frei spielbar. PC, Handy und Controller.',
  aboutTitle: 'So spielt es sich',
  aboutSub: 'Bei der Mechanik todernst. Beim Ton kein bisschen.',
  pillarAimKicker: 'ZIELEN',
  pillarAimTitle: 'Schießen, bei dem Zielen zählt',
  pillarAimDesc: "Streuung, Rückstoß und Schaden je Körperzone. Kopfschüsse tun mehr weh. In die Kronjuwelen tut's anders weh.",
  pillarTauntKicker: 'DEMÜTIGUNG',
  pillarTauntTitle: 'Ein Tänzchen bringt 150',
  pillarTauntDesc: 'Ein Abschuss bringt 100 Punkte. Auf dem Besiegten zu tanzen bringt 150. Provozieren gehört zum Spiel.',
  pillarArsenalKicker: 'ARSENAL',
  pillarArsenalTitle: 'Waffen, die aufleveln',
  pillarArsenalDesc: 'Jeder Abschuss levelt die Waffe, die ihn erzielt hat, und schaltet neue Waffen frei: vom Küchenmesser bis zum Lichtschwert, vom Standardgewehr bis zum Protz-Goldgewehr.',
  mapsTitle: 'Karten',
  mapsSub: 'Drei Nachbarschaften, jede mit eigenen Witzen und Geheimnissen.',
  mapRuaWhen: 'Sonniger Tag',
  mapRuaGag: 'Vorstadt mit leerem Pool, Eiswagen und Flamingos. Vorsicht vor Amora: Ihr Biss ist tödlich.',
  mapJardimWhen: 'Nacht im Laternenschein',
  mapJardimGag: 'Fernöstlicher Garten im Laternenlicht. Kois in den Teichen und eine Kirsche, die 30 s lang extra Leben gibt.',
  mapHalloweenWhen: 'Vollmond',
  mapHalloweenGag: 'Friedhof, Villa, Rummelplatz und Kanalisation. Eine Hexe verteilt Tränke mit zufälliger Wirkung, und unten haust eine Riesenratte.',
  mapCemiterioWhen: 'Nebelnacht',
  mapCemiterioGag: 'Der ummauerte Friedhof des Zombie-Modus: Die Horde steigt draußen aus den Gräbern und kommt nur durch die fünf Lücken in der Mauer rein. Nagle Bretter vor die Lücken und bestimm, wo sie reinkommt.',
  modesTitle: 'Spielmodi',
  tagAccount: 'MIT KONTO',
  tagNoAccount: 'OHNE KONTO',
  landOnlineDesc: 'Jeder gegen jeden (mit deinem Arsenal), Waffenrennen oder Zombies (Wellen im Team), mit Chat und Punktetabelle mit Level und Ping.',
  landOnlineFacts: 'Bis zu 10 Spieler|Sessions pro Karte|Levelt dein Arsenal',
  landBotsDesc: 'Dieselben Regeln, gegen Bots mit Namen wie Capitão Lag und Recruta 404.',
  landBotsFacts: '3, 5, 7 oder 9 Bots|Leicht · Normal · Schwer|2 s Spawnschutz',
  landRangeDesc: 'Zielpuppen auf der gewählten Karte, manche auf Patrouille. Damit du dein Zielen schärfst, ohne dass jemand zuschaut.',
  landRangeFacts: 'Keine Gegner|Jede Karte|Respawn in 3 s',
  accountWhy: 'Um online zu spielen, den Fortschritt deiner Waffen zu speichern und deinen Charakter zu gestalten.',
  startTitle: 'Jetzt spielen',
  startGuest: 'Ohne Registrierung, sofort. Du spielst als {name}.',
  passwordHint: '8 bis 128 Zeichen.',
  nameHint: '3 bis 16 Buchstaben oder Zahlen. Wird als Name#1234 angezeigt.',
  levelShort: 'Lvl {level}',
  accountLevelUp: '🏅 Konto-Level {level}!',
  sessionEnded: 'Deine Session wurde beendet (Abmeldung, Passwortänderung, Löschung oder Sperrung).',
  connectedElsewhere: 'Dein Konto hat sich woanders im Spiel angemeldet.',
  profileTitle: 'Profil',
  statsTitle: 'Statistiken',
  recentTitle: 'Letzte Teilnahmen',
  noParticipations: 'Noch keine Online-Matches.',
  statKills: 'Abschüsse',
  statDeaths: 'Tode',
  statHead: 'Kopfschüsse',
  statGroin: 'In die Kronjuwelen',
  statKnife: 'Messerstiche',
  statBackstab: 'Hinterrücks',
  statGrenade: 'Per Granate',
  statHumiliations: 'Demütigungen',
  statTime: 'Spielzeit',
  statMatches: 'Teilnahmen',
  zstatsTitle: 'Zombie-Modus',
  zstatMatches: 'Matches',
  zstatWins: 'Siege',
  zstatBestWave: 'Beste Welle',
  zstatWaves: 'Überlebte Wellen',
  zstatKills: 'Zombie-Abschüsse',
  zstatDowns: 'Mal am Boden',
  zstatRevives: 'Wiederbelebungen',
  zstatCoffin: 'Sarg-Drehs',
  albumTitle: 'Stickeralbum',
  albumHint: 'Jedes Ziel bringt eine Veredelung mehr, bis hin zu Gold. Nur was du online machst, zählt.',
  albumCount: '{stuck} von {total} Stickern · {finishes} von {finishesTotal} Veredelungen',
  albumDone: 'Komplett!',
  albumRepeats: 'Doppelte: ×{n}',
  finishNone: 'Noch nicht eingeklebt',
  finishComum: 'Normal',
  finishBrilhante: 'Glänzend',
  finishHolografica: 'Holografisch',
  finishDourada: 'Gold',
  stickerUp: '{icon} Sticker ({finish}): {name}!',
  stickerSecret: '🔓 Geheimer Sticker entdeckt: {icon} {name}!',
  albumHidden: 'Geheimer Sticker',
  albumShowcase: 'Im Schaukasten',
  albumNoShowcase: 'Leer: Wähle einen eingeklebten Sticker',
  albumTitleLabel: 'Titel',
  albumNoTitle: 'Kein Titel',
  albumFeature: 'In den Schaukasten',
  albumUnfeature: 'Aus dem Schaukasten',
  albumTitlesSummary: 'Titel: {got} von {total}',
  albumTitlesHint: 'Jede Seite bringt dir einen Titel, sobald alle ihre Sticker Holografisch oder Gold sind. Dein Titel und dein Sticker im Schaukasten erscheinen für die anderen in der Punktetabelle und wenn du sie erledigst.',
  errStickerLocked: 'Diesen Sticker oder Titel hast du noch nicht.',
  customize: 'CHARAKTER ANPASSEN',
  changeName: 'Namen ändern',
  nameFreeAt: 'Nächste Änderung möglich am {date}.',
  nameRule: 'Die erste Änderung ist frei, danach eine alle 7 Tage.',
  linkDiscord: 'Discord verknüpfen',
  unlinkDiscord: 'Discord trennen',
  discordLinked: 'Discord verknüpft.',
  deleteAccount: 'Konto löschen',
  deleteConfirm: 'Konto löschen? Du hast 30 Tage Zeit, es dir anders zu überlegen, indem du dich wieder anmeldest. Danach werden Name und E-Mail gelöscht.',
  cancelDeletion: 'Löschung abbrechen',
  deletionPending: 'Konto zur Löschung am {date} vorgemerkt. Online spielen ist gesperrt, bis du die Löschung abbrichst.',
  saved: 'Gespeichert.',
  errCredentials: 'E-Mail oder Passwort falsch.',
  errTooMany: 'Zu viele Versuche. Warte eine Minute und versuch es noch mal.',
  errSuspended: 'Dieses Konto ist gesperrt.',
  errPendingDeletion: 'Dieses Konto ist zur Löschung vorgemerkt. Brich sie im Profil ab, um online zu spielen.',
  errEmailUsed: 'Für diese E-Mail gibt es schon ein Konto. Melde dich an oder nutze "Passwort vergessen".',
  errEmailInvalid: 'Ungültige E-Mail.',
  errPasswordInvalid: 'Das Passwort muss 8 bis 128 Zeichen haben.',
  errNameInvalid: 'Ungültiger Name: 3 bis 16 Buchstaben oder Zahlen.',
  errNameTaken: 'Für diesen Namen sind keine Nummern mehr frei. Versuch einen anderen.',
  errNameCooldown: 'Du kannst deinen Namen erst am {date} wieder ändern.',
  errTokenInvalid: 'Ungültiger oder abgelaufener Link. Fordere unter "Passwort vergessen" einen neuen an.',
  errOnlyLogin: 'Discord ist der einzige Weg in dieses Konto.',
  errDiscordUnavailable: 'Anmelden mit Discord ist unter dieser Adresse nicht verfügbar.',
  errDiscordLinked: 'Dieser Discord-Account ist schon mit einem Konto verknüpft.',
  errUnauthorized: 'Bitte melde dich neu an.',
  errOffline: 'Server nicht erreichbar. Starte "bun run dev:online" (oder spiel das Offline-Training).',
  errGeneric: 'Da ist was schiefgelaufen. Versuch es noch mal.',
  onlineSubtitle: 'Session: {name} · {mode}',
  // Mapas and Gerenciamento tabs (PF-6: client/ui/maps.ts, client/ui/management.ts).
  tabMaps: 'KARTEN',
  tabManagement: 'VERWALTUNG',
  mapsOfficial: 'Offiziell',
  mapsCommunity: 'Community',
  mapsNew: '+ Neue Karte',
  mapsSearch: 'Suchen…',
  mapsSearchBy: 'Suchen nach',
  mapsByName: 'Name',
  mapsByAuthor: 'Autor',
  mapsOrder: 'Sortierung',
  mapsOrderPlayed: 'Meistgespielt',
  mapsOrderRecent: 'Neueste',
  mapsShowHidden: 'Ausgeblendete zeigen',
  mapsEmpty: 'Keine Karten gefunden.',
  mapsMore: 'Mehr anzeigen',
  mapsPlays: '{n}× gespielt',
  mapsPlaysOne: '1× gespielt',
  mapsVersion: 'Version {v}',
  mapsBy: 'von {autor}',
  mapsOfficialBy: 'Offizielle Karte',
  mapsCommunitySub: 'Community-Karte',
  mapsZombieOnly: 'Nur Zombies',
  mapsHiddenTag: 'Ausgeblendet',
  mapsHiddenWhy: 'Ausgeblendet: {motivo}',
  mapsPlay: 'Spielen',
  mapsBots: 'Gegen Bots',
  mapsRange: 'Schießstand',
  mapsEdit: 'Bearbeiten',
  mapsDuplicate: 'Duplizieren',
  mapsDelete: 'Löschen',
  mapsHide: 'Ausblenden',
  mapsUnhide: 'Einblenden',
  mapsVersions: 'Versionen',
  mapsCancel: 'Abbrechen',
  mapsClose: 'Schließen',
  mapsDeleteConfirm: '"{nome}" löschen? Die Karte verschwindet aus den Listen und startet keine neuen Matches mehr (laufende Matches werden darauf zu Ende gespielt).',
  mapsHideReason: 'Grund (optional)',
  mapsHideConfirm: '"{nome}" aus den Listen ausblenden? Nur der Autor und das Team sehen die Karte dann noch.',
  mapsVersionsTitle: 'Gespeicherte Versionen',
  mapsRestore: 'Wiederherstellen',
  mapsCurrent: 'aktuell',
  mapsRestored: 'Version {v} wiederhergestellt: Neue Matches nutzen sie.',
  mapsDuplicated: 'Kopie von "{nome}" unter Community erstellt.',
  mapsDeleted: 'Karte gelöscht.',
  mapsHidden: 'Karte ausgeblendet.',
  mapsUnhidden: 'Die Karte ist wieder in den Listen.',
  mapsLoading: 'Lädt…',
  mgTitle: 'Verwaltung',
  mgHint: 'Such ein Konto über den Namen oder den Tag (Name#1234).',
  mgSearch: 'Name oder Name#1234',
  mgFind: 'Suchen',
  mgOpen: 'Öffnen',
  mgEmpty: 'Keine Konten gefunden.',
  mgBanned: 'Gebannt',
  mgMuted: 'Stummgeschaltet',
  mgSuspended: 'Gesperrt',
  mgPendingDeletion: 'Wird gelöscht',
  mgRole_admin: 'Admin',
  mgRole_moderador: 'Moderator',
  mgPlayer: 'Spieler',
  mgReadOnly: 'Du kannst dieses Konto nicht bearbeiten: Ein Moderator kann nichts gegen einen Admin unternehmen.',
  mgSanctions: 'Sanktionen',
  mgNoPunish: 'Du kannst dieses Konto nicht bestrafen.',
  mgBan: 'Bannen',
  mgMute: 'Stummschalten',
  mgReason: 'Grund',
  mgDuration: 'Dauer',
  mgDur_1h: '1 Stunde',
  mgDur_12h: '12 Stunden',
  mgDur_1d: '1 Tag',
  mgDur_7d: '7 Tage',
  mgDur_30d: '30 Tage',
  mgDur_permanente: 'Dauerhaft',
  mgApply: 'Anwenden',
  mgUnban: 'Bann aufheben',
  mgUnmute: 'Stummschaltung aufheben',
  mgHistory: 'Verlauf',
  mgNoSanctions: 'Keine Sanktionen.',
  mgSanction_banimento: 'Bann',
  mgSanction_silencio: 'Stummschaltung',
  mgUntil: 'bis {data}',
  mgForever: 'unbefristet',
  mgRevoked: 'aufgehoben am {data}',
  mgBy: 'von {tag}',
  mgNeedReason: 'Gib einen Grund an.',
  mgName: 'Name',
  mgNameHint: 'Sofort geändert, ohne die 7 Tage Wartezeit; die Wartezeit des Spielers beginnt neu.',
  mgLook: 'Aussehen',
  mgEditLook: 'Aussehen bearbeiten',
  mgProgress: 'Fortschritt',
  mgAccountXp: 'Konto-XP (Level {n})',
  mgWeaponXp: 'Waffen-XP',
  mgSaveProgress: 'Fortschritt speichern',
  mgBadNumber: 'Nutze ganze Zahlen von 0 bis 1.000.000.000.',
  mgRoles: 'Rollen',
  mgPromote: 'Zum {papel} befördern',
  mgDemote: 'Rolle {papel} entziehen',
  mgRolesNone: 'Du kannst die Rollen dieses Kontos nicht ändern.',
  mgDone: 'Erledigt.',
  errNoPermission: 'Dazu hast du keine Berechtigung.',
  errNotFound: 'Nicht gefunden.',
  errBadInput: 'Ungültige Daten.',
  errLastAdmin: 'Der letzte Admin kann nicht entfernt werden.',
  errProtectedMap: 'Die vier ursprünglichen offiziellen Karten können weder gelöscht noch ausgeblendet werden.',
  // Pause menu (client/ui/menu.ts, client/ui/pauseMenu.ts): the rail (where we are, the banner, the exit), the
  // mode's tab and the settings' tab in the panel, and the exit's confirmation. Same texts on the start card.
  pmLineSession: 'Session: {name} · {n}/{max} Spieler',
  pmLineBots: 'Gegen {n} Bots · {skill}',
  // {wave}: pmLineWave, or before the first wave the HUD's countdown title (zCountdown).
  pmLineWave: 'Welle {n}/{total}',
  pmLineWaveTeam: '{wave} · {players} Spieler',
  pmLineWaveAlone: '{wave} · 1 Spieler',
  pmLineWaveSolo: '{wave} · allein',
  pmLineRange: 'Offline-Training mit den Zielpuppen',
  pmPreview: 'Vorschau: {file}',
  pmLiveOnline: 'Online: Das Spiel läuft weiter, und du kannst dir eine Kugel fangen.',
  pmLiveHorde: 'Online: Die Horde wartet nicht. Dein Team kämpft weiter.',
  pmPausedBots: 'Spiel pausiert: Die Bots warten auf dich.',
  pmPaused: 'Spiel pausiert.',
  pmExitSession: 'Session verlassen',
  pmExitMatch: 'Match verlassen',
  pmExitRace: 'Rennen verlassen',
  pmExitRange: 'Training verlassen',
  pmConfirmSession: 'Du verlässt die Session {name} und kehrst zum Startbildschirm zurück. Die Punkte, die deine Waffen schon verdient haben, bleiben auf deinem Konto.',
  pmConfirmBots: 'Das Match gegen die Bots endet und du kehrst zum Startbildschirm zurück.',
  pmConfirmRace: 'Du verlässt das Rennen und verlierst deine aktuelle Stufe. Ab zum Startbildschirm.',
  pmConfirmRaceBots: 'Das Rennen gegen die Bots endet und du kehrst zum Startbildschirm zurück.',
  pmConfirmZombieTeam: 'Dein Team macht ohne dich weiter. Das Geld aus diesem Match verfällt.',
  pmConfirmZombieAlone: 'Das Match startet neu für den Nächsten, der beitritt. Das Geld aus diesem Match verfällt.',
  pmConfirmZombieSolo: 'Das Match endet und das Geld verfällt.',
  pmConfirmRange: 'Du verlässt den Schießstand und kehrst zum Startbildschirm zurück.',
  pmConfirmEditor: 'Das Spiel stoppt und du kehrst in den Editor zurück, genau dorthin, wo du warst.',
  pmStay: 'BLEIBEN',
  pmLeave: 'VERLASSEN',
  pmStayHint: 'im Match bleiben',
  pmClose: 'Schließen',
  pmBack: 'Zurück',
  pmHintResume: 'Zurück zum Spiel',
  pmHintBack: 'Zurück',
  pmHintPick: 'Auswählen',
  pmBadgeReadOnly: '🔒 Nur ansehen',
  pmBadgeEditable: 'Im Training änderbar',
  pmArsenalSubReadOnly: 'Deine Ausrüstung · nur ansehen',
  pmArsenalSubEditable: 'Tausch Waffen und Upgrades',
  pmArsenalHintReadOnly: 'Das hast du in dieses Match mitgebracht.',
  pmArsenalHintEditable: 'Auf dem Schießstand kannst du alles tauschen, und es gilt sofort.',
  pmArsenalFootReadOnly: 'Während des Matches gesperrt. Tausch Waffen und Upgrades im Arsenal auf dem Startbildschirm: Änderungen gelten ab dem nächsten Match.',
  pmArsenalFootEditable: 'Auf dem Schießstand ist das Arsenal bearbeitbar und Änderungen gelten sofort.',
  pmArsenalFootGuest: 'Erstell ein Konto, damit deine Waffen aufleveln',
  pmUpgradesUnlocked: 'Freigeschaltete Upgrades',
  pmNoUpgrades: 'Noch keine Upgrades freigeschaltet',
  pmMoreUpgrades: '🔒 Noch {n} Upgrades freizuschalten. Nächstes: {upgrade}, noch {xp} {prog}-Punkte.',
  pmMoreUpgrade: '🔒 Noch 1 Upgrade freizuschalten: {upgrade}, noch {xp} {prog}-Punkte.',
  pmNextMatch: 'Gilt im nächsten Match',
  pmWeaponsUnlocked: 'Freigeschaltete Waffen',
  pmTabLadder: 'Leiter',
  pmTabLadderSub: 'Stufe {n} von {total} · {k}/{need} Abschüsse',
  pmLadderHint: 'Alle nutzen dieselben Waffen mit denselben Werten.',
  pmLadderYou: 'Du · {k}/{need}',
  pmLadderNow: 'Jetzt · Stufe {n}',
  pmLadderNext: 'Nächste · Stufe {n}',
  pmLadderToGo: 'noch {n} Abschüsse bis zum Aufstieg',
  pmLadderToGoOne: 'noch 1 Abschuss bis zum Aufstieg',
  pmLadderToWin: 'noch {n} Abschüsse bis zum Sieg',
  pmLadderToWinOne: 'noch 1 Abschuss bis zum Sieg',
  pmLadderGun: '{mag} Schuss · {rpm} rpm',
  pmLadderSilenced: 'gedämpfte Schüsse',
  pmLadderFinal: 'Letzter Abschuss',
  pmLadderFinalOne: 'Ein Abschuss mit dem {weapon} gewinnt die Runde',
  pmLadderFinalMany: '{n} Abschüsse mit dem {weapon} gewinnen die Runde',
  pmRuleClimb: '{n} Abschüsse mit der aktuellen Waffe oder dem Messer bringen dich eine Stufe höher.',
  pmRuleStab: "Tod durch Messerstich kostet einen Abschuss. Ohne Abschüsse auf der Stufe geht's eine Waffe zurück.",
  pmRuleFinalOne: 'Auf der letzten Stufe gewinnt ein Abschuss mit dem {weapon} die Runde.',
  pmRuleFinalMany: 'Auf der letzten Stufe gewinnen {n} Abschüsse mit dem {weapon} die Runde.',
  pmLeader: 'In Führung',
  pmLeaderOther: '{name} · Stufe {n} ({weapon})',
  pmLeaderYou: 'Du liegst vorne',
  pmTabCoffin: 'Sarg',
  pmTabCoffinSub: 'Was du trägst und die Chancen',
  pmCoffinHintOnline: '${cost} pro Waffe, ausgelost auf dem Server. Die Seltenheit multipliziert den Schaden gegen Zombies.',
  pmCoffinHintSolo: '${cost} pro Waffe. Die Seltenheit multipliziert den Schaden gegen Zombies.',
  pmCoffinFoot: 'Die neue Waffe ersetzt die der gleichen Art (Gewehr, Sekundärwaffe oder Messer). Beschädigt lässt sich nicht reparieren: Da hilft nur ein neuer Dreh.',
  pmCoffinOdds: 'Chancen · ${cost}',
  pmCoffinMul: '×{m} Schaden',
  pmCoffinBroken: '{n}% kommen beschädigt',
  pmConfigSub: 'Zielen, Grafik, Ton und Tasten',
  pmConfigHint: 'Alles gilt sofort.',
  pmSubAim: 'Zielen',
  pmSubVideo: 'Grafik',
  pmSubAudio: 'Ton',
  pmSubKeys: 'Tasten',
  pmSubPad: 'Controller',
  pmSubTouch: 'Touchscreen',
  pmDescSens: 'Maus, ohne Zielen',
  pmDescAds: 'Multipliziert die Empfindlichkeit beim Zielen',
  pmDescPadSens: 'Rechter Stick',
  pmDescAssist: 'Das Fadenkreuz wird über einem Gegner langsamer, zieht aber nicht aus der Ferne',
  pmDescInvert: 'Nach oben bewegen schaut nach unten',
  pmDescFov: 'Höher zeigt mehr an den Seiten',
  pmDescQuality: 'Automatisch regelt selbst nach, um die FPS zu halten',
  pmDescFullscreen: 'Im Vollbild öffnet und schließt Esc das Menü sofort',
  // The language (PF-30): the row in the settings' Video tab, the landing's button, the page title and the
  // game server's refusals by code (shared/protocol.ts WsErrorCode).
  language: 'Sprache',
  pmDescLanguage: 'Texte, Menüs und die Passwort-E-Mail. Außerhalb eines Matches lädt die Seite sofort neu',
  langLater: 'Sprache gespeichert: gilt, sobald du zum Start zurückkehrst',
  docTitle: 'Offensive Combat — Prototyp',
  wsErr_sem_ola: 'Die Verbindung hat sich nicht angemeldet. Versuch es noch mal.',
  wsErr_sessao_lotada: 'Session voll.',
  wsErr_sessao_inexistente: 'Diese Session gibt es nicht mehr.',
  wsErr_mapa_indisponivel: 'Diese Karte ist nicht verfügbar.',
  wsErr_modo_fora_do_mapa: 'Dieser Modus wird auf dieser Karte nicht gespielt.',
  wsErr_sem_mapa: 'Für diesen Modus gibt es keine Karte.',
  wsErr_entrada_falhou: 'Beitreten gerade nicht möglich.',
  pmDescVolume: 'Gesamtlautstärke des Spiels',
  pmDescSpatial: 'Automatisch: 3D am PC, Stereo am Handy',
  pmOn: 'An',
  pmOff: 'Aus',
  keyGroupMove: 'Bewegung',
  keyGroupCombat: 'Kampf',
  keyGroupOther: 'Sonstiges',
  pmKeyPress: 'Taste drücken…',
  pmEscFixed: 'öffnet das Menü (fest)',
  pmPadNote: 'Feste Controller-Belegung (CoD-Stil). Die Tastatur lässt sich frei belegen.',
  gpuWarning: 'Dein Browser zeichnet das Spiel ohne Grafikkarte (Renderer: {gpu}), deshalb läuft es nur mit ~10 FPS. Aktiviere “Grafikbeschleunigung verwenden, wenn verfügbar” unter chrome://settings/system (in Edge: edge://settings/system) und starte den Browser neu.',
  // Galpão (client/ui/galpao): the 3D home's menu, stations, signs, Arsenal board and launch.
  gpQuick: 'SCHNELLSTART',
  gpQuickLine: '{mode} · Online · {maps}',
  gpNoMapMarked: 'keine Karte ausgewählt',
  gpBack: '‹ LAGERHALLE',
  gpLaunching: 'AB INS MATCH',
  gpLaunchOnline: '{map} · {mode} · {n}/{max} Spieler',
  gpLaunchBots: 'Gegen {n} Bots · {map}',
  gpLaunchHorde: 'Allein gegen die Horde · {map}',
  gpLaunchRange: 'Offline-Training · {map}',
  gpSt_play: 'Spielen',
  gpSt_maps: 'Karten',
  gpSt_arsenal: 'Arsenal',
  gpSt_album: 'Album',
  gpSt_profile: 'Profil',
  gpSt_settings: 'Einstellungen',
  gpSt_admin: 'Verwaltung',
  gpStSub_play: 'Online, gegen Bots oder auf dem Schießstand',
  gpStSub_maps: 'Offiziell und aus der Community: spielen, duplizieren oder erstellen',
  gpStSub_arsenal: 'Waffen, Upgrades und Ausrüstung',
  gpStSub_album: 'Sticker, Titel und Schaukasten',
  gpStSub_profile: 'Konto, Statistiken und Charakter',
  gpStSub_settings: 'Zielen, Grafik, Ton und Tasten',
  gpStSub_admin: 'Moderation · nur fürs Team',
  gpHint_play: 'Wähle den Modus, die Match-Art und die Karte. Der orange Knopf startet.',
  gpHint_maps: 'Spiel eine Karte, dupliziere eine zum Bearbeiten oder bau eine von Grund auf neu.',
  gpHint_arsenal: 'Ziehen zum Bewegen, Mausrad zum Zoomen. Klick auf eine Waffe für Details. Grün: ausgerüstet · rot: gesperrt.',
  gpHint_arsenalTouch: 'Ziehen zum Bewegen, mit zwei Fingern zoomen. Tipp auf eine Waffe für Details. Grün: ausgerüstet · rot: gesperrt.',
  gpHint_album: 'Klick auf einen Sticker, um zu sehen, wie du ihn einklebst. Mit den Reitern blätterst du um.',
  gpHint_profile: 'Deine Akte: Statistiken, letzte Matches und die Kontooptionen.',
  gpHint_settings: 'Wähle oben auf der Tafel einen Bereich. Änderungen gelten sofort.',
  gpHint_admin: 'Such das Konto, prüf den Status und wähle eine Aktion. Nichts ändert sich, bevor du bestätigst.',
  gpSign_play: '01 · EINSÄTZE',
  gpSign_maps: '02 · KARTEN',
  gpSign_arsenal: '03 · ARSENAL',
  gpSign_profile: '05 · UMKLEIDE',
  gpSign_settings: '06 · WERKSTATT',
  gpSign_admin: '07 · SICHERHEIT',
  gpBoard_primaria: 'PRIMÄR',
  gpBoard_secundaria: 'SEKUNDÄR',
  gpBoard_faca: 'MESSER',
  gpBoard_granada: 'GRANATE',
  gpAdminScreen: 'VERWALTUNG',
  gpAdminScreenSub: 'ZUGANG BESCHRÄNKT · TEAM',
  gpDanger: 'GEFAHR',
  gpHighVoltage: 'HOCHSPANNUNG',
  gpExit: 'AUSGANG',
  gpAlbumCover1: 'OFFENSIVE COMBAT · OFFIZIELLES ALBUM',
  gpAlbumCover2: 'STICK',
  gpAlbumCover3: 'ER',
  gpAlbumCover4: '{n} STICKER',
  gpTagLevel: 'LVL{level}',
  gpTagLocked: 'GESPERRT',
  gpTagOn: 'AN',
  gpTagOff: 'AUS',
  gpLockedChip: 'GESPERRT',
  gpSharesProg: 'Nutzt die {prog}-Punkte und -Upgrades',
  gpAutoOn: 'Schaltet sich beim Freischalten selbst ein',
  gpUpgradesOf: '{prog}-UPGRADES',
  gpPlayHintOnline: 'Wähle die Match-Art und die Karten. Die Liste zeigt die gerade offenen Sessions.',
  gpPlayHintBots: 'Offline-Match gegen Bots, mit deinem Arsenal und den Upgrades deines Kontos.',
  gpPlayHintRange: 'Klick auf eine Karte (oder den orangen Knopf), um den Schießstand mit den Zielpuppen zu öffnen.',
  gpCtaLine: '{mode} · {map}',
  gpRangeTargets: 'Statische Zielpuppen',
};

export const tips: string[] = [
  'Tipp: Auf den Gegner schießen klappt meistens besser als auf die Wand.',
  'Tipp: Die Zielpuppe schießt nicht zurück. Noch nicht.',
  'Tipp: Ein Sturz aus 7 Metern tut weh. Frag mal deine Knie.',
  'Tipp: Kopfschüsse machen doppelten Schaden und dich dreimal so eingebildet.',
  'Tipp: Sprinten und gleichzeitig schießen ist verboten. Hat die Armgewerkschaft so beschlossen.',
  'Tipp: Der Eiswagen verkauft kein Eis. Aber Musik spielt er.',
  'Tipp: Die Flamingos können nichts dafür.',
];

export const quickChat: string[] = ['GG', 'Stark!', 'xD', 'Vorsicht!', '1v1?', 'Danke!'];

export const deathMessages: DeathLines = {
  fall: ['Du hast die Schwerkraft besiegt. Kleiner Scherz: Sie hat gewonnen.', 'Versuch nächstes Mal, auf den Füßen zu landen.', 'Der Bürgersteig lässt grüßen.'],
  void: ['Du hast die Karte verlassen. Die Karte hat dich nicht vermisst.', 'Mutiger Entdecker. Toter Entdecker.'],
  explosion: ['Zu lange gekocht. Die Granate – und dich gleich mit.', 'Tipp: Die Granate fliegt Richtung Gegner.'],
  dog: ['Amora fand deinen Besuch nicht so toll.', 'Von Amora gebissen. Flauschig, aber bissig.', 'Falscher Garten. Wuff.'],
  zombie: ['Mahlzeit! Du warst das Zombie-Mittagessen.', 'Der Nachbar hat zugebissen. Und das war kein Knutschfleck.', 'Keiner kam, um dich wiederzubeleben. Was für eine Nachbarschaft.'],
  thorns: ['Das Gitter hatte Dornen. Stand nirgendwo dran.', 'Über die Mauer klettern: 0. Dornen: 1.', 'Verblutet. Die Hecke sagt danke.'],
  sacrilege: ['Auf den Altar geklettert. Der Altar fand das gar nicht lustig.', 'Sakrileg: Die Kapelle kassiert saftig.', 'Das Totem ist zum Anzünden da, nicht zum Draufstellen.'],
  crows: ['Die Krähen haben dich zuerst gefunden.', "Ein Baum ist kein Versteck. Die Krähen haben's dir gesagt.", 'Zu Tode gepickt.'],
};
