// The map editor's texts (pt-BR and en), apart from the game's (client/ui/strings.ts): the same language the
// game picked (getLang).
import { getLang } from '../ui/strings';

const pt = {
  title: 'Editor de mapas',
  newMap: 'Mapa novo',
  loading: 'Carregando o mapa…',
  loadFailed: 'Não deu para abrir o mapa: {erro}',
  undo: 'Desfazer (Ctrl+Z)',
  redo: 'Refazer (Ctrl+Y)',
  hand: 'Mão (Q)',
  move: 'Mover (W)',
  rotate: 'Girar (E)',
  scale: 'Escalar (R)',
  rect: 'Retângulo (T)',
  pivot: 'Pivô',
  center: 'Centro',
  pivotTip: 'Pivô: o gizmo na peça ativa · Centro: no meio da seleção (gira e escala em volta dele)',
  local: 'Local',
  global: 'Global',
  spaceTip: 'Local: os eixos do gizmo giram com a peça ativa · Global: os eixos do mundo',
  grid: 'Grade',
  gridTip: 'Encaixe sempre ligado (desligado, segure Ctrl para encaixar)',
  gridMenu: 'Passos do encaixe',
  gridMove: 'Mover (m)',
  gridTurn: 'Girar (graus)',
  viewPersp: 'Persp',
  viewOrtho: 'Orto',
  viewTip: 'Clique num eixo para ver daquele lado (Y: de cima); no meio, perspectiva ou ortográfica',
  copied: 'Copiado: {n} peça(s).',
  pasteEmpty: 'Nada copiado ainda (Ctrl+C).',
  focus: 'Centralizar (F)',
  duplicate: 'Duplicar (Ctrl+D)',
  remove: 'Apagar (Delete)',
  save: 'Salvar',
  exit: 'Sair',
  exitConfirm: 'Sair do editor? O que não foi salvo se perde.',
  hint: 'Botão direito + WASD/QE voa · Alt + arrastar orbita · botão do meio arrasta · roda aproxima · Q W E R T ferramentas · Ctrl encaixa · arrastar seleciona por caixa · F centraliza',
  search: 'Buscar peça…',
  markers: 'Marcadores',
  imported: 'Modelos GLB',
  importGlb: 'Importar .glb do computador…',
  catPrimitivas: 'Primitivas',
  catEstrutura: 'Estrutura',
  catConstrucoes: 'Construções',
  catNatureza: 'Natureza',
  catMoveis: 'Móveis',
  catVeiculos: 'Veículos',
  catObjetos: 'Objetos',
  catLuzes: 'Luzes',
  catAmbiente: 'Ambiente',
  catImportado: 'Importado',
  mkSpawnA: 'Spawn time A',
  mkSpawnB: 'Spawn time B',
  mkSpawnFfa: 'Spawn livre (FFA)',
  mkBoneco: 'Boneco de treino',
  mkCereja: 'Cereja (coletável)',
  mkBiscoito: 'Biscoito (coletável)',
  mkBruxa: 'Lugar da bruxa',
  mkRato: 'Rato (objeto)',
  mkPeixe: 'Peixe',
  mkSurgir: 'Zumbi: surgimento',
  mkCaixa: 'Zumbi: caixão',
  mkChefe: 'Zumbi: chefe {id}',
  mkBarricada: 'Zumbi: brecha {id}',
  mkDentro: 'Zumbi: canto do muro',
  mkZumbiOn: 'Criar os dados do modo zumbi',
  inspector: 'Propriedades',
  mapSettings: 'Mapa',
  nothingSelected: 'Nada selecionado: estas são as configurações do mapa.',
  piece: 'Peça',
  kind: 'Tipo',
  position: 'Posição',
  yaw: 'Giro (graus)',
  scaleField: 'Escala',
  pose: 'Pose (gizmo)',
  posePos: 'Deslocamento',
  poseRot: 'Giro X, Y, Z (graus)',
  poseClear: 'Tirar a pose',
  seed: 'Semente',
  propId: 'Id da piada',
  collectible: 'Coletável',
  none: 'nenhum',
  params: 'Parâmetros',
  optional: 'usar',
  addItem: '+ item',
  removeItem: 'tirar',
  addOpening: '+ vão',
  jsonInvalid: 'JSON inválido',
  killY: 'Morte abaixo de (killY)',
  cell: 'Célula dos lotes (m)',
  shadow: 'Sombra do sol (meia largura, m)',
  dome: 'Céu',
  domeNone: 'dia (padrão)',
  domeClouds: 'nuvens',
  domeMoon: 'lua',
  domeOriental: 'noite oriental',
  atmosphere: 'Luz e neblina (JSON)',
  sounds: 'Sons ambientes (JSON)',
  lights: 'Luzes reais',
  patrol: 'Patrulha',
  lake: 'Lago',
  loop: 'Volta (x, z, raio)',
  depth: 'Profundidade (y)',
  width: 'Largura',
  axis: 'Eixo',
  budget: 'Orçamento',
  budgetMeasuring: 'medindo…',
  budgetText: '{dc} / {dcMax} chamadas · {tri} / {triMax} triângulos',
  budgetOver: 'Passou do limite: {o}',
  budgetDrawCalls: 'chamadas de desenho',
  budgetTriangles: 'triângulos',
  invalid: 'O mapa tem problemas ({n}):',
  saveTitle: 'Salvar o mapa',
  name: 'Nome',
  emoji: 'Emoji',
  color: 'Cor do cartão',
  modes: 'Modos',
  modesOpen: 'aberto (mata-mata, corrida armada, bots e treino)',
  modesZombie: 'exclusivo do modo zumbi',
  kindLabel: 'Tipo',
  official: 'oficial',
  community: 'comunidade',
  officialOnlyStaff: 'Só admin e moderador salvam mapas oficiais.',
  baseVersion: 'Editando a versão {v}',
  saveConfirm: 'Salvar',
  cancel: 'Cancelar',
  saving: 'Salvando…',
  saved: 'Salvo: versão {v}.',
  errStale: 'Alguém salvou a versão {v} deste mapa enquanto você editava. Nada foi salvo: escolha o que fazer.',
  staleForce: 'Salvar como nova versão mesmo assim',
  staleForceHint: 'A versão {v} continua no histórico.',
  staleOpen: 'Abrir a versão atual',
  staleOpenHint: 'Descarta as suas edições.',
  errBudget: 'O servidor recusou: {o} ({dc} chamadas, {tri} triângulos; limite {dcMax} e {triMax}).',
  errInvalid: 'O servidor recusou o mapa:',
  errPermission: 'Você não pode salvar este mapa.',
  errSignedOut: 'Entre na sua conta para salvar.',
  errOffline: 'Sem conexão com o servidor.',
  errOther: 'Não deu para salvar ({e}).',
  testInvalid: 'Corrija o mapa antes de jogar (Play).',
  glbTooBig: 'O arquivo passa de 10 MB.',
  glbUploading: 'Enviando {nome}…',
  glbDone: '{nome} enviado.',
  glbInvalid: 'Modelo recusado: {m}',
  glbQuota: 'Sua cota de modelos acabou.',
  glbRate: 'Muitos envios nesta hora: tente mais tarde.',
  glbFailed: 'Não deu para enviar o modelo ({e}).',
  buildFailed: 'A peça {id} não montou: {e}',
  limitReached: 'O mapa já tem o máximo de "{nome}".',
  draftTitle: 'Rascunho guardado',
  draftText: 'Este mapa tem um rascunho de {quando}, mais novo que a versão salva. Recuperar as edições?',
  draftTextNew: 'Há um rascunho de mapa novo de {quando}. Recuperar?',
  draftRecover: 'Recuperar o rascunho',
  draftDiscard: 'Descartar',
  draftRecovered: 'Rascunho recuperado (ainda não salvo).',
  play: 'Play: jogar o mapa aqui, na aba Jogo (o treino; num mapa só de zumbi, a partida de zumbi sozinho)',
  pause: 'Pause: congela o jogo e solta o mouse (▶ continua)',
  stop: 'Stop: termina o jogo e volta a editar onde estava',
  panelGame: 'Jogo',
  gameIdle: 'Aperte ▶ (Play) para jogar aqui o mapa do editor, mesmo sem salvar.',
  gameLoading: 'Abrindo o jogo…',
  playFailed: 'O jogo não abriu: {e}',
  playTimeout: 'o jogo demorou demais para abrir',
  playPausedVeil: '❚❚ Pausado · ▶ continua · ■ volta a editar',
  playing: 'Jogando: o editor só olha (■ para editar).',
  paused: 'Pausado: a câmera da Cena e a seleção funcionam; nada muda o mapa.',
  thumbSize: 'Tamanho das miniaturas',
  thumbsDrawing: 'Desenhando {n} miniatura(s)…',
  projectEmpty: 'Nada aqui.',
  markerNeedsZombie: 'Precisa dos dados do modo zumbi (no Inspetor do mapa).',
  layout: 'Layout',
  layoutReset: 'Restaurar layout padrão',
  panelHierarchy: 'Hierarquia',
  panelScene: 'Cena',
  panelInspector: 'Inspetor',
  panelProject: 'Projeto',
  hierCreate: 'Criar',
  hierNewGroup: 'Grupo vazio',
  hierGroupSel: 'Agrupar a seleção (Ctrl+G)',
  hierSearch: 'Buscar na cena…',
  cantMove: 'Um grupo não entra nele mesmo nem num grupo de dentro dele.',
  manySelected: '{n} peças selecionadas',
  mixedKinds: 'Tipos diferentes: só o Transform é editado junto.',
  mixedValues: 'Os valores são diferentes entre as peças selecionadas.',
  nameField: 'Nome (vazio: o id)',
  group: 'Grupo',
  transform: 'Transform',
  rotation: 'Rotação (graus)',
  dragHint: 'Arraste para mudar (Shift: mais rápido)',
};

const en: Record<keyof typeof pt, string> = {
  title: 'Map editor',
  newMap: 'New map',
  loading: 'Loading the map…',
  loadFailed: "Couldn't open the map: {erro}",
  undo: 'Undo (Ctrl+Z)',
  redo: 'Redo (Ctrl+Y)',
  hand: 'Hand (Q)',
  move: 'Move (W)',
  rotate: 'Rotate (E)',
  scale: 'Scale (R)',
  rect: 'Rect (T)',
  pivot: 'Pivot',
  center: 'Center',
  pivotTip: 'Pivot: the gizmo on the active piece · Center: in the middle of the selection (turns and scales about it)',
  local: 'Local',
  global: 'Global',
  spaceTip: "Local: the gizmo's axes turn with the active piece · Global: the world's axes",
  grid: 'Grid',
  gridTip: 'Snapping always on (off: hold Ctrl to snap)',
  gridMenu: 'Snap steps',
  gridMove: 'Move (m)',
  gridTurn: 'Rotate (degrees)',
  viewPersp: 'Persp',
  viewOrtho: 'Ortho',
  viewTip: 'Click an axis to look from that side (Y: from above); the middle switches perspective and orthographic',
  copied: 'Copied: {n} piece(s).',
  pasteEmpty: 'Nothing copied yet (Ctrl+C).',
  focus: 'Focus (F)',
  duplicate: 'Duplicate (Ctrl+D)',
  remove: 'Delete (Delete)',
  save: 'Save',
  exit: 'Exit',
  exitConfirm: 'Leave the editor? Anything not saved is lost.',
  hint: 'Right button + WASD/QE flies · Alt + drag orbits · middle button pans · wheel zooms · Q W E R T tools · Ctrl snaps · drag to box-select · F frames',
  search: 'Search pieces…',
  markers: 'Markers',
  imported: 'GLB models',
  importGlb: 'Import a .glb from your computer…',
  catPrimitivas: 'Primitives',
  catEstrutura: 'Structure',
  catConstrucoes: 'Buildings',
  catNatureza: 'Nature',
  catMoveis: 'Furniture',
  catVeiculos: 'Vehicles',
  catObjetos: 'Objects',
  catLuzes: 'Lights',
  catAmbiente: 'Ambience',
  catImportado: 'Imported',
  mkSpawnA: 'Team A spawn',
  mkSpawnB: 'Team B spawn',
  mkSpawnFfa: 'Free-for-all spawn',
  mkBoneco: 'Training dummy',
  mkCereja: 'Cherry (collectible)',
  mkBiscoito: 'Biscuit (collectible)',
  mkBruxa: "Witch's spot",
  mkRato: 'Rat (object)',
  mkPeixe: 'Fish',
  mkSurgir: 'Zombie: rising spot',
  mkCaixa: 'Zombie: coffin',
  mkChefe: 'Zombie: boss {id}',
  mkBarricada: 'Zombie: gap {id}',
  mkDentro: 'Zombie: wall corner',
  mkZumbiOn: 'Create the zombie mode data',
  inspector: 'Properties',
  mapSettings: 'Map',
  nothingSelected: "Nothing selected: these are the map's settings.",
  piece: 'Piece',
  kind: 'Kind',
  position: 'Position',
  yaw: 'Turn (degrees)',
  scaleField: 'Scale',
  pose: 'Pose (gizmo)',
  posePos: 'Offset',
  poseRot: 'Turn X, Y, Z (degrees)',
  poseClear: 'Clear the pose',
  seed: 'Seed',
  propId: 'Gag id',
  collectible: 'Collectible',
  none: 'none',
  params: 'Parameters',
  optional: 'use',
  addItem: '+ item',
  removeItem: 'remove',
  addOpening: '+ opening',
  jsonInvalid: 'Invalid JSON',
  killY: 'Death below (killY)',
  cell: 'Batch cell (m)',
  shadow: 'Sun shadow (half width, m)',
  dome: 'Sky',
  domeNone: 'day (default)',
  domeClouds: 'clouds',
  domeMoon: 'moon',
  domeOriental: 'oriental night',
  atmosphere: 'Light and fog (JSON)',
  sounds: 'Ambient sounds (JSON)',
  lights: 'Real lights',
  patrol: 'Patrol',
  lake: 'Pond',
  loop: 'Loop (x, z, radius)',
  depth: 'Depth (y)',
  width: 'Width',
  axis: 'Axis',
  budget: 'Budget',
  budgetMeasuring: 'measuring…',
  budgetText: '{dc} / {dcMax} draw calls · {tri} / {triMax} triangles',
  budgetOver: 'Over the limit: {o}',
  budgetDrawCalls: 'draw calls',
  budgetTriangles: 'triangles',
  invalid: 'The map has problems ({n}):',
  saveTitle: 'Save the map',
  name: 'Name',
  emoji: 'Emoji',
  color: 'Card color',
  modes: 'Modes',
  modesOpen: 'open (deathmatch, gun game, bots and training)',
  modesZombie: 'zombie mode only',
  kindLabel: 'Kind',
  official: 'official',
  community: 'community',
  officialOnlyStaff: 'Only admins and moderators save official maps.',
  baseVersion: 'Editing version {v}',
  saveConfirm: 'Save',
  cancel: 'Cancel',
  saving: 'Saving…',
  saved: 'Saved: version {v}.',
  errStale: 'Someone saved version {v} of this map while you were editing. Nothing was saved: choose what to do.',
  staleForce: 'Save as a new version anyway',
  staleForceHint: 'Version {v} stays in the history.',
  staleOpen: 'Open the current version',
  staleOpenHint: 'Drops your edits.',
  errBudget: 'The server refused it: {o} ({dc} draw calls, {tri} triangles; limit {dcMax} and {triMax}).',
  errInvalid: 'The server refused the map:',
  errPermission: "You can't save this map.",
  errSignedOut: 'Sign in to save.',
  errOffline: 'No connection to the server.',
  errOther: "Couldn't save ({e}).",
  testInvalid: 'Fix the map before playing it.',
  glbTooBig: 'The file is over 10 MB.',
  glbUploading: 'Uploading {nome}…',
  glbDone: '{nome} uploaded.',
  glbInvalid: 'Model refused: {m}',
  glbQuota: 'Your model quota is used up.',
  glbRate: 'Too many uploads this hour: try later.',
  glbFailed: "Couldn't upload the model ({e}).",
  buildFailed: "Piece {id} didn't build: {e}",
  limitReached: 'The map already has the most "{nome}" it may have.',
  draftTitle: 'Saved draft',
  draftText: 'This map has a draft from {quando}, newer than the saved version. Recover the edits?',
  draftTextNew: 'There is a draft of a new map from {quando}. Recover it?',
  draftRecover: 'Recover the draft',
  draftDiscard: 'Discard',
  draftRecovered: 'Draft recovered (not saved yet).',
  play: 'Play: play the map here, in the Game tab (the training range; on a zombie-only map, the zombie match alone)',
  pause: 'Pause: freezes the game and frees the mouse (▶ goes on)',
  stop: 'Stop: ends the game and goes back to editing where you were',
  panelGame: 'Game',
  gameIdle: "Press ▶ (Play) to play the editor's map here, even unsaved.",
  gameLoading: 'Opening the game…',
  playFailed: "The game didn't open: {e}",
  playTimeout: 'the game took too long to open',
  playPausedVeil: '❚❚ Paused · ▶ goes on · ■ back to editing',
  playing: 'Playing: the editor only looks (■ to edit).',
  paused: 'Paused: the Scene camera and the selection work; nothing changes the map.',
  thumbSize: 'Thumbnail size',
  thumbsDrawing: 'Drawing {n} thumbnail(s)…',
  projectEmpty: 'Nothing here.',
  markerNeedsZombie: 'Needs the zombie mode data (in the map Inspector).',
  layout: 'Layout',
  layoutReset: 'Restore the default layout',
  panelHierarchy: 'Hierarchy',
  panelScene: 'Scene',
  panelInspector: 'Inspector',
  panelProject: 'Project',
  hierCreate: 'Create',
  hierNewGroup: 'Empty group',
  hierGroupSel: 'Group the selection (Ctrl+G)',
  hierSearch: 'Search the scene…',
  cantMove: "A group can't go into itself or into a group inside it.",
  manySelected: '{n} pieces selected',
  mixedKinds: 'Different kinds: only the Transform is edited together.',
  mixedValues: 'The selected pieces have different values.',
  nameField: 'Name (empty: the id)',
  group: 'Group',
  transform: 'Transform',
  rotation: 'Rotation (degrees)',
  dragHint: 'Drag to change (Shift: faster)',
};

export type EditorKey = keyof typeof pt;

/** An editor text in the game's language, with {params}. */
export function et(key: EditorKey, params: Record<string, string | number> = {}): string {
  const dict = getLang() === 'pt-BR' ? pt : en;
  return dict[key].replace(/\{(\w+)\}/g, (_, k) => String(params[k] ?? ''));
}

/** A piece kind's or category's name in the game's language. */
export const nameOf = (n: { pt: string; en: string }) => (getLang() === 'pt-BR' ? n.pt : n.en);
