// The map editor's texts (pt-BR and en), apart from the game's (client/ui/strings.ts): the same language the
// game picked (getLang).
import { getLang } from '../ui/strings';

const pt = {
  title: 'Editor de mapas',
  newMap: 'Mapa novo',
  loading: 'Carregando o mapa…',
  loadFailed: 'Não deu para abrir o mapa: {erro}',
  undo: 'Desfazer (Ctrl+Z)',
  redo: 'Refazer (Ctrl+Y)',
  move: 'Mover (1)',
  rotate: 'Girar (2)',
  scale: 'Escalar (3)',
  snap: 'Encaixe 0,5 m e 15° (Shift segurado tira)',
  focus: 'Centralizar (F)',
  duplicate: 'Duplicar (Ctrl+D)',
  remove: 'Apagar (Delete)',
  test: 'Testar',
  save: 'Salvar',
  exit: 'Sair',
  exitConfirm: 'Sair do editor? O que não foi salvo se perde.',
  hint: 'WASD e Q/E andam · botão direito arrastado olha · Shift acelera · clique seleciona · 1/2/3 mover, girar, escalar',
  search: 'Buscar peça…',
  markers: 'Marcadores',
  imported: 'Modelos GLB',
  importGlb: 'Importar .glb do computador…',
  catPrimitivas: 'Primitivas',
  catEstrutura: 'Estrutura',
  catConstrucoes: 'Construções',
  catNatureza: 'Natureza',
  catMoveis: 'Móveis',
  catVeiculos: 'Veículos',
  catObjetos: 'Objetos',
  catLuzes: 'Luzes',
  catAmbiente: 'Ambiente',
  catImportado: 'Importado',
  mkSpawnA: 'Spawn time A',
  mkSpawnB: 'Spawn time B',
  mkSpawnFfa: 'Spawn livre (FFA)',
  mkBoneco: 'Boneco de treino',
  mkCereja: 'Cereja (coletável)',
  mkBiscoito: 'Biscoito (coletável)',
  mkBruxa: 'Lugar da bruxa',
  mkRato: 'Rato (objeto)',
  mkPeixe: 'Peixe',
  mkSurgir: 'Zumbi: surgimento',
  mkCaixa: 'Zumbi: caixão',
  mkChefe: 'Zumbi: chefe {id}',
  mkBarricada: 'Zumbi: brecha {id}',
  mkDentro: 'Zumbi: canto do muro',
  mkZumbiOn: 'Criar os dados do modo zumbi',
  inspector: 'Propriedades',
  mapSettings: 'Mapa',
  nothingSelected: 'Nada selecionado: estas são as configurações do mapa.',
  piece: 'Peça',
  kind: 'Tipo',
  position: 'Posição',
  yaw: 'Giro (graus)',
  scaleField: 'Escala',
  pose: 'Pose (gizmo)',
  posePos: 'Deslocamento',
  poseRot: 'Giro X, Y, Z (graus)',
  poseClear: 'Tirar a pose',
  seed: 'Semente',
  propId: 'Id da piada',
  collectible: 'Coletável',
  none: 'nenhum',
  params: 'Parâmetros',
  optional: 'usar',
  addItem: '+ item',
  removeItem: 'tirar',
  addOpening: '+ vão',
  jsonInvalid: 'JSON inválido',
  killY: 'Morte abaixo de (killY)',
  cell: 'Célula dos lotes (m)',
  shadow: 'Sombra do sol (meia largura, m)',
  dome: 'Céu',
  domeNone: 'dia (padrão)',
  domeClouds: 'nuvens',
  domeMoon: 'lua',
  domeOriental: 'noite oriental',
  atmosphere: 'Luz e neblina (JSON)',
  sounds: 'Sons ambientes (JSON)',
  lights: 'Luzes reais',
  patrol: 'Patrulha',
  lake: 'Lago',
  loop: 'Volta (x, z, raio)',
  depth: 'Profundidade (y)',
  width: 'Largura',
  axis: 'Eixo',
  budget: 'Orçamento',
  budgetMeasuring: 'medindo…',
  budgetText: '{dc} / {dcMax} chamadas · {tri} / {triMax} triângulos',
  budgetOver: 'Passou do limite: {o}',
  budgetDrawCalls: 'chamadas de desenho',
  budgetTriangles: 'triângulos',
  invalid: 'O mapa tem problemas ({n}):',
  saveTitle: 'Salvar o mapa',
  name: 'Nome',
  emoji: 'Emoji',
  color: 'Cor do cartão',
  modes: 'Modos',
  modesOpen: 'aberto (mata-mata, corrida armada, bots e treino)',
  modesZombie: 'exclusivo do modo zumbi',
  kindLabel: 'Tipo',
  official: 'oficial',
  community: 'comunidade',
  officialOnlyStaff: 'Só admin e moderador salvam mapas oficiais.',
  baseVersion: 'Editando a versão {v}',
  saveConfirm: 'Salvar',
  cancel: 'Cancelar',
  saving: 'Salvando…',
  saved: 'Salvo: versão {v}.',
  errStale: 'Alguém salvou a versão {v} deste mapa enquanto você editava. O seu rascunho continua aqui; nada foi salvo.',
  errBudget: 'O servidor recusou: {o} ({dc} chamadas, {tri} triângulos; limite {dcMax} e {triMax}).',
  errInvalid: 'O servidor recusou o mapa:',
  errPermission: 'Você não pode salvar este mapa.',
  errSignedOut: 'Entre na sua conta para salvar.',
  errOffline: 'Sem conexão com o servidor.',
  errOther: 'Não deu para salvar ({e}).',
  testing: 'Abrindo o teste…',
  testInvalid: 'Corrija o mapa antes de testar.',
  glbTooBig: 'O arquivo passa de 10 MB.',
  glbUploading: 'Enviando {nome}…',
  glbDone: '{nome} enviado.',
  glbInvalid: 'Modelo recusado: {m}',
  glbQuota: 'Sua cota de modelos acabou.',
  glbRate: 'Muitos envios nesta hora: tente mais tarde.',
  glbFailed: 'Não deu para enviar o modelo ({e}).',
  buildFailed: 'A peça {id} não montou: {e}',
  limitReached: 'O mapa já tem o máximo de "{nome}".',
  devEntry: 'Editor (dev)',
};

const en: Record<keyof typeof pt, string> = {
  title: 'Map editor',
  newMap: 'New map',
  loading: 'Loading the map…',
  loadFailed: "Couldn't open the map: {erro}",
  undo: 'Undo (Ctrl+Z)',
  redo: 'Redo (Ctrl+Y)',
  move: 'Move (1)',
  rotate: 'Rotate (2)',
  scale: 'Scale (3)',
  snap: 'Snap 0.5 m and 15° (hold Shift to turn off)',
  focus: 'Focus (F)',
  duplicate: 'Duplicate (Ctrl+D)',
  remove: 'Delete (Delete)',
  test: 'Test',
  save: 'Save',
  exit: 'Exit',
  exitConfirm: 'Leave the editor? Anything not saved is lost.',
  hint: 'WASD and Q/E move · right-drag looks · Shift goes faster · click selects · 1/2/3 move, rotate, scale',
  search: 'Search pieces…',
  markers: 'Markers',
  imported: 'GLB models',
  importGlb: 'Import a .glb from your computer…',
  catPrimitivas: 'Primitives',
  catEstrutura: 'Structure',
  catConstrucoes: 'Buildings',
  catNatureza: 'Nature',
  catMoveis: 'Furniture',
  catVeiculos: 'Vehicles',
  catObjetos: 'Objects',
  catLuzes: 'Lights',
  catAmbiente: 'Ambience',
  catImportado: 'Imported',
  mkSpawnA: 'Team A spawn',
  mkSpawnB: 'Team B spawn',
  mkSpawnFfa: 'Free-for-all spawn',
  mkBoneco: 'Training dummy',
  mkCereja: 'Cherry (collectible)',
  mkBiscoito: 'Biscuit (collectible)',
  mkBruxa: "Witch's spot",
  mkRato: 'Rat (object)',
  mkPeixe: 'Fish',
  mkSurgir: 'Zombie: rising spot',
  mkCaixa: 'Zombie: coffin',
  mkChefe: 'Zombie: boss {id}',
  mkBarricada: 'Zombie: gap {id}',
  mkDentro: 'Zombie: wall corner',
  mkZumbiOn: 'Create the zombie mode data',
  inspector: 'Properties',
  mapSettings: 'Map',
  nothingSelected: "Nothing selected: these are the map's settings.",
  piece: 'Piece',
  kind: 'Kind',
  position: 'Position',
  yaw: 'Turn (degrees)',
  scaleField: 'Scale',
  pose: 'Pose (gizmo)',
  posePos: 'Offset',
  poseRot: 'Turn X, Y, Z (degrees)',
  poseClear: 'Clear the pose',
  seed: 'Seed',
  propId: 'Gag id',
  collectible: 'Collectible',
  none: 'none',
  params: 'Parameters',
  optional: 'use',
  addItem: '+ item',
  removeItem: 'remove',
  addOpening: '+ opening',
  jsonInvalid: 'Invalid JSON',
  killY: 'Death below (killY)',
  cell: 'Batch cell (m)',
  shadow: 'Sun shadow (half width, m)',
  dome: 'Sky',
  domeNone: 'day (default)',
  domeClouds: 'clouds',
  domeMoon: 'moon',
  domeOriental: 'oriental night',
  atmosphere: 'Light and fog (JSON)',
  sounds: 'Ambient sounds (JSON)',
  lights: 'Real lights',
  patrol: 'Patrol',
  lake: 'Pond',
  loop: 'Loop (x, z, radius)',
  depth: 'Depth (y)',
  width: 'Width',
  axis: 'Axis',
  budget: 'Budget',
  budgetMeasuring: 'measuring…',
  budgetText: '{dc} / {dcMax} draw calls · {tri} / {triMax} triangles',
  budgetOver: 'Over the limit: {o}',
  budgetDrawCalls: 'draw calls',
  budgetTriangles: 'triangles',
  invalid: 'The map has problems ({n}):',
  saveTitle: 'Save the map',
  name: 'Name',
  emoji: 'Emoji',
  color: 'Card color',
  modes: 'Modes',
  modesOpen: 'open (deathmatch, gun game, bots and training)',
  modesZombie: 'zombie mode only',
  kindLabel: 'Kind',
  official: 'official',
  community: 'community',
  officialOnlyStaff: 'Only admins and moderators save official maps.',
  baseVersion: 'Editing version {v}',
  saveConfirm: 'Save',
  cancel: 'Cancel',
  saving: 'Saving…',
  saved: 'Saved: version {v}.',
  errStale: 'Someone saved version {v} of this map while you were editing. Your draft is still here; nothing was saved.',
  errBudget: 'The server refused it: {o} ({dc} draw calls, {tri} triangles; limit {dcMax} and {triMax}).',
  errInvalid: 'The server refused the map:',
  errPermission: "You can't save this map.",
  errSignedOut: 'Sign in to save.',
  errOffline: 'No connection to the server.',
  errOther: "Couldn't save ({e}).",
  testing: 'Opening the test…',
  testInvalid: 'Fix the map before testing it.',
  glbTooBig: 'The file is over 10 MB.',
  glbUploading: 'Uploading {nome}…',
  glbDone: '{nome} uploaded.',
  glbInvalid: 'Model refused: {m}',
  glbQuota: 'Your model quota is used up.',
  glbRate: 'Too many uploads this hour: try later.',
  glbFailed: "Couldn't upload the model ({e}).",
  buildFailed: "Piece {id} didn't build: {e}",
  limitReached: 'The map already has the most "{nome}" it may have.',
  devEntry: 'Editor (dev)',
};

export type EditorKey = keyof typeof pt;

/** An editor text in the game's language, with {params}. */
export function et(key: EditorKey, params: Record<string, string | number> = {}): string {
  const dict = getLang() === 'pt-BR' ? pt : en;
  return dict[key].replace(/\{(\w+)\}/g, (_, k) => String(params[k] ?? ''));
}

/** A piece kind's or category's name in the game's language. */
export const nameOf = (n: { pt: string; en: string }) => (getLang() === 'pt-BR' ? n.pt : n.en);
