// The map editor's texts in German (PF-30); the keys are client/editor/strings.ts's.
import type { EditorKey } from './strings';

export const de: Record<EditorKey, string> = {
  title: 'Karteneditor',
  newMap: 'Neue Karte',
  loading: 'Karte wird geladen…',
  loadFailed: 'Karte konnte nicht geöffnet werden: {erro}',
  undo: 'Rückgängig (Strg+Z)',
  redo: 'Wiederholen (Strg+Y)',
  hand: 'Hand (Q)',
  move: 'Verschieben (W)',
  rotate: 'Drehen (E)',
  scale: 'Skalieren (R)',
  rect: 'Rechteck (T)',
  pivot: 'Drehpunkt',
  center: 'Mitte',
  pivotTip: 'Drehpunkt: das Gizmo am aktiven Teil · Mitte: in der Mitte der Auswahl (dreht und skaliert um diesen Punkt)',
  local: 'Lokal',
  global: 'Global',
  spaceTip: 'Lokal: Die Gizmo-Achsen drehen sich mit dem aktiven Teil · Global: die Weltachsen',
  grid: 'Raster',
  gridTip: 'Einrasten immer an (aus: Strg halten zum Einrasten)',
  gridMenu: 'Rasterschritte',
  gridMove: 'Verschieben (m)',
  gridTurn: 'Drehen (Grad)',
  viewPersp: 'Persp',
  viewOrtho: 'Ortho',
  viewTip: 'Klick auf eine Achse, um von dieser Seite zu schauen (Y: von oben); die Mitte wechselt zwischen perspektivisch und orthografisch',
  copied: 'Kopiert: {n} Teil(e).',
  pasteEmpty: 'Noch nichts kopiert (Strg+C).',
  focus: 'Zentrieren (F)',
  duplicate: 'Duplizieren (Strg+D)',
  remove: 'Löschen (Entf)',
  save: 'Speichern',
  exit: 'Beenden',
  exitConfirm: 'Editor verlassen? Alles nicht Gespeicherte geht verloren.',
  hint: 'Rechte Maustaste + WASD/QE fliegt · Alt + Ziehen umkreist · mittlere Taste verschiebt · Mausrad zoomt · Q W E R T Werkzeuge · Strg rastet ein · Ziehen wählt per Rahmen · F zentriert',
  search: 'Teil suchen…',
  markers: 'Marker',
  imported: 'GLB-Modelle',
  importGlb: '.glb vom Computer importieren…',
  catPrimitivas: 'Primitive',
  catEstrutura: 'Struktur',
  catConstrucoes: 'Gebäude',
  catNatureza: 'Natur',
  catMoveis: 'Möbel',
  catVeiculos: 'Fahrzeuge',
  catObjetos: 'Objekte',
  catLuzes: 'Lichter',
  catAmbiente: 'Ambiente',
  catImportado: 'Importiert',
  mkSpawnA: 'Spawn Team A',
  mkSpawnB: 'Spawn Team B',
  mkSpawnFfa: 'Freier Spawn (FFA)',
  mkBoneco: 'Zielpuppe',
  mkCereja: 'Kirsche (Sammelobjekt)',
  mkBiscoito: 'Keks (Sammelobjekt)',
  mkBruxa: 'Platz der Hexe',
  mkRato: 'Ratte (Objekt)',
  mkPeixe: 'Fisch',
  mkSurgir: 'Zombie: Auftauchpunkt',
  mkCaixa: 'Zombie: Sarg',
  mkChefe: 'Zombie: Boss {id}',
  mkBarricada: 'Zombie: Lücke {id}',
  mkDentro: 'Zombie: Mauerecke',
  mkZumbiOn: 'Zombie-Modus-Daten erstellen',
  inspector: 'Eigenschaften',
  mapSettings: 'Karte',
  nothingSelected: 'Nichts ausgewählt: Das sind die Karteneinstellungen.',
  piece: 'Teil',
  kind: 'Typ',
  position: 'Position',
  yaw: 'Drehung (Grad)',
  scaleField: 'Skalierung',
  pose: 'Pose (Gizmo)',
  posePos: 'Versatz',
  poseRot: 'Drehung X, Y, Z (Grad)',
  poseClear: 'Pose entfernen',
  seed: 'Startwert',
  propId: 'Gag-ID',
  collectible: 'Sammelobjekt',
  none: 'keins',
  params: 'Parameter',
  optional: 'verwenden',
  addItem: '+ Eintrag',
  removeItem: 'entfernen',
  addOpening: '+ Öffnung',
  jsonInvalid: 'Ungültiges JSON',
  killY: 'Tod unterhalb von (killY)',
  cell: 'Batch-Zelle (m)',
  shadow: 'Sonnenschatten (halbe Breite, m)',
  dome: 'Himmel',
  domeNone: 'Tag (Standard)',
  domeClouds: 'Wolken',
  domeMoon: 'Mond',
  domeOriental: 'orientalische Nacht',
  atmosphere: 'Licht und Nebel (JSON)',
  sounds: 'Umgebungsgeräusche (JSON)',
  lights: 'Echte Lichter',
  patrol: 'Patrouille',
  lake: 'Teich',
  loop: 'Runde (x, z, Radius)',
  depth: 'Tiefe (y)',
  width: 'Breite',
  axis: 'Achse',
  budget: 'Budget',
  budgetMeasuring: 'wird gemessen…',
  budgetText: '{dc} / {dcMax} Draw Calls · {tri} / {triMax} Dreiecke',
  budgetOver: 'Limit überschritten: {o}',
  budgetDrawCalls: 'Draw Calls',
  budgetTriangles: 'Dreiecke',
  budgetLight: 'Achtung: Mit dem Detail Leicht (Handys) liegt es über der Empfehlung: {o}',
  budgetWorst: 'schlechteste Kamera {v} Dreiecke (bis {max})',
  budgetMedian: 'mittlere Kamera {v} Dreiecke (bis {max})',
  budgetShadow: 'Schatten {v} Dreiecke (bis {max})',
  budgetCalls: '{v} Draw Calls (bis {max})',
  invalid: 'Die Karte hat Probleme ({n}):',
  saveTitle: 'Karte speichern',
  name: 'Name',
  emoji: 'Emoji',
  color: 'Kachelfarbe',
  modes: 'Modi',
  modesOpen: 'offen (Jeder gegen jeden, Waffenrennen, Bots und Training)',
  modesZombie: 'nur Zombie-Modus',
  kindLabel: 'Typ',
  official: 'offiziell',
  community: 'Community',
  officialOnlyStaff: 'Nur Admins und Moderatoren speichern offizielle Karten.',
  baseVersion: 'Bearbeite Version {v}',
  saveConfirm: 'Speichern',
  cancel: 'Abbrechen',
  saving: 'Wird gespeichert…',
  saved: 'Gespeichert: Version {v}.',
  errStale: 'Jemand hat Version {v} dieser Karte gespeichert, während du sie bearbeitet hast. Nichts wurde gespeichert: Wähle, was du tun willst.',
  staleForce: 'Trotzdem als neue Version speichern',
  staleForceHint: 'Version {v} bleibt im Verlauf.',
  staleOpen: 'Aktuelle Version öffnen',
  staleOpenHint: 'Verwirft deine Änderungen.',
  errBudget: 'Der Server hat abgelehnt: {o} ({dc} Draw Calls, {tri} Dreiecke; Limit {dcMax} und {triMax}).',
  errInvalid: 'Der Server hat die Karte abgelehnt:',
  errPermission: 'Du kannst diese Karte nicht speichern.',
  errSignedOut: 'Melde dich an, um zu speichern.',
  errOffline: 'Keine Verbindung zum Server.',
  errOther: 'Speichern fehlgeschlagen ({e}).',
  testInvalid: 'Korrigiere die Karte, bevor du sie spielst (Play).',
  glbTooBig: 'Die Datei ist größer als 10 MB.',
  glbUploading: '{nome} wird hochgeladen…',
  glbDone: '{nome} hochgeladen.',
  glbInvalid: 'Modell abgelehnt: {m}',
  glbQuota: 'Dein Modell-Kontingent ist aufgebraucht.',
  glbRate: 'Zu viele Uploads in dieser Stunde: Versuch es später.',
  glbFailed: 'Modell konnte nicht hochgeladen werden ({e}).',
  buildFailed: 'Teil {id} wurde nicht gebaut: {e}',
  limitReached: 'Die Karte hat schon das Maximum an "{nome}".',
  draftTitle: 'Gespeicherter Entwurf',
  draftText: 'Diese Karte hat einen Entwurf von {quando}, neuer als die gespeicherte Version. Änderungen wiederherstellen?',
  draftTextNew: 'Es gibt einen Entwurf einer neuen Karte von {quando}. Wiederherstellen?',
  draftRecover: 'Entwurf wiederherstellen',
  draftDiscard: 'Verwerfen',
  draftRecovered: 'Entwurf wiederhergestellt (noch nicht gespeichert).',
  play: 'Play: Spiel die Karte hier im Tab Spiel (das Training; auf einer reinen Zombie-Karte das Zombie-Match allein)',
  pause: 'Pause: friert das Spiel ein und gibt die Maus frei (▶ geht weiter)',
  stop: 'Stop: beendet das Spiel und kehrt zum Bearbeiten an derselben Stelle zurück',
  panelGame: 'Spiel',
  gameIdle: 'Drück ▶ (Play), um die Editor-Karte hier zu spielen, auch ungespeichert.',
  gameLoading: 'Spiel wird geöffnet…',
  playFailed: 'Das Spiel ließ sich nicht öffnen: {e}',
  playTimeout: 'das Spiel hat zu lange zum Öffnen gebraucht',
  playPausedVeil: '❚❚ Pausiert · ▶ weiter · ■ zurück zum Bearbeiten',
  playing: 'Im Spiel: Der Editor schaut nur zu (■ zum Bearbeiten).',
  paused: 'Pausiert: Szenen-Kamera und Auswahl funktionieren; nichts ändert die Karte.',
  thumbSize: 'Miniaturgröße',
  thumbsDrawing: 'Zeichne {n} Miniatur(en)…',
  projectEmpty: 'Hier ist nichts.',
  markerNeedsZombie: 'Braucht die Zombie-Modus-Daten (im Inspektor der Karte).',
  layout: 'Layout',
  layoutReset: 'Standard-Layout wiederherstellen',
  panelHierarchy: 'Hierarchie',
  panelScene: 'Szene',
  panelInspector: 'Inspektor',
  panelProject: 'Projekt',
  hierCreate: 'Erstellen',
  hierNewGroup: 'Leere Gruppe',
  hierGroupSel: 'Auswahl gruppieren (Strg+G)',
  hierSearch: 'In der Szene suchen…',
  cantMove: 'Eine Gruppe kann nicht in sich selbst oder in eine ihrer Untergruppen.',
  manySelected: '{n} Teile ausgewählt',
  mixedKinds: 'Verschiedene Typen: Nur Transform wird gemeinsam bearbeitet.',
  mixedValues: 'Die ausgewählten Teile haben unterschiedliche Werte.',
  nameField: 'Name (leer: die ID)',
  group: 'Gruppe',
  transform: 'Transform',
  rotation: 'Rotation (Grad)',
  dragHint: 'Ziehen zum Ändern (Shift: schneller)',
};
