// The map editor's texts in Spanish (es-419) (PF-30); the keys are client/editor/strings.ts's.
import type { EditorKey } from './strings';

export const es: Record<EditorKey, string> = {
  title: 'Editor de mapas',
  newMap: 'Mapa nuevo',
  loading: 'Cargando el mapa…',
  loadFailed: 'No se pudo abrir el mapa: {erro}',
  undo: 'Deshacer (Ctrl+Z)',
  redo: 'Rehacer (Ctrl+Y)',
  hand: 'Mano (Q)',
  move: 'Mover (W)',
  rotate: 'Rotar (E)',
  scale: 'Escalar (R)',
  rect: 'Rectángulo (T)',
  pivot: 'Pivote',
  center: 'Centro',
  pivotTip: 'Pivote: el gizmo en la pieza activa · Centro: en medio de la selección (gira y escala alrededor de él)',
  local: 'Local',
  global: 'Global',
  spaceTip: 'Local: los ejes del gizmo giran con la pieza activa · Global: los ejes del mundo',
  grid: 'Cuadrícula',
  gridTip: 'Ajuste siempre activo (desactivado: mantén Ctrl para ajustar)',
  gridMenu: 'Pasos de ajuste',
  gridMove: 'Mover (m)',
  gridTurn: 'Rotar (grados)',
  viewPersp: 'Persp',
  viewOrtho: 'Orto',
  viewTip: 'Haz clic en un eje para mirar desde ese lado (Y: desde arriba); en el centro, perspectiva u ortográfica',
  copied: 'Copiado: {n} pieza(s).',
  pasteEmpty: 'Aún no copiaste nada (Ctrl+C).',
  focus: 'Centrar (F)',
  duplicate: 'Duplicar (Ctrl+D)',
  remove: 'Eliminar (Delete)',
  save: 'Guardar',
  exit: 'Salir',
  exitConfirm: '¿Salir del editor? Lo que no se guardó se pierde.',
  hint: 'Botón derecho + WASD/QE vuela · Alt + arrastrar orbita · botón central desplaza · rueda acerca · Q W E R T herramientas · Ctrl ajusta · arrastrar selecciona con caja · F centra',
  search: 'Buscar pieza…',
  markers: 'Marcadores',
  imported: 'Modelos GLB',
  importGlb: 'Importar .glb desde la computadora…',
  catPrimitivas: 'Primitivas',
  catEstrutura: 'Estructura',
  catConstrucoes: 'Construcciones',
  catNatureza: 'Naturaleza',
  catMoveis: 'Muebles',
  catVeiculos: 'Vehículos',
  catObjetos: 'Objetos',
  catLuzes: 'Luces',
  catAmbiente: 'Ambiente',
  catImportado: 'Importado',
  mkSpawnA: 'Spawn equipo A',
  mkSpawnB: 'Spawn equipo B',
  mkSpawnFfa: 'Spawn libre (FFA)',
  mkBoneco: 'Muñeco de práctica',
  mkCereja: 'Cereza (coleccionable)',
  mkBiscoito: 'Galleta (coleccionable)',
  mkBruxa: 'Lugar de la bruja',
  mkRato: 'Rata (objeto)',
  mkPeixe: 'Pez',
  mkSurgir: 'Zombi: punto de aparición',
  mkCaixa: 'Zombi: ataúd',
  mkChefe: 'Zombi: jefe {id}',
  mkBarricada: 'Zombi: brecha {id}',
  mkDentro: 'Zombi: esquina del muro',
  mkZumbiOn: 'Crear los datos del modo zombi',
  inspector: 'Propiedades',
  mapSettings: 'Mapa',
  nothingSelected: 'Nada seleccionado: esta es la configuración del mapa.',
  piece: 'Pieza',
  kind: 'Tipo',
  position: 'Posición',
  yaw: 'Giro (grados)',
  scaleField: 'Escala',
  pose: 'Pose (gizmo)',
  posePos: 'Desplazamiento',
  poseRot: 'Giro X, Y, Z (grados)',
  poseClear: 'Quitar la pose',
  seed: 'Semilla',
  propId: 'Id de la broma',
  collectible: 'Coleccionable',
  none: 'ninguno',
  params: 'Parámetros',
  optional: 'usar',
  addItem: '+ elemento',
  removeItem: 'quitar',
  addOpening: '+ abertura',
  jsonInvalid: 'JSON inválido',
  killY: 'Muerte por debajo de (killY)',
  cell: 'Celda de lotes (m)',
  shadow: 'Sombra del sol (medio ancho, m)',
  dome: 'Cielo',
  domeNone: 'día (predeterminado)',
  domeClouds: 'nubes',
  domeMoon: 'luna',
  domeOriental: 'noche oriental',
  atmosphere: 'Luz y niebla (JSON)',
  sounds: 'Sonidos ambientales (JSON)',
  lights: 'Luces reales',
  patrol: 'Patrulla',
  lake: 'Estanque',
  loop: 'Vuelta (x, z, radio)',
  depth: 'Profundidad (y)',
  width: 'Ancho',
  axis: 'Eje',
  budget: 'Presupuesto',
  budgetMeasuring: 'midiendo…',
  budgetText: '{dc} / {dcMax} llamadas · {tri} / {triMax} triángulos',
  budgetOver: 'Superó el límite: {o}',
  budgetDrawCalls: 'llamadas de dibujo',
  budgetTriangles: 'triángulos',
  budgetLight: 'Aviso: con el detalle Ligero (celulares) supera lo recomendado: {o}',
  budgetWorst: 'peor cámara {v} triángulos (hasta {max})',
  budgetMedian: 'cámara mediana {v} triángulos (hasta {max})',
  budgetShadow: 'sombra {v} triángulos (hasta {max})',
  budgetCalls: '{v} llamadas de dibujo (hasta {max})',
  invalid: 'El mapa tiene problemas ({n}):',
  saveTitle: 'Guardar el mapa',
  name: 'Nombre',
  emoji: 'Emoji',
  color: 'Color de la tarjeta',
  modes: 'Modos',
  modesOpen: 'abierto (combate a muerte, carrera armada, bots y práctica)',
  modesZombie: 'exclusivo del modo zombi',
  kindLabel: 'Tipo',
  official: 'oficial',
  community: 'comunidad',
  officialOnlyStaff: 'Solo admins y moderadores guardan mapas oficiales.',
  baseVersion: 'Editando la versión {v}',
  saveConfirm: 'Guardar',
  cancel: 'Cancelar',
  saving: 'Guardando…',
  saved: 'Guardado: versión {v}.',
  errStale: 'Alguien guardó la versión {v} de este mapa mientras editabas. No se guardó nada: elige qué hacer.',
  staleForce: 'Guardar como nueva versión de todos modos',
  staleForceHint: 'La versión {v} sigue en el historial.',
  staleOpen: 'Abrir la versión actual',
  staleOpenHint: 'Descarta tus ediciones.',
  errBudget: 'El servidor lo rechazó: {o} ({dc} llamadas, {tri} triángulos; límite {dcMax} y {triMax}).',
  errInvalid: 'El servidor rechazó el mapa:',
  errPermission: 'No puedes guardar este mapa.',
  errSignedOut: 'Inicia sesión para guardar.',
  errOffline: 'Sin conexión con el servidor.',
  errOther: 'No se pudo guardar ({e}).',
  testInvalid: 'Corrige el mapa antes de jugarlo (Play).',
  glbTooBig: 'El archivo supera los 10 MB.',
  glbUploading: 'Subiendo {nome}…',
  glbDone: '{nome} subido.',
  glbInvalid: 'Modelo rechazado: {m}',
  glbQuota: 'Se agotó tu cuota de modelos.',
  glbRate: 'Demasiadas subidas en esta hora: intenta más tarde.',
  glbFailed: 'No se pudo subir el modelo ({e}).',
  buildFailed: 'La pieza {id} no se armó: {e}',
  limitReached: 'El mapa ya tiene el máximo de "{nome}".',
  draftTitle: 'Borrador guardado',
  draftText: 'Este mapa tiene un borrador de {quando}, más nuevo que la versión guardada. ¿Recuperar las ediciones?',
  draftTextNew: 'Hay un borrador de un mapa nuevo de {quando}. ¿Recuperarlo?',
  draftRecover: 'Recuperar el borrador',
  draftDiscard: 'Descartar',
  draftRecovered: 'Borrador recuperado (aún sin guardar).',
  play: 'Play: juega el mapa aquí, en la pestaña Juego (la práctica; en un mapa solo de zombis, la partida de zombis en solitario)',
  pause: 'Pause: congela el juego y libera el mouse (▶ continúa)',
  stop: 'Stop: termina el juego y vuelve a editar donde estabas',
  panelGame: 'Juego',
  gameIdle: 'Presiona ▶ (Play) para jugar aquí el mapa del editor, incluso sin guardar.',
  gameLoading: 'Abriendo el juego…',
  playFailed: 'El juego no se abrió: {e}',
  playTimeout: 'el juego tardó demasiado en abrir',
  playPausedVeil: '❚❚ En pausa · ▶ continúa · ■ vuelve a editar',
  playing: 'Jugando: el editor solo observa (■ para editar).',
  paused: 'En pausa: la cámara de la Escena y la selección funcionan; nada cambia el mapa.',
  thumbSize: 'Tamaño de las miniaturas',
  thumbsDrawing: 'Dibujando {n} miniatura(s)…',
  projectEmpty: 'Nada aquí.',
  markerNeedsZombie: 'Necesita los datos del modo zombi (en el Inspector del mapa).',
  layout: 'Diseño',
  layoutReset: 'Restaurar el diseño predeterminado',
  panelHierarchy: 'Jerarquía',
  panelScene: 'Escena',
  panelInspector: 'Inspector',
  panelProject: 'Proyecto',
  hierCreate: 'Crear',
  hierNewGroup: 'Grupo vacío',
  hierGroupSel: 'Agrupar la selección (Ctrl+G)',
  hierSearch: 'Buscar en la escena…',
  cantMove: 'Un grupo no puede entrar en sí mismo ni en un grupo dentro de él.',
  manySelected: '{n} piezas seleccionadas',
  mixedKinds: 'Tipos distintos: solo el Transform se edita en conjunto.',
  mixedValues: 'Los valores son distintos entre las piezas seleccionadas.',
  nameField: 'Nombre (vacío: el id)',
  group: 'Grupo',
  transform: 'Transform',
  rotation: 'Rotación (grados)',
  dragHint: 'Arrastra para cambiar (Shift: más rápido)',
};
